### ISSUE TITLE
Make "combined texture names" optional

### ISSUE THREAD

**Issue by vergol** [KhronosGroup/glTF-Blender-IO#1014]
**Is your feature request related to a problem? Please describe.**
Yes. I'm using images with alpha channel (so alpha is not in a separate file).
So I'm not very happy when the exporter gives me absurd names like "image_image_png.png"

Some example:
Source images: https://i.imgur.com/jzFn376.png
Images generated by the exporter: https://i.imgur.com/cRrnQGN.png

**Describe the solution you'd like**
Add an option (checkbox) to disable the "combined texture names" feature.

**Describe alternatives you've considered**
Alternative 1: Do not combine image names when they are the same image.
Alternative 2: Do not include alpha channel image name into "combined texture name".

**Additional context**
https://github.com/KhronosGroup/glTF-Blender-IO/blob/9dde650dc77fd1a1c9552a2773f0c3533f70683c/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_image.py#L219

**Comment by scurest** [comment]
I can't trigger this. Can you post a .blend file?

**Comment by vergol** [comment]
https://mega.nz/file/yh0CmSoQ#JmAhieEB27KWou7WZEMZiEEHMmYZL39ndIgrEUZ30wk

**Comment by scurest** [comment]
The reason this happens is you are using two different images (both pointing at the same backing file) instead of one image.

![jupiter](https://user-images.githubusercontent.com/11024420/79076713-f0e08600-7cc1-11ea-98af-dca172eb6cbb.png)

If you use one image (either by setting the same image on both Image Texture nodes, or by using one Image Texture node), you'll get a normal file name.

![jup1](https://user-images.githubusercontent.com/11024420/79076689-c55d9b80-7cc1-11ea-9623-e00935a3db98.png)
![jup2](https://user-images.githubusercontent.com/11024420/79076691-c8588c00-7cc1-11ea-9049-afbbf1678533.png)

**Comment by vergol** [comment]
I see, but still can't understand it. It's the same file, right? Just another instance in Blender. But GLTF writes it to 2 different files.
Also for some reason it changes the name of the texture inside the model.

When exporting same object to .fbx or .obj, there are no any problems with texture names.

![Image1](https://i.imgur.com/XZJCjF1.png)

![Image2](https://i.imgur.com/8uj2RAZ.png)

So can we make an option to disable this feature?

**Comment by scurest** [comment]
> It's the same file, right?

But its not the same _image_. For example, if you have two images you can draw on top of them and they will be different, even though they have the same backing file. The exported glTF will reflect what you see in Blender.

![twoimgs](https://user-images.githubusercontent.com/11024420/79077371-c218de80-7cc6-11ea-8840-e8418ec1d122.png)

> But GLTF writes it to 2 different files.  
> Also for some reason it changes the name of the texture inside the model.

Not sure what you mean. It only creates one .png for me.

**Comment by scurest** [comment]
One minor change that I guess would fix this...

If the exported image comes from exactly one Blender image, we already try to use that image's filename

https://github.com/KhronosGroup/glTF-Blender-IO/blob/9dde650dc77fd1a1c9552a2773f0c3533f70683c/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_image.py#L236-L241

We could change this so it checks if _all_ the Blender images being combined have the same filename, and try to use that.

**Comment by vergol** [comment]
Yes, my mistake. It creates only 1 file.
Thanks for the explanation.
Sometimes it's not expected and it changes the texture name.
It happens wide often for me when Blender creates copies of same texture with that ".001", ".002" at the end, when I'm importing from other model formats.

I don't know how to implement this as I'm not familiar with Blender API.
Maybe check if file path is identical, and also check if both images do not have any image effects applied (like that drawing effect)?

**Comment by scurest** [comment]
#1025 should fix your image name problem. Can you test it?

>  Maybe check if file path is identical, and also check if both images do not have any image effects applied (like that drawing effect)?

Yeah, maybe we should come up with a better way of deciding if there's only "one image" being combined (currently it requires literally one Blender image). You'll also have degraded performance when using two images since the exporter thinks it has to combine the channels instead of knowing it can just copy over the existing file. That's more involved than just doing the filenames though...

**Comment by vergol** [comment]
I tested and it works.
