### ISSUE TITLE
Action assignment only preserved for a single animation.

### ISSUE THREAD

**Issue by will-ca** [KhronosGroup/glTF-Blender-IO#1032]
**Describe the bug**
After exporting multiple animated Blender objects into a `gltf` file, only one of the objects will display its original animation when the file is re-imported.

The other objects' animations are exported into the `gltf` file; they just aren't assigned to the right objects on re-import.

**To Reproduce**
1. In an empty Blender project, add two or more mesh objects and create unique keyframe transformation actions for all of them.
2. Export to a `.glb` or `.gltf` file.
3. In another empty Blender project, re-import the `.glb` or `.gltf` file.

**Expected behavior**
Upon import, each of the objects from the `gltf` file has its action restored from before the export.

**Actual Behaviour**
The actions for each object are imported into the Blender project, and are visible in the `Action Editor`. **However**, they are not actually assigned to most of the objects.

Only one imported object has an action assigned. As a result, all of the imported objects except for one are stationary until their actions are re-assigned.

**Version**
 - OS: Linux
 - Blender Version 2.82a

**Additional context**
~~I haven't tested whether the fault occurs in the importer or in the exporter.~~

~~The actions are *in* the exported file, just not associated properly on import, and I think I roughly skimmed somewhere that the `gltf` format specifications allow animations only as a single track per object. If that's the case, then I suppose the dissociation must happen on import.~~

The actions are in the exported file, and are associated without apparent issue by other programs. It just seems incongruous to have a lossy export-import cycle that saves and reads all animations but only activates one of them on read.

**Comment by scurest** [comment]
To explain what happens:

The importer assigns exactly the actions so that the first animation in the glTF file is playing: see #952.

In the exporter, when _Animation > Animation > NLA Strips_ is on (the default), two actions get put into the same glTF animation only if they're pushed onto NLA tracks with the same name. When its off, all the currently assigned actions get put into a single glTF animation instead. (See the [docs](https://docs.blender.org/manual/en/2.82/addons/import_export/scene_gltf2.html#animation) for more.)

So you would, for example, see your expected behavior if you export with _Animation > Animation > NLA Strips_ off and then reimport.

**Comment by will-ca** [comment]
Oh, cool. Thank you for explaining that. Sorry I didn't see the other issue before opening this one.
