### ISSUE TITLE
Glitches in exported GLB animation values

### ISSUE THREAD

**Issue by punkoffice** [KhronosGroup/glTF-Blender-IO#1075]
**Describe the bug**
When exporting GLB, the animation gets corrupted and there can be sudden spikes in the values.  This happens without sampling and also sampling with low numbers.

**To Reproduce**
1. Export GLB with animation
2. Re-import, view animation graph for mixamorig:RightUpLeg
3. Playback animation

**Expected behavior**
Animation should be the same as what appears in the Blender file.

**Screenshots**
Attached to show original animation values to the values from the exported GLB.

**.blend file/ .gltf**
ZIP file attached

**Version**
 - OS: Windows 10 Home
 - Blender Version 2.82a
![glb_export_problem](https://user-images.githubusercontent.com/5295016/82755221-a94b2f00-9e15-11ea-9eb1-06659909d3c3.png)
[GLBanimation_glitch.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4673590/GLBanimation_glitch.zip)

**Comment by scurest** [comment]
Possibly related to https://developer.blender.org/T77811?

**Comment by scurest** [comment]
Seems to have been fixed by https://developer.blender.org/rB814b2787caddf5bd81477bd7b5dea8c45c402a72

Testing with the current 2.92 alpha, the spikes are gone. Animation looks correct visually.

![chicken](https://user-images.githubusercontent.com/11024420/100739370-96a14c00-339c-11eb-8d59-168001e0c7ac.png)
