### ISSUE TITLE
How to export armature animations for lights?

### ISSUE THREAD

**Issue by MennoVink** [KhronosGroup/glTF-Blender-IO#1090]
I've got a scene with a simple plane, a cube and some lights. I've created an armature with a few bones and parented the cube to a bone and the lights to one bone each. Now when i try to export the animation that tries to move the lights around by moving their bones i get an error log: 
![image](https://user-images.githubusercontent.com/26071817/84318729-2d6c1900-ab6f-11ea-9436-748b9876efbe.png)

Is it possible to have lights move around by attaching them to an animated bone?

This is the scene i'm trying to export: [AnimatedLights.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4761234/AnimatedLights.zip)

**Comment by julienduroure** [comment]
I found the root cause

https://github.com/KhronosGroup/glTF-Blender-IO/blob/877791ec61ea0d2ba290668b685f946c29c2b745/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py#L439

Corrective node use None for children, when it should be [ ] to avoid any error.
Will perform more tests to be sure to not have any regression
