### ISSUE TITLE
Importer: Packing of images should be optional

### ISSUE THREAD

**Issue by UX3D-nopper** [KhronosGroup/glTF-Blender-IO#12]

**Comment by donmccurdy** [comment]
I'm not sure I understand what this means?

**Comment by garyritchie** [comment]
Channel-packing the individual ORM images into a single file, I'm guessing. I like this idea of having the option.

**Comment by donmccurdy** [comment]
Makes sense, it sounds more like an exporter option than an importer option, though — perhaps i've misunderstood the title here.

**Comment by garyritchie** [comment]
I missed the "Importer" portion of the title. In that case _packing_ may refer to Blender's ability to store images within the blend file. Instead of writing image data out to image files (during glTF import) they would get stored to Blender image data blocks.

**Comment by McNopper** [comment]
Last one is the issue. During import, all images are packed - integrated into the blend file. In my opinion, this should be optional, as the images are already present.

**Comment by julienduroure** [comment]
I will had an option during import to enable / disable packing.
Only problem that I can see (but linked to blender way of working, user should know how it works) : If the user imports gltf file without packing, before saving the file for the first time, references to image files will be stored as absolute paths, not relative paths.
Not really an issue, because it works exactly the same when importing image by hand (and there is an operator to convert all absolute paths to relative)

**Comment by UX3D-nopper** [comment]
I am still thinking about the round trip, as the image files will - if not packing - not be touched.

**Comment by julienduroure** [comment]
Done in 4f5bcd54f92959e30e9dbb350d493d3e09a521b1
