### ISSUE TITLE
Alembic or Sequenced OBJ animation gltf export

### ISSUE THREAD

**Issue by FaradayNova** [KhronosGroup/glTF-Blender-IO#1207]
**Describe the bug**
i have done research to try to find a previous question or solution. haven't found anything coherent
I am trying to take animation data from an alembic file, and export it as GLB/GLTF

Alembic export to glb does not carry any animation data

I converted the alembic to a OBJ sequenced cache, and baked the animation data.
however each frame is an individual object with set animation and toggle of viewport and render visibility

upon research, gltf glb exporter does not like viewport toggling

I have tried web exporting the OBJ sequence to GLTF converters, but none worked
(one was promising, loaded up the animation in the preview, but locked the animation upon export)

How do I get alembic animation to export to GLTF or GLB

Please and Thank you

**Expected behavior**
alembic animation data, or OBJ sequence animation to export GLB or GLTF for Web AR applications

**.blend file/ .gltf**

[alembic+animationdata-toGLTF.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/5214032/alembic%2Banimationdata-toGLTF.zip)

**Version**
 - OS: Windows 10
 - Blender Version [2.83 + 2.90]

**Additional context**
the alembic file is generated originally from Sverchok. using blender sushi SV alembic exporting method 
(https://youtu.be/4bKR9hChgmg)

i used https://github.com/neverhood311/Stop-motion-OBJ as a method of converting the Alembic to OBJ and sequence animation data

**Comment by donmccurdy** [comment]
For some reason this file isn't working for me (maybe I need the `.abc` file as well?) but I think I roughly know what's happening. This exporter does not support this modifier, or animations that toggle visibility, which would need to be converted into another form for glTF. Perhaps that could be added, I'm not sure.

Otherwise, I think you do have two options:

1. If you can export to `.mdd` and then re-import as a shape key sequence, you can export that to glTF fine. 
2. If you can export each mesh as a separate object in the same file, it's possible to add the animation to the file (stepping through each mesh sequentially) afterward with a simple script.

See https://blenderartists.org/t/export-mesh-animation-to-gltf-usdz/1252593/2?u=donmccurdy for a bit more about both of those options.

**Comment by donmccurdy** [comment]
This may also help, I think it's a similar issue: https://discourse.threejs.org/t/quill-to-gltf-bug/18033/4?u=donmccurdy

**Comment by julienduroure** [comment]
Confirmed that we need the .abc file to see the animation in blender.
And confirmed that we don't (and not sure we even can) support animation created by a modifier.
As suggested by Don, we need to "bake" animation in a possible way that is exportable as glTF, shapekey sequence.

glTF support animation of TRS, and animation of shapekeys.
