### ISSUE TITLE
GLTF exports do not retain emission / glow - AR

### ISSUE THREAD

**Issue by nickalanf** [KhronosGroup/glTF-Blender-IO#1208]
Im having trouble exporting GLB/GLTF files from Blender 2.9 that maintain their emission or glow. 
I am modeling Neon Signs for a small business, to use on their Shopify storefront in Augmented Reality.
I learned blender specifically for its ability to export files as GLB, which is the only format Shopify accepts.

The Neon signs are looking decent in  Blender, however, when I export them, the colors are really flat and there is no glow. I know that glb files cannot act as light sources in 3D space, however, I am hoping to have the signs at least appear to glow around the tubes. 

This is a photo of the sign Im trying to model
![image](https://user-images.githubusercontent.com/26990956/93033343-bc635400-f5ea-11ea-90d5-1e442eca1daa.png)

This is the sign and shader for the red neon section
![image](https://user-images.githubusercontent.com/26990956/93033401-fa607800-f5ea-11ea-9d91-b57e60f0f436.png)

And this is the exported GLTF file in a viewer app
![image](https://user-images.githubusercontent.com/26990956/93033425-0fd5a200-f5eb-11ea-9d39-68d259aa7728.png)

Is there a way of maintaining the emission to export? I know 3D models with glow are possible, I have seen them before. Exhibit A https://www.techleer.com/articles/268-neon-an-augmented-reality-messaging-application/ 
There is a short video at the bottom of the article. 

As a self-taught 3D modeler during COVID lockdown, I'm pretty happy with how far I have got but I have reached the end of my ability/understanding with blender to play around with it.
Any advice hugely appreciated!

**Comment by donmccurdy** [comment]
Could you fill out these items from the "New Issue" template? Without them we often cannot help:

**.blend file/ .gltf**
If applicable, a zipped folder containing a .blend file for exporter issues and a .gltf file for importer issues. Please take care to include all resources, such as textures in the .zip file.

**Version**
 - OS: [e.g. macOS, linux]
 - Blender Version [e.g. 2.82, 2.83, or build date]

**Comment by donmccurdy** [comment]
Additionally — the "glow" is not entirely a property of the model itself. The viewer (Shopify's, in this case) would need to enable a so-called "bloom effect" in order to show that, even if it the model does contain emission correctly. I'm not entirely sure whether Shopify's viewer has that feature or not. We can check whether the exported model itself does contain the emission if you can share a `.blend`, but for the "bloom effect" question you may need to contact Shopify.

**Comment by nickalanf** [comment]
Apologies, new to Github aswell didnt spot there was a template

.blend file and .gltf file in the zip below

[Toadstool.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/5216030/Toadstool.zip)\

OS: Windows 10
Blender Version - 2.90.0

Please let me know if theres any other info you need.

I will contact Shopify support as well. Thankyou

**Comment by donmccurdy** [comment]
Thanks! Well the good news is, this model's emissive properties are being exported. The 20x strength multiplier isn't included (see https://github.com/KhronosGroup/glTF-Blender-IO/pull/1159) but otherwise the data is there. If you bring the `.gltf` model into Sketchfab's viewer, enable the "bloom" post-processing setting, and adjust the threshold, you'll get a bloom effect (although the backdrop mesh interferes with that a bit).

So, for better or worse, I think this boils down to whether Shopify has an option for bloom.

**Comment by nickalanf** [comment]
Ok, well thats good news atleast.

Thanks very much! Ive already got a help ticket lodged with shopify.
Will let you know how that goes incase the question comes up again in the future

Thanks again @donmccurdy

**Comment by emackey** [comment]
I do wonder if glTF needs an extension to control/suggest bloom settings on the renderer.  Not sure what the behavior would be if you loaded more than one glTF with conflicting settings though.

/cc @pushmatrix

**Comment by donmccurdy** [comment]
I'd prefer not; putting renderer settings in a single model would make it very difficult to correctly compose a scene containing multiple models as you say. I think post-processing (e.g. bloom) should remain a matter of configuring the viewer, not configuring the content.

**Comment by emackey** [comment]
@donmccurdy I mostly agree, but just to offer the counterpoint, glTF is capable of holding whole scenes.  A bloom effect would presumably be a scene-level extension, if it existed, not a material extension.  But you're right, such things make it tricky to compose multiple glTFs into the same scene in a reasonable way.

**Comment by lexaknyazev** [comment]
> A bloom effect would presumably be a scene-level extension

Its strength could be a per-object value for artistic purposes.

**Comment by donmccurdy** [comment]
I don't think renderers will support per-object bloom. This is a post-processing effect performed on a rendered image. A path tracer wouldn't use bloom; the setting is for rasterizers to fake real emission with a screenspace effect. Similarly, a realtime engine supporting GI might have better options than bloom.

The suggestion of including units on emission (from the other thread) is a good one. That might (more investigation needed?) even allow rasterizers to infer the appropriate amount of bloom for a given camera position.

**Comment by emackey** [comment]
> A path tracer wouldn't use bloom; the setting is for rasterizers to fake real emission with a screenspace effect.

No, I have to disagree with this.  Bloom is a real thing that happens in the camera, and on the human retina as well, where pixels or cells that have been overwhelmed with light can have their neighbor pixels/cells respond as well.

For example, consider this photograph of [ULA launching the Mars 2020 rover](https://www.nasa.gov/press-release/nasa-ula-launch-mars-2020-perseverance-rover-mission-to-red-planet):

![ULA_Mars_2020](https://user-images.githubusercontent.com/1235080/93142846-cc476a80-f6b4-11ea-8560-1e0c5ea3f081.jpg)

The air around the vehicle is all lit up with a yellowish glow, very distinct from the color of the sky.  The engine exhaust is bright enough to produce a lot of bloom.

Here's a little experiment here, please pardon my horrible hack job with the lasso tool.  Which rocket has brighter exhaust?

![ULA_Mars_Bloom_vs_not](https://user-images.githubusercontent.com/1235080/93143743-87bcce80-f6b6-11ea-8d0e-3588ac6bc052.jpg)

Take a look with your eyes first.  Is one exhaust plume brighter than the other?  Now try it with a paint program, which one has higher RGB values?

Spoiler alert, they're the same RGB values inside the exhaust trail.  It's only the surrounding glow that's different.  And yet instinctively, I still shield my eyes from the one on the left, as if it were somehow brighter than the white web page background.  The one on the right is an exact copy-paste of the one on the left, just with the bloom excluded by the poorly-drawn lasso-selection.  It looks flat and dim only because of the lack of bloom around it, not because of any difference in its actual RGB values.

In Blender Cycles, bloom is done using a "Glare" node in the compositor tab, after rendering a frame.  In Eevee, there's a render setting to turn on bloom.

**Comment by donmccurdy** [comment]
Fully agreed, and it's a great illustration, thanks! 🚀 

To be more specific — when users of a realtime viewer enable bloom, it's often because their emissive materials do not appear to emit light without it. The rasterizer cannot create real emissive glow, but bloom gives a visual result that "feels" similar, even if the physical behavior is quite different. You could include a "Glare" node in Cycles, too, but it's less common when the emission is obvious without it.

**Comment by donmccurdy** [comment]
Sounds like there's no change needed on the Blender exporter, so I'll close this issue.

I do have reservations about the idea of post-processing as an extension (tl;dr it expands scope vertically, and I'd rather focus horizontally) but in any case proposals on the main glTF repository are always welcome.
