### ISSUE TITLE
T81095: GLTF export crashes after decimation is applied to the model second time

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#1222]
See https://developer.blender.org/T81095

**Comment by scurest** [comment]
Oh, I know about that. It's because if you do calc_loop_triangles, then apply a modifier, then do calc_loop_triangles again, Blender doesn't recompute the triangles. Same think happens with the .x3d addon when using "Triangulate".

I think this should be fixed in Blender. In the meantime, toggling in and out of edit mode after applying a modifier will fix it.

Repro instructions

1. Create a Suzanne
2. In the python console, do `D.meshes['Suzanne'].calc_loop_triangles()`
3. Check the number of tris: `len(D.meshes['Suzanne'].loop_triangles)` => 968
4. Add and apply some modifier (say decimate, unsubdivide, iterations=2)
5. Do `D.meshes['Suzanne'].calc_loop_triangles()`
6. Check that the number of tris didn't change: `len(D.meshes['Suzanne'].loop_triangles)` => 968

**Comment by julienduroure** [comment]
Ok, I created this bug report : 

https://developer.blender.org/T81136

**Comment by julienduroure** [comment]
The original bug is now fixed.
To be tested with tomorrow's build

**Comment by julienduroure** [comment]
Confirmed that this is fixed on Blender side.
Here is the commit: https://developer.blender.org/rB60c3ef3d61836a5b05ef7796544c256fb5e15c74
