### ISSUE TITLE
T83131: gltf exporter exports incorrect transforms when exporting nodes that have a rotation or scale other than the identity

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#1280]
See https://developer.blender.org/T83131
and a proposed PR: https://developer.blender.org/D9660

**Comment by julienduroure** [comment]
I can't reproduce

![image](https://user-images.githubusercontent.com/1696020/101273990-ac4ab300-379a-11eb-8d88-ca8a8fd29ef6.png)
[monkeys.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/5648416/monkeys.zip)

I asked some more info on d.b.o

**Comment by blackears** [comment]
I was using the version of the plugin that was checking into the blender main branch around Nov 27 2020.  (Version 1.5.2 of the glTF plugin)  This bug is specific to exporting linked objects that are part of a collection.  Basically the person who wrote the code that grabs the offset of the collection simply added that offset to the translation instead of applying to rotation and scale matrices to it too.

**Comment by blackears** [comment]
Just looked at the source code in the latest version of the plugin (1.5.8).  The bug appears to still be there.  (didn't realize the version of the plugin shipping with blender was several revisions behind).

**Comment by blackears** [comment]
I forgot to add in the initial report - in the first file with the money, you need to set the origin of the collection to something other than the world origin.  
[myMonkeys.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/5649194/myMonkeys.zip)

**Comment by julienduroure** [comment]
Ok, with this missing step, I can reproduce

**Comment by julienduroure** [comment]
@blackears Can you please open a PR instead of developer.blender.org?
Thanks!

**Comment by blackears** [comment]
I've posted this:
https://github.com/KhronosGroup/glTF-Blender-IO/pull/1288

**Comment by julienduroure** [comment]
This I forgot to close this ticket after merge.
Closing
