### ISSUE TITLE
T83426: Blender GLTF Exporter - Missing texture filtering

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#1285]
See https://developer.blender.org/T83426

Broken: version: 2.91.0
Worked: 2.90.1

**Comment by scurest** [comment]
https://github.com/KhronosGroup/glTF-Blender-IO/blob/5c0bc25d44d13eaf3e901e801c9a1642ada80423/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_sampler.py#L79

This is probably supposed to be LinearMipmapNearest (do linear filtering with the nearest mipmap), not NearestMipmapLinear (do nearest filtering with the two closest mipmaps, then average them).

It could also be LinearMipmapLinear.

**Comment by f3lix-s** [comment]
Changed line 79 as suggested by scurest and it's better now. But something is still missing/wrong please see attatched picture. "2.92.0_mod" is exportet from Blender with line 79 changed to "LinearMipmapNearest".

![blender_compare](https://user-images.githubusercontent.com/75536166/101247680-263b5780-371b-11eb-9c10-995a705617d4.jpg)

**Comment by scurest** [comment]
Try LinearMipmapLinear.

**Comment by f3lix-s** [comment]
"79    return TextureFilter.LinearMipmapLinear" did the job :)

**Comment by scurest** [comment]
To explain what happens: Linear has been (incorrectly) exported as NearestMipmapLinear since at least 2.81, but before 2.91 the sampler would be omitted for textures that are Linear/Repeat in Blender. When the sampler is omitted, the viewer picks the filtering on its own. This was changed to fix #307 (texture was Linear in Blender, but sampler was omitted, and a viewer could pick nearest filter); the sampler is now never omitted. That means the viewer is no longer picking the filter to use itself, it's using the one specified in the .gltf file.

**Comment by scurest** [comment]
@f3lix-s Ah, thanks.

**Comment by scurest** [comment]
Here is what it looks like in Blender

![cube](https://user-images.githubusercontent.com/11024420/101251513-82828500-36e3-11eb-8a35-d187d75b0dd0.png)

So yeah, LinearMipmapLinear looks like it's closest, let's do that.

**Comment by f3lix-s** [comment]
Thank you for your solution and explanations! I am quite new in coding and new in Blender as well. 
Coming from Cinema 4D with the aim for three.js ...

And this was my first reported bug ever, what an exiting day ;)

**Comment by scurest** [comment]
@f3lix-s Nice work finding this :)

I opened #1286.
