### ISSUE TITLE
Importing fails with Python 3.9

### ISSUE THREAD

**Issue by here-abarany** [KhronosGroup/glTF-Blender-IO#1295]
**Describe the bug**
Python 3.9 removed the "encoding" parameter for json.loads(), leading to an unexpected keyword argument exception being thrown when attempting to load a glTF file.

**To Reproduce**
1. Launch Blender with a system using Python 3.9.
2. Import a glTF or glb file.

**Expected behavior**
File imports without error.

**Screenshots**
![Screenshot_20201215_142414](https://user-images.githubusercontent.com/16659193/102280057-4ddfac00-3ee1-11eb-8076-e1409ddf785c.png)

**Version**
 - OS: Arch Linux
 - Blender Version 2.91

**Additional context**
Removing the encoding parameter in gltf_io_gltf.py line 64 fixes the issue.

**Comment by julienduroure** [comment]
Hello,
Blender is bundled with its own python interpreter, that is the only python version that is officially supported.
For 2.91, this is 3.7.7

**Comment by scurest** [comment]
From the [3.7 docs](https://docs.python.org/3.7/library/json.html#json.loads)

> The other arguments have the same meaning as in load(), except _encoding_ which is **ignored and deprecated**.

encoding has been ignored since 3.1, so it should be deleted even in 3.7.

I only put the `encoding=` arg in in #1238 because I thought incorrectly that `json.loads(str(json_bytes, encoding='utf-8'))` was the same as `json.loads(json_bytes, encoding='utf-8')`.

**Comment by makitsune** [comment]
I'm having this issue as well using Arch Linux with Python 3.9.1. I had to manually remove all `encoding='utf8'` in the plugin to get it to work for now.
