### ISSUE TITLE
Importer: Disable all non-glTF parameters in Principled BSDF node

### ISSUE THREAD

**Issue by UX3D-nopper** [KhronosGroup/glTF-Blender-IO#13]
Set clear coat and other parameters that they do not have any effect.

**Comment by donmccurdy** [comment]
Does the Blender API let you disable pieces of a Principled BSDF node? I'm not sure this should be the responsibility of the importer, because we cannot assume the user is planning to export back out as glTF.

Is it possible to display warnings to the user on export, without exiting the export process?

**Comment by McNopper** [comment]
Maybe disable is the wrong word. More like setting values, that the effect is not visible. If you import a glTF file, you assume a specific material.

**Comment by oparisy** [comment]
Displaying warnings is interesting in that it helps in teaching users what is expected by the exporter.
