### ISSUE TITLE
Images are converted to PNG

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Blender-IO#130]
From glTF-Blender-Exporter, I think were we ended up was trying to use the input format wherever possible, and if the file exists on disk, try to copy it rather than re-saving (which will apply various unwanted scene preferences...).

See: https://github.com/KhronosGroup/glTF-Blender-Exporter/pull/221 and https://github.com/KhronosGroup/glTF-Blender-Exporter/pull/220.

I'm testing with this 600KB JPG, which on export becomes a 4MB PNG:

![awan biru](https://user-images.githubusercontent.com/1848368/49358184-a0e1c000-f686-11e8-8220-ff9c49f1206f.jpg)

(from https://www.blendswap.com/blends/view/80706)

**Comment by viperscape** [comment]
I just wanted to note that when converted, the naming scheme in the gltf file is then not the same for uri and name:
```json
            "mimeType" : "image/png",
            "name" : "rock-mat_diffuseOriginal.bmp", // original file used
            "uri" : "rock-mat_diffuseOriginal.png" // recreated png from exporter
```

**Comment by emackey** [comment]
@viperscape I think that's fine, `name` is just an arbitrary name and can match the original source material.  It doesn't need to match files shipped with the glTF.  Also, BMP format is not allowed by glTF, so it needs to be converted to either JPG or PNG.

But the up-conversion from smaller JPGs to larger PNGs is an un-wanted regression.  @donmccurdy had this fixed in the previous converter, and it would be good to see that fix preserved or re-created here.

**Comment by emackey** [comment]
Thanks @UX3D-schmithuesen.  I didn't try this yet, but does your fix still convert BMPs and other disallowed formats to PNG?  Looking briefly at the code it reads as if it will preserve any original format.

**Comment by donmccurdy** [comment]
Thanks! :)
