### ISSUE TITLE
Very big file size when exportiong with animations to gltf

### ISSUE THREAD

**Issue by timurshel** [KhronosGroup/glTF-Blender-IO#1322]
I imported Flamingo.glb (76 kb) from three js examples and then  immediately I exported it to f.glb and got 610 kb size.
When I remove flags from exporting animation , I got 68 kb. When I put some more animations - size became 5 Mb.

Is threre a way to make low recource models with animations using blender?
version 2.91.0
[Flamingo.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/5904750/Flamingo.zip)

**Comment by julienduroure** [comment]
* Be sure to restrict your scene range to avoid exporting 
* Initial flamingo don't have any NORMALS data. You can avoid exporting normals data by unchecking "Normals" in geometry export options

**Comment by donmccurdy** [comment]
@timurshel a bit of additional information that may be helpful — there are various tools available to optimize and compress glTF files, like glTF-Pipeline (for geometry), gltfpack, glTF-Transform, RapidCompact, and Gestaltor. Many of those optimizations are lossy, and involve simplifying the data in some way. Blender tries to export very nearly what the original scene contains, losslessly, and — because we don't know anything at export time about the original `.glb` source — this can increase a file's size. 

Comparing the meshes in these files...

**Before:**

| # | name | mode      | primitives | glPrimitives | vertices | indexed | components      | attributes                    | instances | size  |
| - | ---- | --------- | ---------- | ------------ | -------- | ------- | --------------- | ----------------------------- | --------- | ----- |
| 0 |      | TRIANGLES | 1          | 542          | 337      | ✓       | Float32, Uint16 | COLOR_0, POSITION, TEXCOORD_0 | 1         | 69 KB |

**After:**

| # | name   | mode      | primitives | glPrimitives | vertices | indexed | components      | attributes                            | instances | size      |
| - | ------ | --------- | ---------- | ------------ | -------- | ------- | --------------- | ------------------------------------- | --------- | --------- |
| 0 | Mesh_0 | TRIANGLES | 1          | 542          | 1,626    | ✓       | Float32, Uint16 | COLOR_0, NORMAL, POSITION, TEXCOORD_0 | 1         | 600.22 KB |

... you can see that a "NORMALS" attribute has been added, and the number of vertices has increased. The increase in vertices is directly caused by exporting normals, so unchecking that option in your export settings will bring the file back down to its original size, as @julienduroure mentions. I created these tables using `gltf-transform inspect Flamingo.glb`.

Some of the optimization tools mentioned above may be able to detect and optimize such issues automatically.

**Comment by scurest** [comment]
It would be possible for the exporter to check if all polys are flat and omit normals automatically btw.

**Comment by donmccurdy** [comment]
I'm not sure if we should change that – not all engines are so consistent about generating flat normals and it may come at a performance cost...

**Comment by timurshel** [comment]
Thank you very much. After clearing "export normals" my model became even 4 kb lesser: 72 kb with animation.
Also thanks for information about optiomization gltf.
