### ISSUE TITLE
`Limit to Playback Range` option does not work

### ISSUE THREAD

**Issue by marcofugaro** [KhronosGroup/glTF-Blender-IO#1379]
**Describe the bug**

The `Limit to Playback Range` does not seem to work.

I have a simple animation of blender, of which I have selected only a small portion to export:

https://user-images.githubusercontent.com/7217420/115210383-d031e400-a0fe-11eb-9972-b11d6795c201.mov

When exporting, I have selected the `Limit to Playback Range`, which according to the docs: **"Clips animations to selected playback range."**

<img width="244" alt="Screenshot 2021-04-19 at 10 46 06" src="https://user-images.githubusercontent.com/7217420/115210662-1c7d2400-a0ff-11eb-9315-35acc30838cd.png">

However, when I use the exported gltf, here in [gltf-viewer](https://gltf-viewer.donmccurdy.com/), the whole animation plays. This is confusing.

https://user-images.githubusercontent.com/7217420/115211077-81d11500-a0ff-11eb-9358-328f0ae9e4a5.mov

**To Reproduce** 
1. Download `test-playback.zip` below
2. Open `test-playback.blend`
3. Export to gltf using the `Limit to Playback Range` option
4. Open the gltf in https://gltf-viewer.donmccurdy.com/ for example
5. The complete animation plays

**Expected behavior**
Only the animation from frames 30 to 40 should be exported.

**.blend file/ .gltf**
[test-playback.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/6334607/test-playback.zip)

**Version**
 - OS: macOS
 - Blender Version: 2.93.0 Alpha 2021-04-10

**Comment by marcofugaro** [comment]
This may be related to #387 as well

**Comment by gigablox** [comment]
Ran into this recently as well. This seems like a pretty serious bug - if we can't export a frame range on an NLA track that breaks a lot of animation loop cycles like walking and running. These animations often depend on being able to cut the last frame off a NLA track because the curve leading into the first and last keyframe match which enable a seamless loop.

**Comment by schroef** [comment]
The limit playback range is only the end frame, i guess, thats also how its named in Blender itself. I think you would need to use current_frame otherwise it will always export from frame 0, which is weird since blender starts at frame 1

in the py "gltf2_blender_export.py" #37  i see this statement.
```
if not export_settings['gltf_current_frame']:
        bpy.context.scene.frame_set(0)
```

I think this addon will be better off with a visible start and end frame input like some other exporters have

**Comment by hybridherbst** [comment]
Also running into this issue. 
@julienduroure any plans to fix this? It's a pretty commonly used technique to build looping animations.

**Comment by julienduroure** [comment]
Hello,
This is now fixed in current main branch, after animation refactor 64e3532f48ebdf878a1c9b81ade6d1a19c8ff890
