### ISSUE TITLE
PointLight exported as Object3D

### ISSUE THREAD

**Issue by castelblends** [KhronosGroup/glTF-Blender-IO#1385]
**Describe the bug**
Point lights created in  Blender get exported as Object3D type instead of PointLight thus preventing from changing intensity or power.

**To Reproduce**
1. Add a point light in blender. Name it L1.
2. export to file to GLB. Include "Punctual Lights".
3. Load the model with glff loader in three js.
4. console log L1 right after [scene.add(gltf.scene)].
5. check object type.

**Expected behavior**
Expected to have a light with type "PointLight" and properties of a PointLight object like decay, distance, intensity, power and so on.

**Screenshots**
![Screenshot from 2021-04-29 11-05-32](https://user-images.githubusercontent.com/61828683/116573581-eef06180-a8da-11eb-8913-d073f320ea39.png)
This screenshot shows a   THREE.PointLight object created manually called "LL" and a Blender point light called "L1". Notice the difference in types.

**.blend file/ .gltf**

**Version**
 - OS: Ubuntu 20.04.2 LTS
 - Blender Version 2.92.0
 - ThreeJS r128

**Additional context**

**Comment by donmccurdy** [comment]
Exporting the default Blender scene with **Include** -> **Punctual Lights** enabled in the export options, you'll get a structure like this in three.js:

![Screen Shot 2021-04-29 at 9 09 00 AM](https://user-images.githubusercontent.com/1848368/116582871-9fa23500-a8ca-11eb-888b-0eb81f81ef20.png)

Note that the object "Light" is an empty node (or Object3D in three.js terms), but that it has a point light as its only child. The additional wrapping node is there to correct for orientation differences between Blender's conventions and glTF's, although admittedly that's a bit pointless in this specific case, since a point light has no meaningful orientation. See https://github.com/KhronosGroup/glTF-Blender-IO/issues/1328.

**Comment by castelblends** [comment]
Oh! I see. Didn't occurred to me to look for children in an imported light. 

So the workaround to implement in my workflow will be to add "_Orientation" to all light names created in Blender.

Thank you.
