### ISSUE TITLE
My character's limbs seem to be tearing my character's clothes ?

### ISSUE THREAD

**Issue by mrParabol** [KhronosGroup/glTF-Blender-IO#1390]
My character's feet are visible through the shoe of my character that I exported from the blender to the godot.
os: manjaro
blender : 2.92

blender image:
![2-my-boots](https://user-images.githubusercontent.com/28789841/116942435-3f204880-ac7a-11eb-877d-91a7e15187bb.png)

godot image:
![1-my-boots](https://user-images.githubusercontent.com/28789841/116942453-4ba4a100-ac7a-11eb-851b-e91afdc52421.png)

My blender, godot files and the files I exported as glb are also on the link.
https://disk.yandex.com.tr/d/sVIzHRJXbbFGkQ

Thank you very much for your attention.

**Comment by mrParabol** [comment]
I have tried all of the links below but I am having the same problem.

Godot
https://gltf-viewer.donmccurdy.com/
https://sandbox.babylonjs.com/
https://github.khronos.org/glTF-Sample-Viewer-Release/

**Comment by donmccurdy** [comment]
This model is using a [Mask Modifier](https://docs.blender.org/manual/en/latest/modeling/modifiers/generate/mask.html) to hide the legs below the shoes. Most modifiers cannot be exported from Blender to other software, so you have two choices here:

1. Re-model the boots so that they fully cover the character's legs.
2. Enable "Geometry -> Apply Modifiers" during export to bake that modifier, completely removing the vertices that the modifier currently hides.

**Comment by mrParabol** [comment]
@donmccurdy  First of all, thank you very much for your help.I solved my problem as follows.I combined the pieces thanks to the makehuman addons.
![dancegirl](https://user-images.githubusercontent.com/28789841/117211742-1034de80-ae02-11eb-93b1-f8d522323270.png)
