### ISSUE TITLE
Problems with skinned armatures in 2.90 and up

### ISSUE THREAD

**Issue by Quest-Homes** [KhronosGroup/glTF-Blender-IO#1405]
I’m still using 2.83 because it’s the last version gltf export is working correctly.

For context I’m building environments for the oculus quest. The viewer is using gltf separate.
But since 2.90 every environment that has mesh skinned to a armature the environments will crash.

The only workaround is to copy the gltf addon from 2.83 into newer blender versions.
Since 2.93 is released I would like to switch completely without the need to copy the old gltf export addon every time to the new version.

Does someone know what changed, that armatures are breaking gltf exports?

**Comment by julienduroure** [comment]
Hello,
As requested in bug template, can you please provide a test file .blend that seems to work on 2.83 and not on 2.90 ?
Lots of stuff changed since 2.83, and as far as I remember, skinning was changed after 2.83, because it was wrong in most cases (I mean was not respect the glTF specification)

(Another question : what is your glTF reader you are using to read files coming from Blender ?)

**Comment by scurest** [comment]
#1284 involved skinning in oculus quest, might be related.

**Comment by julienduroure** [comment]
Hello,
No news on this ticket. Test file is not provided, and it may be a problem with Oculus.
Closing this ticket.
Don't hesitate to open a new ticket with all needed information if you still have any issue.
