### ISSUE TITLE
Feature Request: Triangulate Mesh Checkbox

### ISSUE THREAD

**Issue by DynasoulStudio** [KhronosGroup/glTF-Blender-IO#145]
It would speed up exporting if I didn't have to add a triangulate modifier to each individual piece of a model, instead a checkbox that automatically adds the triangulate modifer and then applies it to each model would be awesome! Blender supports n-gons but the gltf format appreciate tri faces the most.

**Comment by donmccurdy** [comment]
Hi @DynasoulStudio — Meshes are triangulated automatically when they're exported, because the glTF format disallows n-gons. If you export a basic cube, open it on https://gltf-viewer.donmccurdy.com/, then enable 'wireframe' in the settings you'll see the triangles.

Have you run into a case where pieces of the model aren't exported correctly without a triangulate modifier? It may be that text or other objects require some conversion to a mesh..

**Comment by DynasoulStudio** [comment]
The Tangent export feature seems to complain about the mesh not being triangulated, perhaps it could be calculated after triangulation?

**Comment by donmccurdy** [comment]
Merging with https://github.com/KhronosGroup/glTF-Blender-IO/issues/172
