### ISSUE TITLE
Manage KHR_materials_volume

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#1454]
Currently, KHR_materials_transmission is managed but not KHR_materials_volume nor KHR_materials_ior.

I'am not very familiar with these extensions, so let's discuss about it and how to implement it:

Without any order:
- How to differentiate KHR_materials_transmission with and without KHR_materials_volume?
- How to manage all parameters of KHR_materials_volume that are not in principled shader?

**Comment by donmccurdy** [comment]
> I'm not sure what (if anything) to do with attenuationColor and attenuationDistance at this stage.

See comments in https://github.com/KhronosGroup/glTF/pull/1726#issuecomment-683820025, we can use the Principled Volume node in complement to the Principled BSDF, although I'm still not sure exactly which sockets to use. Note that SSS is a separate, upcoming, glTF extension.

<img width="563" alt="Screen Shot 2021-08-23 at 8 43 54 PM" src="https://user-images.githubusercontent.com/1848368/130552683-4e223dd3-2a73-45f9-83b3-a55b59dac20d.png">

**Comment by emackey** [comment]
Lately I've been doing some experimenting with Blender and `KHR_materials_volume`.  Here's my adaptation of the [AttenuationTest Sample Model](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AttenuationTest):

![screenshot of attenuation test](https://user-images.githubusercontent.com/1235080/134988036-b6678f4f-d822-4c84-9099-f92c529ecac8.png)

Some notes:

- The `KHR_materials_transmission` extension is here, and must be reflected in the `Transmission` input of the Principled BSDF Node on the left, above.  The (outdated) version I tested has export but not import support for Transmission, so I added this manually here.

- The use of transmission (as opposed to translucency) is intended to hint that any volumetric effects will be primarily absorption/attenuation, not sub-surface scattering.  At some later date, glTF may introduce a "translucency" extension that might become a gateway into SSS.

- The `KHR_materials_volume` extension, when paired with Transmission, can be fully represented here by the "Volume Absorption" node, not the full Principled Volume node.

- `KHR_materials_volume` has a property `attenuationColor` (in linear space, like all glTF color factors).  I believe this color can be copied to the "Volume Absorption" node directly as shown here.  glTF does not allow a texturemap for this property, as it is volumetric in nature.

- `KHR_materials_volume` has a property `attenuationDistance` which appears to be the inverse of the `density` shown on this node by Blender.  Specifically, `density = 1.0 / attenuationDistance` while importing.  This is because glTF specifies the volume as reaching the color when the attenuationDistance is reached, but Blender is calculating the other way, reaching the color some number of times per meter as specified by `density`.  No texturemaps are allowed in glTF on this input either, as it also describes a material's volumetric property.

- `KHR_materials_volume` has a "thickness" value in both factor & texture forms.  This is intended to help realtime implementations imitate pathtracing to some extent, by hinting at the thickness of the mesh (in raw mesh coordinate units).  Blender can bake a thickness map (I've had only mixed success) using the "Ambient Occlusion" node with "Inside" checked, firing rays into the mesh interior.  But for glTF import/export, this may need to be another dead input on the glTF Settings node, like Occlusion.  If the value is unknown, it's important to at least put `1.0` as the `thicknessFactor`, otherwise the volumetric effects are disabled.

- If the importer reads `KHR_materials_volume` but `thicknessFactor` is zero or unspecified, it should ignore the extension and not place any volume node on the graph.

- It might be wise to connect `KHR_materials_ior` to the IOR input of the Principled node.  But beware, glTF's default IOR is 1.5, and Blender's default is 1.45.  I don't think we want a situation where the exporter always writes KHR_materials_ior for every material by default, so perhaps it should only write it when the Volume Absorption node is present.

**Comment by emackey** [comment]
One more note: Sadly, Eevee seems geared towards smoke as the realtime volumetric effect.  Only Cycles can produce a sane image as shown above.  Still I think it is well worth supporting these parameters.

**Comment by emackey** [comment]
And for the exporter:  `attenuationDistance = (density > 0.0) ? (1.0 / density) : None`.

The importer should not have to worry about `attenuationDistance` being zero, that's illegal in glTF.

**Comment by stmaccarelli** [comment]
Hi guys.
exporting KHR_materials_transmission without setting KHR_materials_volume properties is quite unuseful.
A refracrive material that has zero thickness, is not refracting anything.

I wrote a "user extension" of Khronos glTF-Blender-IO exporter (following this example: https://github.com/KhronosGroup/glTF-Blender-IO/tree/master/example-addons/example_gltf_extension) that simply uses Blender's "refraction depth" property and exports that as thicknessFactor.
Note that hte size unit in Blender is m(etres), I don't know what the unit of the thicknessFactor is in glTF, but to me it looks like m(etres) is acceptable, according to the objects in the scene.

this version of the addon doesn't export attenuationDistance, attenuationColor or thicknessMap, but I'm working on it. 

Here's a GIST: https://gist.github.com/stmaccarelli/840bbc5f04c097a884787063e710db08

**Comment by stmaccarelli** [comment]
updated the GIST with KHR_materials_ior.
exports IOR (index of refraction) from Blender Principled BSDF node.
Most of the times we'll use the standard 1.45 index (water) but now if you want, you can simulate different materials (sapphire, water, glycerin, glass, etc)

**Comment by donmccurdy** [comment]
>  exporting KHR_materials_transmission without setting KHR_materials_volume properties is quite unuseful.

There's a range of uses for transmissive materials that don't require refraction: thin-walled glass that is fully transmissive but still reflective (unlike alpha blending), or rough transmissive materials like frosted glass. Certainly we'd like to support `KHR_materials_volume` as well, but that should be omitted at export if refraction is disabled.

> I don't know what the unit of the thicknessFactor is in glTF

Meters, and affected by the scale of the mesh.

@stmaccarelli would you be willing to open a PR to add your changes here, similar to https://github.com/KhronosGroup/glTF-Blender-IO/pull/1094? I don't think it's necessary for all parameters to be supported initially, especially if some are harder to map from Blender's materials.

**Comment by stmaccarelli** [comment]
Hello @donmccurdy ,

> There's a range of uses for transmissive materials that don't require refraction: thin-walled glass that is fully transmissive but still reflective
Yes, but it is quite uncommon in real life. The only stuff I can think about, with such features, is glass xmas balls, or soap balls.

> or rough transmissive materials like frosted glass
This can take advantage from KHR_materials_volume params too, because a frosted glass ball refracts and distorts light too.

> Certainly we'd like to support KHR_materials_volume as well, but that should be omitted at export if refraction is disabled.
Do you mean Blender  screen space refraction setting in the renderer tab? Or refraction as material property?
I think it can be done in either case. Right now my raw plugin has a checkbox, but a better Blender addons coder can do a better job 


>>     I don't know what the unit of the thicknessFactor is in glTF
> 
> Meters, and affected by the scale of the mesh.

So it should be the same as Blender


> would you be willing to open a PR to add your changes here, similar to #1094? I don't think it's necessary for all parameters to be supported initially, especially if some are harder to map from Blender's materials.
Yes, I'd gladly do it. I have a "final" version of my addon, I was working on thickness map, but it's quite difficult to me because blender doesn't natively supports it in its Principled BSDF or Glass Material

**Comment by emackey** [comment]
> > There's a range of uses for transmissive materials that don't require refraction: thin-walled glass that is fully transmissive but still reflective
> 
> Yes, but it is quite uncommon in real life. The only stuff I can think about, with such features, is glass xmas balls, or soap balls.

It's much more common in lower-poly models, for example of house windows or car windows.  Basically any situation where the model can only afford a single layer of polys to represent a pane of glass, can avoid using the full KHR_materials_volume extension, and avoid its associated costs.

Even so I'm eager to see a proper implementation of KHR_materials_volume in Blender, as obviously refraction can make a whole scene look a lot more sophisticated.

**Comment by donmccurdy** [comment]
> but it's quite difficult to me because blender doesn't natively supports it in its Principled BSDF or Glass Material...

For baked Occlusion we've resorted to detecting an "Occlusion" slot on a custom "glTF Settings" node. Seems very reasonable to do the same thing with a "Thickness" slot here I think, unless/until Blender adds its own equivalent.

**Comment by stmaccarelli** [comment]
> It's much more common in lower-poly models, for example of house windows or car windows. Basically any situation where the model can only afford a single layer of polys to represent a pane of glass, can avoid using the full KHR_materials_volume extension, and avoid its associated costs.

Yes, but in that case you won't need transmission at all... reflections is all you need, and you can achieve that with clearcoat, by just reflecting the environmental map.
declaring a model has KHR_materials_transmission is computationally expensive the same way if the volume thickness 1 meter, 10 meters or 0.001 meters, the renderer has to do the same operations, only on different numbers.

KHR_materials_volume applies to the same single layer of polys. You can even apply to a single quad, and tell the renderer, using KHR_materials_volume, that has to simulate light refraction as that quad would be a 0,5meters thick glass.
plus, using IOR, you can even tell the renderer what material is that panel! it may refract like water, diamond, ice, etc...

**Comment by stmaccarelli** [comment]
> For baked Occlusion we've resorted to detecting an "Occlusion" slot on a custom "glTF Settings" node. Seems very reasonable to do the same thing with a "Thickness" slot here I think, unless/until Blender adds its own equivalent.

I identified a slot that can be used as thickness, but that slot only accepts numbers, not textures.
RIght now I featured all the properties of KHR_material_transmission, KHR_materials_volume and KHR_materials_ior just using Blender native slots.
The only one I'm missing is a thickness map (texture)

I was thinking about using Blender's Principled BSDF MAterial's Subsurface Color node, because it supports textures too, but it's actually for a different purpose.

Let's also say that a Blender plugin has the ability to add items to Blender panels, so a "Khronos glTF extrensions" panel could be added with such extra stuff. But I don't know if I'd be able to code that in a reasonable amount of time, maybe someone more expert would be helpful.

**Comment by stmaccarelli** [comment]
anyways, I'll soonest cleanup my last plugin edits, and I'll post a new GIST code + demo screencast, and we'll discuss about everything. I?ll try to find some time tomorrow morning.

**Comment by donmccurdy** [comment]
> Let's also say that a Blender plugin has the ability to add items to Blender panels, so a "Khronos glTF extrensions" panel could be added with such extra stuff.

Since this plugin is enabled in Blender by default, I don't think we can/should add new UI panels unfortunately. Using a "Thickness" socket on a custom "glTF Settings" node has been our workaround for that, and since it's already required for Occlusion maps I think it would make sense for a Thickness map.

Support for subsurface in glTF is on the roadmap, so we probably don't want to misappropriate that slot. :)

**Comment by emackey** [comment]
> Yes, but in that case you won't need transmission at all...

Actually, I meant like this:  https://sketchfab.com/3d-models/pony-cartoon-885d9f60b3a9429bb4077cfac5653cf9

And this: https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/ToyCar

> KHR_materials_volume applies to the same single layer of polys

No, in the [Extending Materials](https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_materials_volume#extending-materials) section, there's a note that says "A non-zero thickness switches from thin-walled to volumetric behavior. This requires a manifold/closed mesh."  Later, in the properties section, it says "The doubleSided property has no effect on volume boundaries".  So, this is intended for a single-sided mesh of polygons surrounding an enclosed volume of material.  Behavior of a single layer of double-sided polygons will be unpredictable, especially in a path tracer where the volume boundary is only crossed once.

+1 for Don's comments on the Thickness map.

**Comment by stmaccarelli** [comment]
ok, let's wrap it up.
My English is not so good, so I'll most probably have some difficulties explaining my concepts, but let's try and forgive me.

about the comment by @emackey 
**KHR_materials_transmission** itself, without volume declarations, is enough to define clear glass-like surfaces with virtually zero thickness, like your examples show.
But, in real life, nothing is zero thickness. A car glass is about 3 to 5 mm, and refracts / distorts light, other that letting it pass through. Adding **KHR_materials_volume** addresses this, and makes everything more realistic.

Look at this model: https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/IridescentDishWithOlives
Thick glass objects? glass statues? refractive realistic glass windows? Ice sculptures? Eye bulbs? Diamonds? With the actual Khronos Blender glTF2.0 exporter, this is simply impossible, and you have to use additional tools, like the one made by @donmccurdy , to add materials extensions to exported models.

And about the "manifold" in the documentation, I think it's not mandatory for calculating refraction or simple transmission: Babylon, Three, Blender's Eevee and Cycles, can render transmission and volume data on non-manifold meshes, although js renderers cannot combine multiple layers of transmissive objects, but that's not our business)

Actually declaring that mesh X, made even by a single quad, has a volume thickness of 0.5, tells the renderer:
when lights passes through this mesh, distort it like it was a glass mass of 0.5meters.
And they do the job quite well:
https://threejs.org/examples/?q=trans#webgl_loader_gltf_transmission
the different thicknesses you see along the glass cup, are addressed with a thickness texture, not by actually ray-tracing (that would be computationally overkill), so I don't understand why we would need a manifold mesh.

**Comment by stmaccarelli** [comment]
ok, let's wrap it up.
My English is not so good, so I'll most probably have some difficulties explaining my concepts, but let's try and forgive me.

about the comment by @emackey 
**KHR_materials_transmission** itself, without volume declarations, is enough to define clear glass-like surfaces with virtually zero thickness, like your examples show.
But, in real life, nothing is zero thickness. A car glass is about 3 to 5 mm, and refracts / distorts light, other that letting it pass through. Adding **KHR_materials_volume** addresses this, and makes everything more realistic.

Look at this model: https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/IridescentDishWithOlives
Thick glass objects? glass statues? refractive realistic glass windows? Ice sculptures? Eye bulbs? Diamonds? With the actual Khronos Blender glTF2.0 exporter, this is simply impossible, and you have to use additional tools, like the one made by @donmccurdy , to add materials extensions to exported models.

And about the "manifold" in the documentation, I think it's not mandatory for calculating refraction or simple transmission: Babylon, Three, Blender's Eevee and Cycles, can render transmission and volume data on non-manifold meshes, although js renderers cannot combine multiple layers of transmissive objects, but that's not our business)

Actually declaring that mesh X, made even by a single quad, has a volume thickness of 0.5, tells the renderer:
when lights passes through this mesh, distort it like it was a glass mass of 0.5meters.
And they do the job quite well:
https://threejs.org/examples/?q=trans#webgl_loader_gltf_transmission
the different thicknesses you see along the glass cup, are addressed with a thickness texture, not by actually ray-tracing (that would be computationally overkill), so I don't understand why we would need a manifold mesh.

**Comment by stmaccarelli** [comment]
@donmccurdy 

> Since this plugin is enabled in Blender by default, I don't think we can/should add new UI panels unfortunately. 

I agree.

>Using a "Thickness" socket on a custom "glTF Settings" node has been our workaround for that, and since it's already required for Occlusion maps I think it would make sense for a Thickness map.

Maybe, yes. Does the glTF addon add a **glTF Settings** node? I didn't see it.

> Support for subsurface in glTF is on the roadmap, so we probably don't want to misappropriate that slot. :)

Well, I think that subsurface color and attenuation color can be the same, because if that object is green, would be green for subsurface color and transmission color too, the same applies for subsurface "density", I think we could safely use for attenuation distance too. 
Don't you think so? I see them as material / mesh properties, that most probably is the way PBR Materials are going to follow, I mean declaring properties of the object itself, that the renderer use to assign "CGI" properties.

**Comment by stmaccarelli** [comment]
**HOW MY PLUGIN WORKS**

My efforts are to export glTF with correct and complete transmission and volume data, to be used by webGL renderers that already correctly support them (Babylon.js and Three.js), by extracting data from Blender default material properties.
The official Khronos plugin currently only exports KHR_materials_transmission, and the importers (babylon, three) assign 0.001 thickness.
So I add KHR_materials_volume extension and properties to glTF materials that have KHR_materials_transmission enabled, and I also add KHR_materials_ior (index of refraction) because it's useful.

IF the to-be-exported glTF material has a **KHR_materials_transmission** glTF extension declared, I add **KHR_materials_volume** and its properties:

 **thicknessFactor**
  _The thickness of the volume beneath the surface. The value is given in the coordinate space of the mesh. If the value is 0 the material is thin-walled. Otherwise the material is a volume boundary. The doubleSided property has no effect on volume boundaries. Range is [0, +inf)._
taken from  **blender_material.refraction_depth**
_that serves the same purpose for "screen space refractions" in Blender_

**attenuationColor**
_The color that white light turns into due to absorption when reaching the attenuation distance._
taken from **blender_material.node_tree.nodes["Principled BSDF"].inputs['Subsurface Color'].default_value**
_This is going to work only if the object has Principled BSDF material, but has to be tested with other Blender materials (glass? refraction?)_

**attenuationDistance**
_Density of the medium given as the average distance that light travels in the medium before interacting with a particle. The value is given in world space. Range is (0, +inf)._
taken from **blender_material.node_tree.nodes["Principled BSDF"].inputs['Subsurface Radius'].default_value**
_This is going to work only if the object has Principled BSDF material, but has to be tested with other Blender materials (glass? refraction?)
This needs some more work extracting the right values, but I'm on it._

then I add the **KHR_materials_ior** extension, with its only **ior** property taken straight from
**blender_material.node_tree.nodes["Principled BSDF"].inputs["IOR"].default_value** 
_This is going to work only if the object has Principled BSDF material, but has to be tested with other Blender materials (glass? refraction?)_

**Comment by stmaccarelli** [comment]
@emackey did a great job here [https://github.com/KhronosGroup/glTF-Blender-IO/issues/1454#issuecomment-928319444
](https://github.com/KhronosGroup/glTF-Blender-IO/issues/1454#issuecomment-928319444
)
My aim was to make something that would work easily, matching simply what I see in Blender to what I see in Three / Babylon.
This is the reason it's coded as an "extension of the addon", as from Khronos specs (that now became very minimal, I started from an actual working example I can't find anymore)

yes, like you state attenuationDistance and attenuationColor can be taken out Volume Scatter node, and it's way better than taking them from subsurface data. In blender they serve the same purpose and I can even see the result in eevee.

**Comment by stmaccarelli** [comment]
@emackey I misunderstood some of your comments, pardon moi.
To wrap it up, I'll update my plugin attenuation data according to your suggestion.
And, it actually has the checkboxes in the export panel, and I could add checkboxes for every property and glTF extension he would add.

**Comment by julienduroure** [comment]
> Since this plugin is enabled in Blender by default, I don't think we can/should add new UI panels unfortunately.

If necessary, we can add some addon preferences and restrict UI panel  / operator to create glTF Settings node to be displayed only when option is activated in addon preferences (off by default)

**Comment by stmaccarelli** [comment]
Ok, I've changed a bit the logic of my addon.
- I still take  KHR_materials_volume['thicknessFactor'] from Refractin Depth (Settings tab in Material panel)
- I still take KHR_materials_ior['ior'] from Principled BSDF IOR property
- Now I take  KHR_materials_volume['attenuationColor'] and KHR_materials_volume['attenuationDistance'] from a Volume Absorption node in the node graph, the first one created, that can also be unconnected
- changed the UI of the addon in the export panel, now you can select what extension and property want to export.

Here it is:
https://gist.github.com/stmaccarelli/acc97d9f9b00cd1f7169455d5404f388.js
 
I think this is a tool to simplify the export of KHR_materials_volume and KHR_materials_ior straight from Blender, but it's far from perfect.
The main feature missing is exporting thicknessTexture, but as I can understand we are far from "standardising" this idea from blender.

For this reason, maybe is better to keep the export of volume extension into an external addon like this.
Don't you think so?

**Comment by donmccurdy** [comment]
Awesome, thanks @stmaccarelli! For some reason the link above didn't work, here's a fixed version:

https://gist.github.com/stmaccarelli/acc97d9f9b00cd1f7169455d5404f388

Blender is probably never going to have built-in sockets for baking outputs, like occlusion and thickness textures. Blender computes these on the fly, but runtime loaders often can't, so it's a difference in Blender's goals there. We do want to bring this support into the official addon. My opinion on handling `thicknessTexture` would be:

1) Look for a "Thickness" socket on "glTF Settings" node (as we do for Occlusion)
2) If neither refraction depth nor "Thickness" is present, export `KHR_materials_ior` but not `KHR_materials_volume`
3) Perhaps someday we can automatically bake thickness on export, but not yet

**Comment by vrsebas** [comment]
> > Since this plugin is enabled in Blender by default, I don't think we can/should add new UI panels unfortunately.
> 
> If necessary, we can add some addon preferences and restrict UI panel / operator to create glTF Settings node to be displayed only when option is activated in addon preferences (off by default)

Hi, I've been trying this for a work project and it was pretty useful, do you think this could be merged and added to the addon itself? may be it could be hold as an experimental feature.

![image](https://user-images.githubusercontent.com/40178251/167720577-6437d122-e283-491e-b2ce-64a176bcd8ba.png)

**Comment by julienduroure** [comment]
Hello,
Based on this comment : https://github.com/KhronosGroup/glTF-Blender-IO/issues/1454#issuecomment-928319444
I started to implement it here : #1646

**Comment by julienduroure** [comment]
Closing this ticket, as #1646 is now merged
