### ISSUE TITLE
T58955 Export animated FBX to glTF 2.0 

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#153]
Bug from blender tracker: https://developer.blender.org/T58955

**Comment by donmccurdy** [comment]
If it's helpful I've tested and documented a workflow for FBX files from the source mentioned, Mixamo, in the past: https://www.donmccurdy.com/2017/11/06/creating-animated-gltf-characters-with-mixamo-and-blender/. I haven't re-tested this since Blender 2.8, however, and it would be an important workflow to keep intact. 👍

**Comment by donmccurdy** [comment]
@UX3D-nopper I'm moving this to MS VII because it seems to be skinning-related, and I assume that the more examples we have, easier it will be to identify the correct fixes. If you think this should be left out of the milestone please let me know.

**Comment by donmccurdy** [comment]
^the material issue can be considered out a separate problem for now.

**Comment by UX3D-becher** [comment]
also fixed by #412
