### ISSUE TITLE
Extra Nodes in Three.js vs. Blender

### ISSUE THREAD

**Issue by mysterybear** [KhronosGroup/glTF-Blender-IO#1535]
Here's the GLTF in Blender:

![image](https://user-images.githubusercontent.com/50906986/149509663-9f0a5007-1133-4c12-91c5-fa9f570629cf.png)

Here's a log of the node keys in Three.js:

![image](https://user-images.githubusercontent.com/50906986/149509721-fce9c869-63de-4625-bab3-8f4f16c02bc3.png)

Here's a zip with the GLB:

[mobble.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/7870093/mobble.zip)

The issue is the nodes at the top in the Three.js output, beginning with 771... Wondering where they come from?

**Comment by scurest** [comment]
There are 32 nodes in the .glb you attached. They exactly match the objects in Blender, so there does not appear to be any issue with the Blender export.

```sh
$ glb-json mobble.glb | gron | rg nodes | rg name | cut -d ' ' -f 3 | sort
"IfcBeam/None.012";
"IfcBeam/None.016";
"IfcBeam/None.018";
"IfcBeam/None.024";
"IfcBeam/None.026";
"IfcBuildingElementPart/None.003";
"IfcBuildingElementPart/None.010";
"IfcBuildingElementPart/None.017";
"IfcColumn/None.007";
"IfcColumn/None.008";
"IfcCovering[CLADDING]/None";
"IfcCovering[CLADDING]/None.001";
"IfcCovering[CLADDING]/None.005";
"IfcCovering[CLADDING]/None.009";
"IfcCovering[CLADDING]/None.015";
"IfcCovering[CLADDING]/None.020";
"IfcCovering[CLADDING]/None.021";
"IfcCovering[CLADDING]/None.023";
"IfcCovering[CLADDING]/None.025";
"IfcCovering[FLOORING]/None.002";
"IfcFurnishingElement/None.004";
"IfcFurnishingElement/None.006";
"IfcFurnishingElement/None.013";
"IfcPlate/None";
"IfcPlate/None.001";
"IfcProject/None";
"IfcSite/None";
"IfcWall/None.011";
"IfcWall/None.014";
"IfcWall/None.019";
"IfcWindow/None.022";
"IfcWindow/None.027";
```

It appears Three uses a Group for glTF meshes with multiple primitives

https://github.com/mrdoob/three.js/blob/aca1c4f4503c887331d3045eb9984749185a840b/examples/jsm/loaders/GLTFLoader.js#L3572

And indeed, the meshes `77/1040` and `77/1326` are the only meshes with more than one primitive (this happens because the Blender mesh uses multiple materials).

**Comment by mysterybear** [comment]
That's really helpful @scurest thanks so much!
