### ISSUE TITLE
UV (or texture transform) mismatch

### ISSUE THREAD

**Issue by drewp** [KhronosGroup/glTF-Blender-IO#1540]
[glb-textures.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/7884699/glb-textures.zip)

In blender-3.1.0-alpha+master.34d424fd64bb (2022-01-17), this looks good, but in the GLB export (displayed in https://gltf-viewer.donmccurdy.com/ or no sketchfab), the textures are way too big.

good:
![image](https://user-images.githubusercontent.com/104003/149838325-3a8f0636-15b4-4f65-bf95-148c1ef649a0.png)

wrong:
![image](https://user-images.githubusercontent.com/104003/149838368-0565505f-c611-4a2e-9a9c-37c1f6313e3e.png)

floor texture (from blenderkit):
![image](https://user-images.githubusercontent.com/104003/149838456-8401aa2f-634e-4caf-9b4c-fbcd304ed1a9.png)

**Comment by drewp** [comment]
io_scene_gltf2 version is 1.8.6

**Comment by scurest** [comment]
This is because the Texture Coordinate node uses the active UVMap, which is second one, while the glTF exporter exports it as using the first UVMap.

**Comment by julienduroure** [comment]
Confirm that both UVMap are exported in mesh primitives, but json texture does not include texCoord data, so 0 is used by default

**Comment by scurest** [comment]
It's not very easy to fix because the material code does not know what mesh it is being applied to. The glTF exporter needs to be able to export multiple materials for a single Blender material if the material is applied to meshes that affect it differently.

Same issue for this hilariously ballsy code for getting the UV index for a UV name 

https://github.com/KhronosGroup/glTF-Blender-IO/blob/3bc2858c714d5b517aa521a632906934fafdd4a8/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_texture_info.py#L166-L171

The easiest fix is probably to do a pre-scan of the material before calling gather_material that determines what UVMap information is used by the nodes. Then that information would be packaged up into a argument to gather_material and the cache system would handle the rest.

**Comment by julienduroure** [comment]
Another solution, to avoid run pre scan the tree, is to store what textures don't use explicit UVMap, and then override material with active materials for all these textures.
Some tests here : #1567
