### ISSUE TITLE
Incorrectly baked first frame for sampled animations with custom IK rig

### ISSUE THREAD

**Issue by STREGAsGate** [KhronosGroup/glTF-Blender-IO#1555]
**Describe the bug**
Exporting sampled animations with custom IK rig results in incorrectly sampled keys at the start of an animation.

**To Reproduce**
I've included a stripped down .blend file to make it easier to explore the issue.
I'm using a bone constraint to keep my rig control positioned on a bone, and more constraints to manipulate the IK target based on that control. Only the first couple frames are incorrect, the rest of the animation works as expected.

**Screenshots**
This is the bug in action.
![ezgif-7-97b5304113](https://user-images.githubusercontent.com/55062873/152664339-d11cc8d6-bf59-4b65-bfae-cb713134d904.gif)

**.blend file/ .gltf**
[Character.glb (1.8.14)](https://github.com/KhronosGroup/glTF-Blender-IO/files/8009176/Character.glb.zip)
[Character.blend](https://github.com/KhronosGroup/glTF-Blender-IO/files/8009175/Character.blend.zip)

**Version**
 - OS: macOS
 - Blender Version 3.0.1, 3.1 Beta

**Notes**
If I duplicate the first keyframe a couple frames behind the animation start, then it does export correctly.
<img width="605" alt="Screen Shot 2022-02-05 at 7 53 37 PM" src="https://user-images.githubusercontent.com/55062873/152664071-06d68b73-46d3-439b-b054-000ee303f7fd.png">

**Comment by julienduroure** [comment]
Hello,
Your rig has as dependency cycle. That means that it can't be baked correctly.
![image](https://user-images.githubusercontent.com/1696020/152670822-ebcec09d-4d13-40c3-ad53-d96619a32ec8.png)

You can see the problem in your console.
You can also check that the problem is not only during export, but you can see it in action in viewport:
- Go to frame 0
- Then go to frame 1
- Then  jumping from frame 1 to 2 and back multiple time

The rig settles only after a few cycles.
Don't think there is something we can do with a non correctly build rig.
