### ISSUE TITLE
Import glbf2 track name with object name suffix, which will get longer and longer

### ISSUE THREAD

**Issue by omega-ult** [KhronosGroup/glTF-Blender-IO#1588]
When import a gltf file, blender will set animation track with object name as suffix:

when export a new gltf file and import again, the suffix will ge longer and longer 

![image](https://user-images.githubusercontent.com/800629/157031597-b33a81f7-cf8a-4e6b-b08c-9a236098efdb.png)

at line 51 of gltf2_blender_animation_weight.py

```
        name = animation.track_name + "_" + obj.name
        action = bpy.data.actions.new(name)
        action.id_root = "KEY"
        gltf.needs_stash.append((obj.data.shape_keys, action))
```

**Comment by scurest** [comment]
> when export a new gltf file and import again, the suffix will get longer and longer

It shouldn't, have you tried this?

One glTF animation can affect multiple objects, so it is imported into Blender as (potentially) multiple actions, one for each object (or shapekey) the animation affects. That's why the action is named for both the animation and the object. The actions are logically grouped together by stashing them to NLA tracks with the same name, the name of the animation.

The exporter also uses the name of the NLA track for the animation name, so the action names don't matter and there should be no "buildup".

**Comment by omega-ult** [comment]
My case, blender import gltf then exported it as fbx to unity, then convert that fbx  to another gltf, since the fbx only stores the active animation name, so the gltf read that name as base name and add a object name again.
