### ISSUE TITLE
Armature animations seem to get merged at export 

### ISSUE THREAD

**Issue by pepperoni505** [KhronosGroup/glTF-Blender-IO#1616]
**Describe the bug**
I have a relatively complex armature with 14 NLA tracks, which are each unique. When exporting and importing into https://gltf-viewer.donmccurdy.com/, the animations all seem to be merged into one. The animation names still appear - but as stated contain every animation. See attached video for example

**To Reproduce**
1. Open the `.blend` file provided
2. View each NLA track individually
3. Export and open in https://gltf-viewer.donmccurdy.com/
4. Enable `skeleton` under `Display`
5. Only enable one animation, and see that it merged all the other animations

**Expected behavior**
Each exported animation matches what is shown in Blender, and is not merged.

**Screenshots**
https://user-images.githubusercontent.com/49950581/162104308-98b2c924-de36-463b-b7d3-a016afe0866b.mp4

**.blend file/ .gltf**
[armature issue.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/8438984/armature.issue.blend.zip)

**Version**
 - OS: macOS
 - Blender Version: 3.2 Alpha (2022-03-01 1:21)

**Additional context**

**Comment by julienduroure** [comment]
Confirmed.
Seems all NLA tracks are evaluated, even id an active action is set on object. Probably because you didn't Stash the actions, but you Pushed Down them.
This can be solved, as a workaround, by toggling channel muting your tracks before export (the checkboxes)

![image](https://user-images.githubusercontent.com/1696020/162122707-e94c9b7d-2421-44b0-9fe8-6e09ecb0f4ef.png)

In code, we need to disable them, and restore them (or better, if accessible in API, disable all track evaluation, the global checkbox at object level)

**Comment by pepperoni505** [comment]
Thanks for your quick response! After playing around with this, I seem to have encountered an even stranger error with my full model. My model seems to get rotated during the export process and the animations are completely screwed.

Pre-export:
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/49950581/162343138-65b77aad-76e2-409f-96c9-7b216d31694a.png">

Post-export:
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/49950581/162343473-4e6a38eb-30e4-4981-bcde-c8af5ef4bcd7.png">

Unfortunately I'm unable to simplify the issue, and I can't send this file here. I have sent you an email with the `.blend` file

**Comment by julienduroure** [comment]
This is a root cause already discussed here:
- Your armature has some keyframes on object directly, for some of your actions, but not all your actions
- When switch from action to another, non keyed objects and bones are not reset (this is a Blender way of working, not linked to glTF exporter)

How to solve your issue : 
- Do not keyframe on armature directly, for all your actions
- Or : Always keyframes your armature, for all your actions

**Comment by pepperoni505** [comment]
Forgot to mention this - I didn't modify anything with the model in Blender. I imported a glTF file and then exported it which resulted in this error. Could this possibly be related to an importer error?

**Comment by julienduroure** [comment]
No, there is probably not an importer error.
As explained, this is how Blender works.

We can try to workaround it, by adding a TRS reset to default when switching from animation to another.
But not sure this is something that we can always apply. Adding another option?

**Comment by pepperoni505** [comment]
Would it be possible to detect if this error would arise during the animation export process? That would be ideal instead of another option. If that doesn't work then the only solution would be adding that option.

**Comment by pepperoni505** [comment]
> This is a root cause already discussed here:
> 
>     * Your armature has some keyframes on object directly, for some of your actions, but not all your actions
> 
>     * When switch from action to another, non keyed objects and bones are not reset (this is a Blender way of working, not linked to glTF exporter)
> 
> 
> How to solve your issue :
> 
>     * Do not keyframe on armature directly, for all your actions
> 
>     * Or : Always keyframes your armature, for all your actions

I'm trying this out but still running into the same issue. I've tried stashing the animations that use keyframes, but that doesn't seem to work. Would you mind explaining this more?
