### ISSUE TITLE
Indexed geometry split in individual triangles when exporting as gltf

### ISSUE THREAD

**Issue by fknfilewalker** [KhronosGroup/glTF-Blender-IO#1644]
When I am exporting a very simple mesh with 32 triangles which are connected through indexed vertices in blender, it gets exported as 96 individual vertices in the resulting gltf.

using Blender 3.1.2

**Comment by scurest** [comment]
Vertices get split up so that they have unique attributes (normal, UV, etc.). Flat shading, sharp edges, UV seams, etc will cause this. See [this question](https://blender.stackexchange.com/questions/204713/how-to-stop-blender-from-generating-duplicate-vertices-on-export) or [this question](https://blender.stackexchange.com/questions/167372/gltf-export-has-twice-the-vertices-it-should). This is how glTF  works and can't be fixed.

Vertices also get split up if they are in tris with different materials, see [this](https://github.com/KhronosGroup/glTF-Blender-IO/issues/590#issuecomment-661102032).

**Comment by julienduroure** [comment]
Hello,
This is the correct behavior, as normals are exported by default, and glTF stores normals by vertex.
You have an option to not export normals, to avoid splitting vertex/normals.

**Comment by julienduroure** [comment]
Ah, same answer at same time with scurest :)
Closing this ticket, as there is no bug here

**Comment by fknfilewalker** [comment]
But when I export it as ply it is fine

**Comment by fknfilewalker** [comment]
> Hello, This is the correct behavior, as normals are exported by default, and glTF stores normals by vertex. You have an option to not export normals, to avoid splitting vertex/normals.

removing the normals worked

**Comment by funwithtriangles** [comment]
Just adding here that you can also do [Shade Smooth](https://docs.blender.org/manual/en/2.91/scene_layout/object/editing/shading.html) on your object in Blender to make sure the normals match on the shared vertices. 

I was trying to do some shader displacement stuff on my mesh and it was causing the triangles to separate. Doing the smooth shading in blender completely fixed the issue.
