### ISSUE TITLE
RoughnessFactor not being generated during export

### ISSUE THREAD

**Issue by j-conrad** [KhronosGroup/glTF-Blender-IO#1655]
When setting up a material with a Roughness texture connected to a MixRGB node (multiplying by a color value), the resulting export has no RoughnessFactor defined.

**To Reproduce**
1. Open the included .blend
2. Look at the Shader Editor (confirm the material setup is sound)
3. Export the scene as a .glTF
4. Open the resulting .glTF and observe the lack of RoughnessFactor. The ocean part of the sphere should appear slightly glossy, as opposed to the matte finish it would have without the MixRGB node. Instead, it remains matte.

**Expected behavior**
According to the [Blender manual](https://docs.blender.org/manual/en/dev/addons/import_export/scene_gltf2.html?highlight=gltf#factors), the MixRGB node set to Multiply should generate a RoughnessFactor.

**Screenshots**
![image](https://user-images.githubusercontent.com/31968496/170593427-d063753f-17fc-4996-b426-1075f49ef561.png)

**.blend file/ .gltf**
Attached below.

**Version**
 - OS: Windows 11
 - Blender Version: Release 3.1.2
 - Exporter Version: 1.8.19

[RoughnessFactor_Earth.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/8782644/RoughnessFactor_Earth.zip)

**Comment by scurest** [comment]
Roughness is a scalar, so the exporter is expecting scalar multiplication: a Math node (Add > Converter > Math) set to Multiply. Use this instead (note the value is 0.35).

![](https://user-images.githubusercontent.com/11024420/170623452-efafd3c2-4b51-40be-ab6f-853f7b8c69e7.png)

Also even if you were doing a color, the exporter expects a MixRGB node set to Multiply _with a Fac of 1_ (although it doesn't actually check that). The factor should go in the other socket.

![](https://user-images.githubusercontent.com/11024420/170622651-754b1bea-0250-4c25-80e9-a274b6ffb429.png)

About your setup: Fac is a lerp factor between `Color1` and `Color1 * Color2`. In general this is not a product unless Fac=1, but in your case since Color2=0, it's `lerp(Color1, 0, Fac) = (1-Fac)*Color1`, so it is actually equivalent to multiplying by 0.35.

**Comment by julienduroure** [comment]
So, no issue here. Tagging as documentation, this may need an update, or additionnal explaination about factors (scalar/color)
