### ISSUE TITLE
Indices type does not switch to uint above 65535

### ISSUE THREAD

**Issue by nothke** [KhronosGroup/glTF-Blender-IO#1671]
The type of the index should switch from unsigned short to unsigned int above 65535, as seen [here](https://github.com/KhronosGroup/glTF-Blender-IO/blob/223364cc69c5319561b1c61b2c861323db8e7470/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_primitives.py#L151), but that doesn't happen. It seems to only switch above 265535. (also this [twitter thread](https://twitter.com/Nothke/status/1539188128405151744)

I've narrowed down the error to the `indices.max()` function. For a simple cube (1 mesh, 1 primitive):
- indices.max() is 23
- len(indices) is 36

36 is the correct number of indices 2 * 3 * 6, this causes the type to not switch as it underestimates the count.

Switching `max_index = indices.max()` to `max_index = len(indices)` actually fixes the issue. But the issue might be in `indices.max()` itself? I tested with multiple meshes in a single primitive, one above the threshold and one below and `len(indices)` works just fine.

**Comment by julienduroure** [comment]
Hello,
At export, vertices get split up so that they have unique attributes (normal, UV, etc.). Flat shading, sharp edges, UV seams, etc will cause some vertices to be duplicated, to have the unique attributes.

For default cube, for example, here is the indice array:
1 14 20  1 20  7 10  6 19 10 19 23 21 18 12 21 12 15 16  3  9 16  9  22 5  2  8  5  8 11 17 13  0 17  0  4
There is 36 indices, but max indice is 23.

I can't see any bug here. This explains why unsigned int is not needed for export of 65535 length array of indices : indices value at not that high.

**Comment by nothke** [comment]
I see, it seems I completely misunderstood the issue 😅 I kept looking at the indices count, but yeah the vertex count is what defines the index type. The number 265535 might be a total accident.

I'll walk myself out and go cry now.

**Comment by julienduroure** [comment]
No problem.
We are all infinite learner!

**Comment by scurest** [comment]
@nothke (Aside: the reason byte color vertex colors export as ushort is because byte color in Blender = 8-bit sRGB. Vertex colors in glTF are linear and 8-bit sRGB = 12-bit linear, hence 16-bit is the smallest type that can represent it losslessly.)
