### ISSUE TITLE
'Mesh' object has no attribute 'color_attributes'

### ISSUE THREAD

**Issue by Gaia-X-Alter** [KhronosGroup/glTF-Blender-IO#1707]
https://github.com/KhronosGroup/glTF-Blender-IO/blob/d5b6052506445ab092dce3708175fcd8902d4073/addons/io_scene_gltf2/blender/imp/gltf2_blender_mesh.py#L316

**Describe the bug:**

after copying addons/io_scene_gltf2 into my scripts/addons/ folder to fix #1623 

I get this error when importing GLB file

```
AttributeError: 'Mesh' object has no attribute 'color_attributes'
addons\io_scene_gltf2\blender\imp\gltf2_blender_mesh.py", line 316, in do_primitive
```

blender:3.2.0 +addon->Commits on Aug 10, 2022

-----

Test Model↓
[test.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/9315822/test.zip)

**Comment by julienduroure** [comment]
Hello,
You can't use recent addon version with Blender 3.2.0, because some changes on Blender and bpy changes.
You can see here : https://github.com/KhronosGroup/glTF-Blender-IO/blob/d5b6052506445ab092dce3708175fcd8902d4073/addons/io_scene_gltf2/__init__.py#L19
the minimum version that is needed to run the addon.
