### ISSUE TITLE
Animation export does not work

### ISSUE THREAD

**Issue by ronangaillard** [KhronosGroup/glTF-Blender-IO#1719]
**Describe the bug**
I have an animation working in blender but when I export it to glb/gltf and load it in https://gltf-viewer.donmccurdy.com it does not work with error messages.

**To Reproduce**
1. Open the attached blend file
2. File -> Export -> GLB/GLTF
3. Save GLB file
4. Load it on https://gltf-viewer.donmccurdy.com and notice that animation don't play and that there are errors on the bottom left

**Expected behavior**
I would expect that https://gltf-viewer.donmccurdy.com plays animation

**Screenshots**
Blender animation playing :
![Sep-02-2022 09-52-33](https://user-images.githubusercontent.com/5607736/188101247-46611be0-5586-468e-8c0d-ec5e1c36c9be.gif)

Extract of errors on gltf viewer :
![image](https://user-images.githubusercontent.com/5607736/188101774-0a1e7ec0-89d8-43d0-8a08-64cff104aa09.png)

**.blend file/ .gltf**
Blend file : https://www.icloud.com/iclouddrive/040krqYCEBMlAzr6IE_1lu7qA#animated
GLB file : https://www.icloud.com/iclouddrive/030TurFjWPh0A6-trttonS6tw#animated

**Version**
 - OS: MacOS 12.5.1
 - Blender Version 3.2.2

**Comment by julienduroure** [comment]
Hello,
Thnaks for the report.
What you see is "hint", not errors. This is already solved in 3.3 RC

About animation:
- Animation are on armature, and are exported. But you used child of constraint for parenting your mesh to bones, so hierarchy is not correct in exported file. You should probably use direct bone parenting instead of ChildOf constraint. (Please use "use current frame" option for now, to workaround this bug #1677 )

- We should be able to bake animations using exporting selection only, but currently, only active action is baked on non animated object. I will have a look on that later.

**Comment by ronangaillard** [comment]
Hi Julien !

Works like a charm thanks !

For further reference I used this video to learn how to parent the bones : https://www.youtube.com/watch?v=o5f18T7Rjmc
