### ISSUE TITLE
Only export vertex colors when the material calls for them

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Blender-IO#1740]
Currently, if one imports a model with vertex colors, they show up as a color attribute with a mix node:

![node screenshot](https://user-images.githubusercontent.com/1235080/191560962-b9f6ad2d-f78f-4421-9906-670c54a35de3.png)

But when exporting, if vertex colors are present at all, they are exported into the glTF, affecting the material.  For example if the user has accidentally created empty vertex colors, the material may export as all black, even though Blender does not preview that.  This has caused some confusion among artists (both at my company and [externally](https://blender.stackexchange.com/q/275071/18161)), as Blender does not make the presence of vertex colors ("Color Attributes") particularly obvious, with the UI panel collapsed by default and the colors not influencing the material by default.

I'm starting to think that the exporter should avoid exporting vertex colors for any mesh unless the mesh bears a material that references the vertex colors from a node graph.  Thoughts?

**Comment by nmfisher** [comment]
I spent hours this morning trying to figure out why using Filament to open a Blender-exported glTF file crashed with `At least one buffer slot was never assigned to an attribute`.  Same problem even after deleting every material/texture and all but one mesh.

Turns out the mesh was being exported with Color Attributes (Face Corner/Byte Color, if that's relevant), COLOR_0 and COLOR_1. Filament will crash whenever the model has two Color Attributes, or a single Color Attribute with no associated material.

As far as Blender/glTF is concerned [0], I fixed the issue by unchecking "Vertex Colors" under the "Geometry" panel in the export window. This stopped those attributes from being exported.

![image](https://user-images.githubusercontent.com/7238578/197685904-7c01ecb5-a090-46bf-b0da-e5b5b02d6e2f.png)

I'm not sure I see a need for any change to the glTF exporter, given there's already an option to disable exporting vertex colors. 

What about making the "Vertex Colors" option unchecked by default?  There might be more people negatively affected by checked-by-default (i.e. who don't need to export vertex colors but still run into these kind of problems), than those who would be negatively affected by unchecked-by-default (i.e who do need to export vertex colors, but are already explicitly working with them therefore should know they need exporting). 

[0] Whether Filament is "correct" in crashing is a separate question that I'll raise on their repository (I suspect not - the spec doesn't require support for COLOR_ attributes but it shouldn't crash simply because they are present, but unused).

**Comment by emackey** [comment]
> What about making the "Vertex Colors" option unchecked by default?

My thinking is that the exporter should attempt to match the visual that the user has created for their model, as opposed to asking the user to learn to use a larger set of checkboxes.

The glTF spec is such that if `COLOR_0` is present, it gets multiplied with the base color, always.  If the user has something similar to this set up in their Blender material, we can best preserve that on export by including the vertex colors.  If the user has vertex colors assigned in Blender, but is not using them for the appearance of the model, then we must exclude them from the glTF export, because glTF offers no way to include disused vertex colors.

**Comment by scurest** [comment]
Some stuff to decide how/if to handle

* Is there still a "Vertex Colors" option? What does it do?
* What to do when a mesh has multiple materials that disagree about whether and which color attribute to use. Warn and pick one to "win"?
* What to do when a color attribute is used for base color but not for alpha (fairly common?). Could export COLOR_0 as vec3 without alpha.
* What to do when a color attribute is used for alpha but not base color. Could export COLOR_0 with one-filled RGB components.
* Does an opaque material that has "multiply alpha by color attribute alpha" nodes count as using the color attribute for alpha?
* What to do if different color attributes are used for base color and alpha. Could merge them together into COLOR_0 (similar to combining image channels).

**Comment by emackey** [comment]
> * Is there still a "Vertex Colors" option? What does it do?

It sounds like we would need this option.  When checked, Blender color attributes not used in the material would be exported as glTF custom vertex attributes, likely `_COLOR_0` as suggested above.  When unchecked, I'm less sure, but given that's a change from the default behavior, maybe the user is trying to turn off all vertex colors regardless of material nodes?

> * What to do when a mesh has multiple materials that disagree about whether or which color attribute to use. Warn and pick one to "win"?

Just like textures do now, yeah.  I can't think of a better suggestion.

> * What to do when a color attribute is used for base color but not for alpha (fairly common?). Could export COLOR_0 as vec3 without alpha.

Yes. glTF allows vec3 here, and it results in some space savings over vec4.

> * What to do when a color attribute is used for alpha but not base color. Could export COLOR_0 with one-filled RGB components.

Is this a common case we must support?  I'm fine if the documentation just disallows this, unless people really want it.

> * Does an opaque material that has "multiply alpha by color attribute alpha" nodes count as using the color attribute for alpha?

Good point, no.  If blend mode is opaque, no alpha channel need be included, and you can get the vec3 smaller storage again.

> * What to do if different color attributes are used for base color and alpha. Could merge them together into COLOR_0 (similar to combining image channels).

If this is relatively straightforward to do, it would be great, similar to how this project combines base color & alpha textures.  But if this is too much for our existing schedules or too negative an impact on code complexity, then we can disallow it and ask users to combine it into a single color attribute before export.

**Comment by scurest** [comment]
Does there need to be a separate option for exporting color attributes different than the option for exporting all attributes?

If COLOR_0 is only for material use, does it make sense to always make it unorm16? (So vec3 and vec4 would be the same size.)

**Comment by emackey** [comment]
> Does there need to be a separate option for exporting color attributes different than the option for exporting all attributes?

I think if we can see color attributes used in the material, and decide to export or not based on that, there's no need for an additional checkbox to control that.

I do think a (new?) checkbox could be helpful to control whether unused attributes get exported or not, defaulting to not.

> If COLOR_0 is only for material use, does it make sense to always make it unorm16? (So vec3 and vec4 would be the same size.)

Oh, I forgot.  I think this project already uses unorm16 for them.  So... no size savings as I wrote above, sorry.

**Comment by scurest** [comment]
> I think this project already uses unorm16 for them.

Currently only Byte Color attributes export as unorm16. Float color attributes export as floats.

**Comment by julienduroure** [comment]
Not sure why this ticket is still open, as we implemented it already. Closing
