### ISSUE TITLE
Incorrect hierarchy and position of objects parented to armature

### ISSUE THREAD

**Issue by brandon-lockaby** [KhronosGroup/glTF-Blender-IO#1753]
**Describe the bug**
Some of the exported objects lost their hierarchy and are incorrectly positioned

**To Reproduce**
1. Load provided incorrect.blend and observe the parenting hierarchy (Armature > sphere1 > sphere2 > sphere3) and positioning
2. Export GLB
3. re-import and/or test in gltf-viewer

**Screenshots**

**.blend file/ .gltf**
![before](https://user-images.githubusercontent.com/968126/194443414-0a174ec7-e738-48bf-81fd-1e1aeec02ccc.png)
![after](https://user-images.githubusercontent.com/968126/194443425-1629f6b4-2cbf-4dda-8888-4c9dbd9cf94c.png)
![gltf-viewer](https://user-images.githubusercontent.com/968126/194443430-a6e354c8-d74b-43c4-987e-e4a81ce77dd6.png)
[incorrect.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/9729599/incorrect.zip)

**Version**
 - OS: linux
 - Blender 3.3.0
 - gltf import/export 3.3.27

**Comment by julienduroure** [comment]
Confirmed.
TRS of skinned meshes must be ignored in glTF, so TRS of children of skinned meshes are wrong at export, because we don't have to take into account the parent TRS.

No hierarchy issue ar export. At import, because of this ignore TRS, we can't use direct parenting, and need to create a new node. You have the same behaviour in babylon.js for example.
