### ISSUE TITLE
Using "Limit to Selected Objects" and "Always Sample Animations" simultaneously results in exporting actions for ALL selected objects, even the ones without any actions

### ISSUE THREAD

**Issue by kokotron** [KhronosGroup/glTF-Blender-IO#1799]
When you have "Limit to Selected Objects" and "Always Sample Animations" simultaneously in the gltf export options, this results in exporting extra blank actions for all selected objects that don't actually had any action or animation assigned.

1. Select all files in a scene
2. Go to export gltf
3. Select "limit to selected objects" and "Always Sample Animations"
4. Export and check gltf/glb file in blender or on an online viewer such as babylonjs sandbox https://sandbox.babylonjs.com/

**Expected behavior**
Only existing actions among the selected objects should be exported.

**.blend file**
[gltf_export_test_blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/10106202/gltf_export_test_blend.zip)

**Version**
 - OS: Windows 10
 - Blender Version: 3.3.1

**Comment by julienduroure** [comment]
Hello,
This behavior was intentional, in order to manage the case where the selected object is not animated, but its parent is animated, and parent is not selected. Exported object will be animated.
With current version, you can use "optimize animation size", to remove not changing animations.

In the current refactoring, the "use selected objects" and "baking all objects" are dissociated, so you will be able to choose if you want to bake not animated objects or not.

Tagging this ticket as enhancement, as the "optimized animation size" option can be used to avoid to export not wanted animations.

**Comment by julienduroure** [comment]
> When "Group by NLA Track" is deactivated

As said in tooltip, this option, when deactivated, export only active action of each objects into a single glTF animation.
In your file, no object have active action, so no actions are exported (again, modulo bake/selection).
Same for shapekeys, they are not active

This "Group by NLA Track" will also be enhanced during refactoring, to take into account more use cases

**Comment by julienduroure** [comment]
Sorry yes, "Assigned" (or what I called "Active") is the action you can see on Action Editor of DopeSheet:

Here nothing:

![image](https://user-images.githubusercontent.com/1696020/204473994-bc479817-08b6-4fd7-8a94-0063ee9218ff.png)


Here an action is assigned:

![image](https://user-images.githubusercontent.com/1696020/204474190-707601e3-20ce-4423-bdda-6640517e945b.png)

This can be done with one of these 2 ways:
- Assigning the action on Action Editor
- Tweaking action on NLA track (TAB)

**Comment by julienduroure** [comment]
Hello,
This is now fixed in current main branch, after animation refactor 64e3532f48ebdf878a1c9b81ade6d1a19c8ff890

Using "Selection Only" will not bake animation on non animated objects, except if you activate the option "bake all object animation"
