### ISSUE TITLE
Incorrect handling of Specular=0

### ISSUE THREAD

**Issue by scurest** [KhronosGroup/glTF-Blender-IO#1812]
Specular=0 is not handled correctly.

Here's two colored spheres in Blender, one with Specular=0, one with the default Specular=0.5 (other parameters are default). You can see the left one has no specular reflections.

![sph1](https://user-images.githubusercontent.com/11024420/208741978-72954e8f-0239-4342-a24d-c95b6f7b39da.jpg)

Exporting produces a glTF with specularColorFactor=[0,0,0]. Here it is in the Three viewer (same in Babylon)

![sph3](https://user-images.githubusercontent.com/11024420/208742092-f3f206b8-fbf0-41fb-937e-93ac060329ac.jpg)

Unlike in Blender, you can see the first sphere has faint reflections away from the 0° angle. Compare with the third sphere I added by hand with specularFactor=0 that has none.

This is consistent with the description in KHR_materials_specular

> The specular color is a directional-dependent weight included in the Fresnel term. At normal incidence (f0), specularColor scales the F0 reflectance f0_color. At grazing incidence (f90), the reflectance remains at 1. In between the scale factor is smoothly interpolated.

Importing the glTF back into Blender produces

![sph4](https://user-images.githubusercontent.com/11024420/208742128-d20c13f9-a11a-419d-8b95-983925f1c109.jpg)

**Comment by julienduroure** [comment]
Some general notes before checking this particular case:

- glTF and Blender current Principled BSDF node are not using same shading models, so they are not 100% compatible. Some conversion are done, but we can't cover 100% because of this model difference. See here for conversion model used: https://gist.github.com/proog128/d627c692a6bbe584d66789a5a6437a33
- A future version of Blender Principled BSDF node (no release date yet) will be 100% compatible with glTF model. So no conversion will be needed anymore. See https://developer.blender.org/T99447
- If you want to be fully compatible, you can use input from glTF material node output, and use option "Export Original PBR Specular". This will use custom sockets from glTF Material output node instead of data from Principled node. See documentation here: https://docs.blender.org/manual/en/latest/addons/import_export/scene_gltf2.html#specular

**Comment by scurest** [comment]
The Specular=0 case can be perfectly converted using specularFactor=0, as you can see. I'm just not certain how general this case is, ie. if there are constraints required on the metallic/transmission.

**Comment by julienduroure** [comment]
Blender 4.0 has now a new Specular model, so conversion from/to Blender/glTF is no more requested.
This case is no more relevant, closing this ticket.
Thanks!
