### ISSUE TITLE
Imported Nodes for SpecGlossVsMetalRough sample model are not all using Principled BSDF + Export is broken

### ISSUE THREAD

**Issue by ROBYER1** [KhronosGroup/glTF-Blender-IO#1853]
**Describe the bug**
Imported Nodes for SpecGlossVsMetalRough sample model are not all using Principled BSDF and the export/reimport of the model via glb/gltf  is broken as the spec/gloss water bottle imports as a black Principled BSDF

**To Reproduce**
1. Import the glb from here: https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/SpecGlossVsMetalRough
2. See the nodes on the materials
3. Export them and reimport them to see the specular gloss 

**Expected behavior**
Imported SpecularGloss model should use Principled BSDF node like other GLTF models, exported/reimported model shouldn't be a plain black material

**Screenshots**
![Nodes_Metal1](https://user-images.githubusercontent.com/10745594/216396362-dc910961-92e8-4a8b-b636-e781ff25f44a.jpg)
![Nodes_SpecG1](https://user-images.githubusercontent.com/10745594/216396368-ac97ade8-a0d0-4e0a-8b0b-16caf73585e1.jpg)

The exported from Blender and reimported model which is black:
![Imported](https://user-images.githubusercontent.com/10745594/216396533-b49bd393-4eaa-46b5-8a3d-1302e20d4ae5.jpg)

**.blend file/ .gltf**
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/SpecGlossVsMetalRough

Version
OS: Windows 11
Blender Version 3.4.1

**Additional context**
Could be useful to have a Blender file including all sample models or an automated test to verify the import and exports of the sample models are 1:1

**Comment by julienduroure** [comment]
Hello,

KHR_materials_pbrSpecularGlossiness is not using Principled BSDF node at import. This is an intentional behaviour, as the SpecGloss model is not compatible with Principled BSDF. This is not possible to represent SpecGloss data with this node, that is based on a MetallicRoughness model.

KHR_materials_pbrSpecularGlossiness export is not implemented. This glTF extension is not archived and it is not recommanded to create new glTF files using this extension. glTF specification now recommands to use PBR MetallicRougness model.
See https://github.com/KhronosGroup/glTF/blob/main/extensions/README.md#archived-extensions-for-gltf-20

Anyway, when re-importing, we have to solve a division by zero issue, so keeping this ticket alive to take this into account

**Comment by scurest** [comment]
Would it make sense to perform a crude conversion of SpecGloss to MetalRough and import that instead? The tradeoff would be it wouldn't look as accurate inside Blender, but it would export the same way it imported, and we could get rid of all the poorly exercised code in gltf2_blender_KHR_materials_pbrSpecularGlossiness.py.

For example

```py
# Preserves only the diffuse and a constant glossiness
def specgloss_to_metalrough(specgloss):
    metalrough = {}

    metalrough["baseColorFactor"] = specgloss.get("diffuseFactor")
    metalrough["baseColorTexture"] = specgloss.get("diffuseTexture")

    if "specularGlossinessTexture" not in specgloss:
        glossiness = specgloss.get("glossinessFactor")
        metalrough["roughnessFactor"] = 1 - glossiness
    
    metalrough["extras"] = specgloss.get("extras")
    metalrough["extensions"] = specgloss.get("extensions")

    return metalrough
```

![new](https://user-images.githubusercontent.com/11024420/216659253-3ffd43a3-eb5e-42f8-9c64-6854c873739e.jpg)

**Comment by scurest** [comment]
Cf https://developer.blender.org/T82974, #1269

**Comment by julienduroure** [comment]
Let's discuss the option to convert into this new ticket #1857 
Let's keep this one for the import issue (division by zero)
