### ISSUE TITLE
[Blender 3.6] Exported animations have a track for every bone, even though the original action only has 2 channels animated

### ISSUE THREAD

**Issue by ansonkao** [KhronosGroup/glTF-Blender-IO#1884]
The following `.blend` file with a single action, when exported from Blender 3.6, will end up with 400+ tracks in the animation, even though the original `.blend` file has only 2 channels in the action (bending the rig's neck to the right). It seems like it's baking all possible bones in the rig. If there is a setting to turn this off, I can't find it.

[blender-3.6-bug.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/10987741/blender-3.6-bug.zip)

This is what's in the file:
<img width="200" alt="image" src="https://user-images.githubusercontent.com/300092/225542712-b3830e13-4e2e-4d73-88b2-8a22ec0aef7b.png">

Original Action just has these 2 neck bones animated:
<img width="228" alt="image" src="https://user-images.githubusercontent.com/300092/225543263-a13e550d-6f3a-40cb-a616-5b62186ef3bc.png">

Exported Animation has ALL bones animated:
<img width="278" alt="image" src="https://user-images.githubusercontent.com/300092/225542987-23c6f08a-286a-46f6-b102-7f8317cbd57a.png">

macOS Big Sur 11.5.2

**Comment by julienduroure** [comment]
Hello,
The option you are looking for is in Animation > Optimize animations
You have to uncheck "Force keeping channel for armature / bone

![image](https://user-images.githubusercontent.com/1696020/225551766-98bb8791-2706-47d8-a03e-d7ff1e4c72e2.png)

**Comment by ansonkao** [comment]
Thanks Julien!

I'd suggest adding something like this to the tooltip:
"All possible channels for the armature and bones will be exported, even if empty"

Current tooltip:
<img width="452" alt="image" src="https://user-images.githubusercontent.com/300092/225554098-18a0e2cb-6f64-4f01-a4a5-c6a3918cc566.png">

**Comment by ansonkao** [comment]
Hi @julienduroure,

I'm still getting similar problems in Blender 3.6:
- Tracks for scale and position appear in the export, even though the original action only has rotation, despite "Force keeping channel for armature / bone" being unchecked
- The root object has scale/position/rotation appear in the export, even though the original action has no such tracks defined. In many cases, a scale of `[0, 0, 0]` is being exported in the animation for the root object, resulting in the entire scene being invisible.
- If there are two actions, one that only animates 1 bone, and another one that animates the entire rig, there are some settings that result in both actions exporting with tracks for every possible bone. This is similar to the original complaint, but WITH "Force keeping channel for armature / bone" unchecked

It's proving very difficult for me to reproduce the problems because there are so many new configuration options and I've lost track of which one is which. 

Is there an updated version of [this doc page](https://docs.blender.org/manual/en/latest/addons/import_export/scene_gltf2.html) somewhere for Blender 3.6 where I can learn more about each config option in more detail? I can't find it in this repo, the most recent branch is `blender-v3.5-release` 

In the meantime I'll try to isolate the issue and share a `.blend` file

**Comment by julienduroure** [comment]
> Tracks for scale and position appear in the export, even though the original action only has rotation, despite "Force keeping channel for armature / bone" being unchecked

Is there any constraints on your rig bones? Is your bone animated (because of constraint or parenting) ? Please share your .blend file

> The root object has scale/position/rotation appear in the export, even though the original action has no such tracks defined. In many cases, a scale of [0, 0, 0] is being exported in the animation for the root object, resulting in the entire scene being invisible.

Please share your .blend file

> If there are two actions, one that only animates 1 bone, and another one that animates the entire rig, there are some settings that result in both actions exporting with tracks for every possible bone. This is similar to the original complaint, but WITH "Force keeping channel for armature / bone" unchecked

Is there any constraints on your rig bones? Is your bone animated (because of constraint or parenting) ? Please share your .blend file

> Is there an updated version of [this doc page](https://docs.blender.org/manual/en/latest/addons/import_export/scene_gltf2.html) somewhere for Blender 3.6 where I can learn more about each config option in more detail? I can't find it in this repo, the most recent branch is blender-v3.5-release

3.6 is currently developed in main branch, so documentation link is https://docs.blender.org/manual/en/3.6/addons/import_export/scene_gltf2.html
But there is still some detail to be added.

For rigs:
- For every bone, each T/R/S channel will be added, for every frame. This is how we can handle bones animated by constraints. A bone can have no fcurve in a channel, but is animated in armature space, because of constraints.
- If "Optimize" is checked: For channels where all values are identical (so bone channel is not animated in armature space, no matter if there are some real keyframes on the bone), we keep only the 1rst keyframe and the last one.
- If "Keep channels for bones" is uncheck: 
  - If the channel was really animated by real keyframes (so there is a fcurve) and all keyframes in armature space are identical, we keep the channel (so 1rst and last ones)
  - If the channel was not really animated (so no fcurve on this channel), and all keyframes in armature space are identical, channel is not exported

**Comment by ansonkao** [comment]
My scene does not have any constraints, just a simple deforming skeleton.

Okay I've reproduced and isolated some of the issues:

For this file [blender-3.6-bug-2.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/11025751/blender-3.6-bug-2.zip), I'm finding the following results when exporting:

CASE 1) "Optimize Animation Size" checked OFF ⛔ = all exported animations have tracks for ALL bones, even if original file only had 2 channels. This seems incorrect...
CASE 2) "Optimize Animation Size" checked ON ✅ = exported animations have the correct number of tracks BUT with 3 EXTRA tracks for the rotation/scale/position of `Rigged_Female`. In particular, the scale with `[0, 0, 0]` is problematic, but all 3 seems like bugs to me.

For case 1 and 2, here is the full export config:
<img width="327" alt="image" src="https://user-images.githubusercontent.com/300092/226541028-f7274ab3-3d4c-45f9-a42d-4c33aac8a6f6.png">

The following options don't seem to affect the results for me:
- Animation > Armature > "Reset pose bones between actions"
- Animation > Rest & Ranges > "Use current frame as object rest transformations"
- Data > Armature > "Use rest position armature"

**Comment by ansonkao** [comment]
I've reproduced the other issue:

CASE 3) For this file [blender-3.6-bug-3.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/11027500/blender-3.6-bug-3.zip), the same `head_Head_tilted` action has only 2 rotation channels, and when exported with the options shown below, result in 9 tracks: 3 for the `Rigged_Female` root, and unexpected position and scale tracks for the 2 bones.


<img width="230" alt="image" src="https://user-images.githubusercontent.com/300092/226586674-89dbeba0-2655-48d2-a9b0-3a003da8a8d0.png">

**Comment by julienduroure** [comment]
This should be fixed now.

Now, "Force keeping animations" are no more linked to "optimize size". These options are now independent.
Now, armature is based on Object Force keeping, no more associated to Bone Force keeping.


Some note, and reply to your other questions:

- NLA Tracks & Scene are full bake (all objects & sampling). I added a note on it in UI. You have to use Action mode if you want if you don't need to bake because of constraints or complex NLA strip use.
- Animation > Armature > "Reset pose bones between actions" has no effect in your case, because you don't have bones that are animated in an action, and not in another, exported after the first one, with some different TRS.
- Animation > Rest & Ranges > "Use current frame as object rest transformations" => You don't have any animated object in your scene, so no impact
- Data > Armature > "Use rest position armature" => I can see the difference here. It changes the rest pose. But once animated, you can't see any difference.

Using rest position armature, disable animations:
![image](https://user-images.githubusercontent.com/1696020/232502042-cc0f76cd-b766-478e-97c8-8a812d32524b.png)

Not Using rest position armature (so current frame as rest pose), disable animations:
![image](https://user-images.githubusercontent.com/1696020/232502228-2c17e791-0942-479f-8a1e-6f25621b15da.png)
