### ISSUE TITLE
Mesh attribute order has changed

### ISSUE THREAD

**Issue by legends2k** [KhronosGroup/glTF-Blender-IO#1888]
**Describe the bug**
When a mesh is exported in Blender 2.92, the attribute order is Position, Normal and Texture Coordinates (_PNT_):

``` json
"meshes":[{
  "name": "Circle",
  "primitives": [
    {
      "attributes": {
        "POSITION": 0,
        "NORMAL": 1,
        "TEXCOORD_0": 2
      },
      "indices": 3
    }
  ]
}]
```

However, with Blender 3.4.1, I see the order has changed to Position, Texture Coordinates and Normal (_PTN_):

``` json
"meshes":[{
  "name": "Circle",
  "primitives": [
    {
      "attributes": {
        "POSITION": 0,
        "TEXCOORD_0": 1,
        "NORMAL": 2
      },
      "indices": 3
    }
  ]
}]
```

**To Reproduce**
1. Export in Blender 2.92 any model
2. Export in Blender 3.4.1 the same model
3. See the order changed

**Expected behavior**
The order is maintained as in older versions since it allows tools to be written atop this.

**Version**
 - OS: Archlinux
 - Blender Version 3.4.1

**Additional context**
If attribute order can be changed by the user (via a setting), this issue wouldn't be a problem.  As it is, this isn't present, hence older tools written with PNT order gets broken due to order change.

**Comment by julienduroure** [comment]
Hello,

There is nothing in glTF specification saying that vertex attributes must come in a given order. There are identified by their names.
So there is no reason to have a fix order during export.

**Comment by legends2k** [comment]
Thanks for the reply @julienduroure .  Agreed, the spec doesn't mandate any order.  However, if there're tools written depending on the order, it'd be nice to have some consistency.

My understanding of storing a glTF document as `.gltf` + `.bin` is that the binary file can be uploaded to the GPU as-is without any shuffling.  This facilitates shaders accessing those attributes in the order of the bin.  Having to re-wire the shader inputs every time after an export becomes additional work.

I might be missing something that's obvious for most graphics devs, so correct me if I'm wrong.

**Comment by donmccurdy** [comment]
The order of these JSON keys is just the tip of the iceberg in terms of vertex layout — the keys may have an order entirely unrelated to the byte order of the vertex attributes, vertex attributes may be organized into buffer views differently, and vertex attributes may be interleaved in various ways.

There is no one vertex layout that would fit all engines, but whatever your engine requires, it's probably possible to pre-process a valid glTF file to that layout. If you're building an engine or loader, I think you have three choices here:

- (A) Allow some flexibility in the vertex layouts your engine supports
- (B) Pre-process the glTF files offline with a consistent optimizer
- (C) Pre-process the glTF files at runtime

In [three.js](https://threejs.org/) we do (A), and can upload a flexible range of glTF vertex layouts directly to the GPU. We recommend (B) in addition, since most glTF files can optimized a lot beyond what DCC tools like Blender export. We avoid (C) in all cases except sparse accessors.

A few good options for pre-processing glTF files would be:

- [gltfpack](https://github.com/zeux/meshoptimizer/tree/master/gltf#-gltfpack)
- [cgltf](https://github.com/jkuhlmann/cgltf)
- [gltf-transform](https://gltf-transform.donmccurdy.com/)

I believe gltfpack will be fairly consistent about its ordering and interleaved output. The latter two may require configuration to set the order as specifically as you're describing.

***

I'll defer to @julienduroure on the practicality of the request here, but I think you may be looking for stricter constraints (identical GPU vertex layouts across Blender versions) than would be compatible with long-term maintenance of this addon, and a pre-processing step would be both more stable and more efficient, since further glTF optimizations can be included.

**Comment by julienduroure** [comment]
I change the order of attribute, even if we should not care about it.
I also added a hook to be able to change it if needed.
Example here: https://github.com/julienduroure/gltf-hooks-examples/blob/main/attributes_order_change.py

**Comment by legends2k** [comment]
Didn't expect this, thank you @julienduroure!
