### ISSUE TITLE
Multi rig support

### ISSUE THREAD

**Issue by jakob-leue** [KhronosGroup/glTF-Blender-IO#189]
Hello,

it seems like multiple rigs aren't supported yet? During this year, I tried to export multiple objects that are rigged (two characters eg) into .glTF, but always stumbling into issues.
Trying out different settings, at the moment I'm in a status where only one action/rig works in the viewer/importer - the other rigs are ignored. 
I'm testing my exported scenes in the donmccurdy viewer - so do you think it's something exporter related or is it more an issue of three.js?
Until now, I wasn't able to find a related issue yet, so thanks in advance and best regards.
![multirigscene](https://user-images.githubusercontent.com/36230197/50016785-7834c100-ffca-11e8-967a-86c1bf470310.PNG)

**Comment by julienduroure** [comment]
Can you please retest it?

**Comment by donmccurdy** [comment]
Result attached:
[multiRigUnfold.glb.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3827778/multiRigUnfold.glb.zip)

The skins and animations are there, it looks like, but they don't play back the same way if you just play each animation simultaneously, as a viewer like mine will do... not sure if that can be fixed in the .blend, or if it requires support for timing of strips within NLA tracks...
