### ISSUE TITLE
Expected behavior of pbrMetallicRoughness's metallicRoughness textures

### ISSUE THREAD

**Issue by chaoticbob** [KhronosGroup/glTF-Blender-IO#1956]
Hi, I have a scene with several materials that only have baseColor, roughnesss, and normal textures. Metallic is set to 0 in the material. When I export from Blender, I noticed that the metallicRoughness textures for these materials have 1.0 (or 255) for the R and the B channel. The G channel had the roughness data in it.

My understand is that R channel doesn't get used for pbrMetallicRoughness. But since I had metallic set to 0, I was expecting the B channel to have a vlaue of 0. Is there a step that I'm missing?

I'm loading through cgltf and I've double checked to make sure there weren't individual flags for metallic and roughness - and their factors. But both attributes are combined as metallicRoughness.

I couldn't find any discssion of this on the web or in this repo, but maybe my search-fu is weak? Curious to know what the expected behavior for the metallicRoughness texture is when one or the other doesn't have a texture?

**Comment by julienduroure** [comment]
Confirmed your behavior, but don't think this is a bug.

Issue come from here: https://github.com/KhronosGroup/glTF-Blender-IO/blob/60b7e7e6bef2be83468e8bdd68463788e38ec170/addons/io_scene_gltf2/blender/exp/material/gltf2_blender_gather_image.py#L254
where data are initialized to 1 when no texture is provided ( because 1 is the default value of metallicFactor)
You may be right saying that in that case, we need to fill with the default value of the socket.

I am currently away from keyboard, I will take care of it after August 15th

**Comment by chaoticbob** [comment]
Hi, thank you for the response. I double checked the spec after making the post ot discover that the default value was 1. I'll check back after the Aug 15th. Thanks.

**Comment by julienduroure** [comment]
Seems I missed something on this bug report.
No matter the R channel value are, as the json contains metallicFactor = 0
The fix will be removed, as there is no bug here, and the PR creates a bug described in #2076
