### ISSUE TITLE
I am not able to export blender file to GLB: Index 166 is out of bound for axis 0 with size 166 

### ISSUE THREAD

**Issue by Prashant3DWonder** [KhronosGroup/glTF-Blender-IO#1990]
**Description**
I think one of the main problem is model size is quite huge, but exporting FBX is working properly for it

**Steps To Reproduce**

1. Import Blender file 
2. Export to GLB
3. See error (Attached Image file )

**Expected Behaviour**
I think it should export GLB 

**Screenshot**
(https://drive.google.com/file/d/1O413uKDV8RUhgsDLirwPZM7OCvuOdWXF/view?usp=drive_link)

**.blend file/ .gltf**
https://drive.google.com/file/d/1sr3Co5u2TC2PYlmEhW2Q8kPguUhaV-PG/view?usp=drive_link

**Version Info**
 - macOS
 - Blender Version [3.6.2 17-08-2023]

@julienduroure

**Comment by julienduroure** [comment]
Hello,
This is already fixed in 4.0 alpha, recent build.
I don't know how you generate this file, but you have multiple invalid mesh data.
These objects are detected using object.data.validate()
We now try to export them if validate() fixes the issue. In case validate() didn't solve the issue, these mesh data are no more exported instead of crash.
