### ISSUE TITLE
Blender3.6 does not support HDRI as part of gltf export

### ISSUE THREAD

**Issue by myinzack** [KhronosGroup/glTF-Blender-IO#2054]
Hi,

We exported .hdr environment texture into blender and added avatar to the scene.
But we r unable to export avatar + Environment texture as part of .gltf format.

I understand, as per the  link https://docs.blender.org/manual/en/latest/addons/import_export/scene_gltf2.html it supports only ambient occlusion maps Is there any way to convert hdri into occlusion maps. pls suggest

Thanks
vijay

**Comment by javagl** [comment]
I'm not familiar with Blender or the glTF-Blender-IO part. 

Hopefully it's OK to go out on a limb and ping @echadwick-artist and @emackey here: Maybe you have an idea? Otherwise, this will have to be triaged and scheduled as part of the glTF-Blender-IO development process.

**Comment by emackey** [comment]
Hi @myinzack, currently most glTF assets don't contain their own environments (with a few rare exceptions), for a couple of reasons:

- The size of the HDRI would increase the size of a glTF asset substantially.
- Different engines need HDRIs in different (sometimes pre-convoluted) formats for optimal realtime rendering (for example Filament and BabylonJS have both shipped tools for preparing HDRIs in separate ways in the past).
- A given model may move around between environments, and could potentially need multiple HDRIs at different points in the app's lifecycle, which is unknown to glTF.

For these and other reasons, glTF extensions that embed HDRIs directly inside glTF have not seen popularity and support beyond the prototype, proof-of-concept phase.

**Comment by echadwick-artist** [comment]
@myinzack could you please share a visual example of the kind of lighting effect you're trying to achieve?

Ambient occlusion and HDR lighting are two very different lighting effects. If you wish to apply a specific HDR onto the model, you could bake it into a glTF emissiveTexture, however this would be a static effect since it wouldn't change when the model rotates or deforms, and wouldn't affect reflections at all. A baked lightmap only emulates the lighting of completely rough surfaces.

**Comment by myinzack** [comment]
Thanks @echadwick-artist for quick response...
The following is the [HDRI](https://fashion-desings.s3.ap-south-1.amazonaws.com/studiohdri.hdr) lighting we are using as environment texture

we are trying to position avatar into a room with lighting and shadow effect as shown below

![scene](https://github.com/KhronosGroup/glTF-Blender-IO/assets/6347404/cff3f59c-8538-4233-a809-0ce8cdb3d28d)


Any finally we need to render the scene from Babylonjs.

**Comment by emackey** [comment]
Babylon has some nice documentation on how folks can do this:

https://doc.babylonjs.com/features/featuresDeepDive/materials/using/HDREnvironment

**Comment by donmccurdy** [comment]
If the environment is visible (not just a source of lighting) then it's often referred to as a skybox. In this case it looks like you're specifically looking for a _ground-projected_ skybox, so that the character appears to be standing on something solid and can cast a shadow. See:

https://doc.babylonjs.com/features/featuresDeepDive/environment/skybox#ground-projection

As @emackey says though, this most be set up in babylon.js separately from loading the model, the skybox isn't something that can be exported from Blender to any standard file format. 

You could also do something tricky like creating an inverted sphere around the character in Blender, putting an unlit material and texture on that sphere, and then in babylon.js keeping the camera within the sphere. But even in that case, you still need to add the HDRI separately to light the model.
