### ISSUE TITLE
T60268: GLTF export fails with simple bone animation

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#209]
From blender tracker : https://developer.blender.org/T60268

Python error & example blend file are provided in blender issue

**Comment by UX3D-schmithuesen** [comment]
Please attach the used images — without them I can't even get that far.

**Comment by julienduroure** [comment]
@UX3D-schmithuesen Please comment original issue on blender tracker, it will take too much time for me to replicate messages here & on blender tracker

But ... This error is linked to animation, you should be able to reproduce without the texture, by removing material

**Comment by julienduroure** [comment]
@UX3D-schmithuesen 
I don't know how we have to handle it:
- Not exporting entire animation
- Ignore this curve, and export other curves that can be exported on same animation

Any thoughts @donmccurdy ?

**Comment by donmccurdy** [comment]
I think I'd lean toward ignoring this channel but exporting the rest of the animation. If there is some way to report a user-visible warning (per https://github.com/KhronosGroup/glTF-Blender-IO/issues/89) without aborting the export that may be ideal.

**Comment by UX3D-schmithuesen** [comment]
Right now, we display a warning on the console (I don't know if that counts as user-visible) and skip that entire animation, but still export the rest of the asset.
> Ignore this curve, and export other curves that can be exported on same animation
It sounds very good and should not even be that hard to implement, but we don't know if the animation will still be useful in the end. I like skipping the entire animation, because even without seeing the warning, the user will notice right away that the animation was not (correctly) exported while just missing piece of an animation might go unnoticed at first.
