### ISSUE TITLE
Feedback on glTF-Embedded

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#2148]
**Background**

We removed the option to export glTF embedded in Blender 4.0. See [1]

The "embedded" form actually base64-encodes all binary assets onto single lines of text that can stretch millions of characters long. This makes it the least efficient form with the most warnings and caveats upon it.

We received recently some feedback from users that are looking for this option, and asking why it has been removed.

**Feedback and understanding user workflow**

This ticket will centralize user feedback. We'd like to understand why you were using Embedded option, and why this choice was better in your pipeline than glb or glTF (separated).

![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/1696020/d6ab0d37-8576-440c-96e5-5f6978041e6d)

[1]: https://github.com/KhronosGroup/glTF-Blender-IO/issues/2025

**Comment by julienduroure** [comment]
Some link on Blender repository:

https://projects.blender.org/blender/blender-addons/issues/105196

**Comment by julienduroure** [comment]
On social networks:

https://x.com/Nothke/status/1755020386612265459?s=20
https://x.com/star_coffey/status/1753887071754698936?s=20
https://mastodon.gamedev.place/@AminiAllight/111817476448142535

**Comment by julienduroure** [comment]
Copy/Past received email:

>  Hello Julien,
Gltf Exporter in Blender v. 4.0 does not support export_format="GLTF_EMBEDDED" anymore and it creates problem in the program I am developing. I use bpy module as a server in my program and serve data in gltf format to three.js in frontend. 
I want to upgrade my program to Blender v. 4.0 but because of the missing option "GLTF_EMBEDDED" I cannot do that.
What can you recommend me to overcome this problem?
Best regards

**Comment by fire** [comment]
My interest in the embedded format was for a path to using pure json (with base64 encoded binary data) workflow which would be compatible with https://ipld.io/docs/codecs/known/dag-json/ or other [CBOR](https://ipld.io/docs/codecs/known/dag-cbor/) like json encoding.

I have not implemented this or used this in production.

**Comment by iamtommo** [comment]
It's just nicer to embed and have a single human readable file. Embedded with external bin files kind of defeats the purpose.

My opinion is to keep it, it's so little code it can't cost much to maintain?

Worst case hide it behind a toggle or drop-down or something if the preferred option for standard users is bin/embedded+bin.

**Comment by madjin** [comment]
> It's just nicer to embed and have a single human readable file. Embedded with separate bin files kind of defeats the purpose.
> 
> My opinion is to keep it, it's so little code it can't cost much to maintain?
> 
> Worst case hide it behind a toggle or drop-down or something if the preferred option for standard users is bin/embedded+bin.
> 
> Ultimately if it's in the spec it should be supported.

Although I don't use it often I agree here that hiding it behind a toggle or dropdown is more preferable than removing all together. There are uses where having a single human readable file, for example glTF embedded is the way I noticed that The Sandbox Game have all their 8500+ glTF assets stored. I have other datasets, also voxel based, with tile textures that also benefit from this way of encoding textures and make a difference in compression.

**Comment by BlissfulDeluge** [comment]
To add my own commenatry on the .gtlf embedded option.

To give some background, I am a Final Fantasy XIV mod creator, creating cosmetic vfx assets for the game using specialized plugins, and uploading these for other players to use.

While I cannot claim to be an expert, the FFXIV game system is reliant on .gltf embedded rather than the glb/gltf (separate) options. The game simply will not read any other format than .gltf embedded, and so the option, though antiquated, is necessitated by the similarly antiquated design of the game. The game was released back in 2013, which may have been before glb/gltf (separate) became more commonplace. Or the designers might have thought .gltf embedded to be a more familiar option. Regardless of the game designers' reasoning for choosing this option, it is the only one that works for the purposes of creating .avfx files. Non-vfx assets use the more common .fbx, .obj, and .3d formats.

Bringing back the .gltf embedded option will not cause any harm, though if there are concerns about its inefficiency, a better solution might be to add a warning message informing users of the flaws of the option, and recommending using those if the .gltf embedded format is not absolutely necessary such as in niche cases like mine.

**Comment by StarCoffey** [comment]
My usage of the embedded format stems from a construct 3 plugin ([link](https://kindeyegames.itch.io/c3-3dobject-alpha)) that allows for 3d models to be imported and the embedded format works the best with it. Besides that, I also do find it ridiculous that removing an option without any consideration for niche use-cases.

**Comment by PixelPartner** [comment]
The only time(s) I used it was to manually edit the JSON/.glTF for KHR extensions not yet supported by Blender. I guess that's a rare use case.

**Comment by amini-allight** [comment]
This was my preferred option because I have a self-written 3D graphics engine which loads meshes from glTF via a loader I wrote myself. I wrote the loader myself because:

- It was an opportunity to learn glTF
- No glTF loading libraries were in the main package repositories for my system (Arch Linux)
- It seemed easy (and that turned out to be true)
- It would let me get the data in exactly the format I would need to feed to my render pipelines and other systems (e.g. interpreting a specially named object as a collision mesh, interpreting specially named empties as attachment points for child objects)

I chose not to write a loader for .glb because JSON-based formats are almost self-documenting while binary formats require documentation to understand and can be harder to debug issues with. I picked glTF embedded over glTF separate because I wanted a self-contained asset that could be moved/copied/replaced by simply moving one file.

Since the removal of glTF embedded I've written a small program that fuses the .gltf and .bin files back into one whole, replicating the behavior of glTF embedded, and I continue to use the rest of this workflow unchanged.

**Comment by DouglasLapsley** [comment]
I agree with others here.  I would like to see this option because otherwise, I have to use a legacy version of Blender for certain things I do where the only supported file format is GLTF Embedded.

**Comment by julienduroure** [comment]
> for certain things I do where the only supported file format is GLTF Embedded.

Can you be more specific, and details what tools you do use and support only Embedded glTF?
This question is not only for you, but for everyone.
The more specific you are, the more it helps.

Thanks a lot!

**Comment by PixelPartner** [comment]
My problem to solve was this:

I wanted a transparent emissive mesh to glow brightly.
Emission RGB is limited to 0.0 … 1.0, emission strength seems to be ignored by Android SceneViewer and other outdated tools, but with Alpha of 0.1 that dims down to 0.0 … 0.1 in the final AR display
So, I had to manually patch the export. Which is hard for binary .glb.

Could I also use .glTF+.bin+textures?
Sure, but the I’d have to juggle with much more files.

Thomas Kumlehn
***@***.***

**Comment by DouglasLapsley** [comment]
> > for certain things I do where the only supported file format is GLTF Embedded.
> 
> Can you be more specific, and details what tools you do use and support only Embedded glTF? This question is not only for you, but for everyone. The more specific you are, the more it helps.
> 
> Thanks a lot!

Sure.  We've written a Metaverse and AR platform that was written for GLTF Embedded format.  We could refactor it to use GLB, but that would require significant work.  So rather than doing that we will use the legacy version of Blender, but it would be helpful not to have to do that.

**Comment by Exairnous** [comment]
I would like to see the glTF Embedded option returned as well.

I use it to easily debug the JSON in glTF files (e.g. when working with custom extensions) without having to cleanup the mess of additional files exported by glTF Separate or having to process the GLB file into a nicely human readable format.  Could I use the other options, sure, it's possible, but it's much nicer to simply export a single, nicely formatted, human-readable file.

**Comment by DRx3D** [comment]
I see two overriding points here 

1. Single file distribution & management
2. Human readable file especially for debugging

Would it be acceptable if #1 were addressed through some sort of archive file (e.g., ZIP)? It becomes important for some of the current work being done for expanded glTF support for multiple models across several files. This matters for determining how to reference models and their constituent parts, especially those that are shared across several models.

**Comment by fire** [comment]
A ZIP is not in the standardized core gltf2 spec / iso standard, so it cannot be used.

**Comment by patrick-han** [comment]
In favor of embedded for largely reasons already echoed above. 

1. The combination of single file management with some human-readability for debugging is just simpler and cleaner.
2. If it's in the spec, it should be supported.

Hiding it behind another drop-down is perfectly acceptable imo with or without a disclaimer. People who "know what they are doing/want" will be able to get it, and those who want the best default settings can export without a second thought. 🙂 

Sure it's not too difficult to convert between one or the other, but just the same it's a small part of the code base looking at the PR, and costs little to maintain. Removing friction for one group of users has clearly created some for others.

I'm not sure I'm convinced that users not understanding the various tradeoffs between the formats is a real problem here. If someone is not familiar with gltf to begin with, why would they understand enough to 'correctly' choose .glb or the separate .gltf either? And in that case, they would understandably just google what the differences are and understand.

**Comment by Visne** [comment]
I also really like the combination of human-readability for development/debugging purposes with the simplicity of having a single file, and I would really like to see this feature re-added.

**Comment by h8ku** [comment]
GLTF embedded is really useful for webapp stuff. The future is the Internet again please make sure it's still supported.

**Comment by aaronfranke** [comment]
GLTF embedded is my preferred export option because I need 2 things: 1) Ability to save everything as one file and 2) Ability to easily view and edit the JSON in a text editor, such as when working with custom extensions that don't have good tooling yet. GLB gives me only 1, GLTF Separate gives me only 2, but GLTF Embedded gives me both.

**Comment by 3dcinetv** [comment]
Ok, enough comments. Enough proof. This is coming (I'm pretty sure) from most experienced users, so the feedback is given. When is the thread going into "RESOLUTION" (to not remove embedded GLTF?, please let us know. Thanks!

**Comment by julienduroure** [comment]
glTF Embedded will be back on Blender 4.1

It will not be available by default, you will have to enable an option in addon preferences.
That way, people that really want to use it, will be able to, but people that not really know that this is the worse format of the 3, will not be tempted to use it.

**Comment by iamtommo** [comment]
That's great.

But again, it's in the spec. There should be no motive to coerce users to use it in any particular way. Embedded is arguably the MOST useful format and a big reason gltf is successful. Hiding this will continue to confuse hundreds of people. I vote for it to be default-visible.

(Thank you for listening to our feedback and maintaining this)

**Comment by Exairnous** [comment]
@julienduroure Thank you!

**Comment by DouglasLapsley** [comment]
> glTF Embedded will be back on Blender 4.1
> 
> It will not be available by default, you will have to enable an option in addon preferences. That way, people that really want to use it, will be able to, but people that not really know that this is the worse format of the 3, will not be tempted to use it.

Brilliant, thank you very much.  Greatly appreciated.

**Comment by StarCoffey** [comment]
> glTF Embedded will be back on Blender 4.1
> 
> It will not be available by default, you will have to enable an option in addon preferences. That way, people that really want to use it, will be able to, but people that not really know that this is the worse format of the 3, will not be tempted to use it.

I'm glad you're bringing it back, but, I'm sorry what? Why are you making it more complicated than it has to be, just put back the way it was. I don't understand the reasoning why 1, it was removed in the first place, and 2, why you are now hiding it in the preferences menu. I doesn't make any sense dude.

**Comment by Visne** [comment]
I would much prefer some warning text stating why you might not want to use glTF Embedded after its selected than having to find some hidden config setting every time I reinstall Blender on a new system.

**Comment by donmccurdy** [comment]
The purpose of this thread is to collect feedback on use cases for the “glTF Embedded” packaging method, and I don't want to distract from that goal. But there are real problems with “glTF Embedded” (compared to “GLB” and “glTF Separate”, which are fine) for many users of this plugin. The differences are subtle and technical, and it's challenging to explain all of that in the previous tooltip.

Not everyone uses glTF in performance-sensitive ways — if you're not, then I'm sorry for the inconvenience! I've advocated in the past for removing this option, and I still feel that way, but if it's coming back I do feel strongly that clear guard rails are necessary. For many users, this option is a real footgun.

My longer writeup on the problems of “glTF Embedded,” compared to other types of glTF files:

https://www.donmccurdy.com/2024/03/10/data-urls-in-3d-models/

**Comment by Visne** [comment]
It seems to me like it could easily be summarized to "glTF Embedded files use more data and are often less performant when compared to GLB and glTF Separate files".

Not to mention that (as far as I know) almost all other 3D file formats that Blender can export are also not 'GPU-ready' and also use more data than would be necessary if it was stored as binary buffers directly, which would make these formats equally "bad" as glTF Embedded.

**Comment by patrick-han** [comment]
> It seems to me like it could easily be summarized to "glTF Embedded files use more data and are often less performant when compared to GLB and glTF Separate files".
> 
> Not to mention that (as far as I know) almost all other 3D file formats that Blender can export are also not "GPU-ready" and also use more data than would be necessary if it was stored as binary buffers directly, which would make these formats equally "bad" as glTF Embedded.

Agreed. If the goal is steering developers/artists who don't know any better, I'm not sure why a short disclaimer like what Visne suggested would be insufficient. I don't think you need a complex write up to convey the idea that a particular format should only be used by someone who knows exactly what they want/are doing. 

For someone who is busy and just wants to know which format to use (or not to, in this case), this hypothetical tooltip is more than enough.

I don't feel as strongly about the decision to place new barriers around this option, but I do think the reasoning used to come to that conclusion is a bit misguided.

Thanks again for putting it back!

**Comment by aaronfranke** [comment]
I will use this option myself, but I think that the points @donmccurdy brings up are perfectly valid. If people are misusing this feature in real-world situations, it makes sense to put up some kind of barrier to access it.

My own use-case is with debugging and developing GLTF extensions by viewing and modifying the data manually, and wanting a self-contained package for easily uploading as one file. This is not the "normal" or "recommended" workflow for users just trying to use the format, and as the extension ecosystem gets more fleshed out with more extensions and more support for those extensions in popular software, the need to do this will also decrease over time. For this use case, which I believe a smaller percentage of users will need over time, it is fine to dig into a some settings menu to enable the feature if it helps avoid footguns for new users.

**Comment by PixelPartner** [comment]
If the validation check for emission would also take Alpha into account, I wouldn't need a hack.Currently all values are clipped at 100% RGB, ignoring Alpha.Am 11.03.2024 um 03:51 schrieb Aaron Franke ***@***.***>:﻿
I will use this option myself, but I think that the points @donmccurdy brings up are perfectly valid. If people are misusing this feature in real-world situations, it makes sense to put up some kind of barrier to access it.
My own use-case is with debugging and developing GLTF extensions by viewing and modifying the data manually, and wanting a self-contained package for easily uploading as one file. This is not the "normal" or "recommended" workflow for users just trying to use the format, and as the extension ecosystem gets more fleshed out with more extensions and more support for those extensions in popular software, the need to do this will also decrease over time. For this use case, which I believe a smaller percentage of users will need over time, it is fine to dig into a some settings menu to enable the feature if it helps avoid footguns for new users.

**Comment by NickR-Git** [comment]
> **Background**
> 
> We removed the option to export glTF embedded in Blender 4.0. See [1](https://github.com/KhronosGroup/glTF-Blender-IO/issues/2025)
> 
> The "embedded" form actually base64-encodes all binary assets onto single lines of text that can stretch millions of characters long. This makes it the least efficient form with the most warnings and caveats upon it.
> 
> We received recently some feedback from users that are looking for this option, and asking why it has been removed.
> 
> **Feedback and understanding user workflow**
> 
> This ticket will centralize user feedback. We'd like to understand why you were using Embedded option, and why this choice was better in your pipeline than glb or glTF (separated).
> 
> ![image](https://private-user-images.githubusercontent.com/1696020/307848423-d6ab0d37-8576-440c-96e5-5f6978041e6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MzA1MTYsIm5iZiI6MTcxMzYzMDIxNiwicGF0aCI6Ii8xNjk2MDIwLzMwNzg0ODQyMy1kNmFiMGQzNy04NTc2LTQ0MGMtOTZlNS01ZjY5NzgwNDFlNmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjBUMTYyMzM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjRmZmViNzdhOTE4ZmMyMmM2OGNlZTJlODNiMGQyMzA4NjkwYWQ5NzJjMDc5ZTBlN2I2NTc4YzU5ZjdhNmMxOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7ixakSaT8tZUclj0hU8wPncwnnvwFItmoQtI99q60K4)

I simply cannot imagine a single valid justification for removing embedded GLTF, given its wide support, regardless of potential performance issues. Blender developers should not be making these decisions in the vacuum they appear to be making them in, without regard towards user's use cases, which, based on this thread, are being assumed vs researched by the development team.

**Comment by EriKWDev** [comment]
Very glad it was re-inroduced. gltf is not a format I intend to use in my shipping application, but damn is it easy in development. Having it all in a single file greatly simplifies the asset pipeline. Sad to see it had to be put behind some weird optional addon thing, but alas.

In our game that is still in development, we really don't care yet that this format is inefficient. We just migrated from OBJ cuz we began needing more types of vertex attributes and converting from the one-file format obj to a multi-file gltf is just not something we care about atm

Once all assets are decided I feel it is obvious that base64 encoded json files are nonsensical to ship, but I don't feel blender should be the decider of that. I mean, you keep COLLADA as the option at the very top of the export list xD please...

**Comment by siliconvoodoo** [comment]
My export plugin based on the gltf export operator stopped working because it couldn't find the GLTF_EMBEDDED enum. It took a bit of googling to end up here. I'm displeased because it's like blender acts like a normalizing authority. I think gltf is normalized at khronos group level, and it should be taken here for changes, in the meantime blender should just implement spec.
That said, gltf embedded is convenient thanks to the "all in one file" asset system, and convenient because it's readable and debuggable. Referring to outside .bins complexifies packaging, and at the level of using GLTF it's usually draft level, where we pass ourselves stuff via slack or other file sharing, even email. Having all in one file is just elegant and less error prone.

**Comment by DouglasLapsley** [comment]
> ![image](https://private-user-images.githubusercontent.com/42039319/332802160-aa6a80b0-922d-4ff5-a835-fbf89d8ed12e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzODI3MjYsIm5iZiI6MTcxNjM4MjQyNiwicGF0aCI6Ii80MjAzOTMxOS8zMzI4MDIxNjAtYWE2YTgwYjAtOTIyZC00ZmY1LWE4MzUtZmJmODlkOGVkMTJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDEyNTM0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhMThhNTQxYjVlZjk1ZDk4ZTFhNzc3MDQ5YjQ2YjNmOWJhYzFmYWNhODhmYmIyYTZhYTFjZDEzYzM1MDlkMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JAFkYbQr9KdTvUww5hIk9QIqm2zR3RxyFr0g8j41xjY) They added a chekbox Allow GLTF Embedded format and now we can export it again!

Excellent.  Thank you :)

**Comment by Caldoric** [comment]
Ngl, removing this capability in the first place was a really stupid move. Glad we have it back, at least, but it would be nice if it was *enabled* by default, instead of defaulting to *disabled.* Seriously, devs, stunts like this are among the first steps down the road of what we end-users like to call "Enshittification Avenue". As such, I recommend y'all take some time to do some major introspection and reflection, and make sure you guys aren't going to try and start tanking Blender in the next 5-10 years (or sooner).

**Comment by Visne** [comment]
"Enshittification" refers to online platforms specifically, and has nothing to do with this. I agree that it should just be enabled by default, as there is no reason to have the warning in the config settings instead of in the export window, but your comment is quite rude to contributors that spend loads of their free time on open source software.
