### ISSUE TITLE
OBJ/GLB doesn't display points cloud correctly, but convert to mesh

### ISSUE THREAD

**Issue by gioxyer** [KhronosGroup/glTF-Blender-IO#2186]
**Describe the bug**
I generate a point clouds and import inside Blender and display as mesh, in particular it doesn't show all the points cloud that represent the final 3D Scenario. Even when doing the translation from OBJ to GLB and import inside websites show same as OBJ initial file.

**To Reproduce**
1. Extract the zip file
2. Open Blender
3. Import OBJ

**Expected behavior**
3D Scenario doesn't appear correctly and half of the 3D scene seems not complete

**Screenshots**
![Dora points cloud](https://github.com/KhronosGroup/glTF-Blender-IO/assets/161426313/f4483721-8d9c-455a-919a-6fb91bd623cd)
![OBJ problem](https://github.com/KhronosGroup/glTF-Blender-IO/assets/161426313/62bd7a50-5c9f-4ac7-95fd-1474368f45cb)

**.blend file/ .gltf (mandatory)**
https://we.tl/t-VgBMB67CH0 (ZIP file with OBJ + textures)
https://we.tl/t-8rVpMx5sxb (.blend file)

**Version**
 - OS: [e.g. Windows 11 Home]
 - Blender Version [e.g. 4.1]

**Additional context**
![mesh_obj](https://github.com/KhronosGroup/glTF-Blender-IO/assets/161426313/a468508b-5601-45f9-ba7a-df86e7663070)

**Comment by julienduroure** [comment]
Hello,
This repository is the glTF I/O project. 
If you want to report bug about OBJ importer, you have to report it on Blender tracker, here: https://projects.blender.org/blender/blender/issues


Closing this ticket, on glTF-Blender-IO, we are not responsible of Obj import.
If I misunderstand something, and your issue is about glTF import, please provide more information, and a .glb or .gltf file to import
