### ISSUE TITLE
Option to export multiple VC

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#2195]
New proposition in this PR #2233 

----------------------------------------
Edit: old proposition here:

From #2094 :

About exporting multiple VC:

- Problem is that COLOR_0 must be applied when present in glTF file, and COLOR_1 can't exist if there is no COLOR_0
 - Proposition : Add an option to force export VC
      - If VC is used in node tree, COLOR_0 is set from the node tree, and all others are from mesh list of VC
      - If no VC is used in node tree, create a fake "all 1.0" COLOR_0, and then export all others from mesh list

**Comment by Invertex** [comment]
A thing to consider here is intended usage of this data. I would argue more often than not, vertex color tends to be used as an easy-to-access and utilize between software custom data channel, than to actually tint model color. So just filling COLOR_0 with 1.0 comes off as wasteful and missing the point.

If I'm exporting my model to Godot or Unity for example, it doesn't matter what the GLTF foundation considers proper usage of COLOR_0, what matters is how I'm expecting the software to _consume_ that data. For all the GLTF people know, the data in COLOR_0 is correct, it might not look great if you did use it as a material tint, but that's my choice, it's still just float values at the end of the day.

So what you're proposing here, as far as I'm seeing it, is fairly wasteful since I believe it will mean our meshes will be imported into engines having both COLOR0 and COLOR1 vertex attribute data, when we only needed one set of data, increasing storage, VRAM and bandwidth usage. 
It complicates workflow for seemingly no reason other than to be overly rigid about a GLTF usage expectation that ultimately does no harm subvert a bit if a person is personally choosing to use the final output in a different way.

Godot and Unity don't even support importing multiple vertex color channels either (not sure about Unreal). So this wouldn't even solve the main workflow issue people have with the recent export change.

The reasonings people like to use vertex color for this are two-fold:

1. The data can easily be painted within Blender and visualized using a similar shader setup to what they use in their external software of choice, allowing for an intuitive and quick workflow.

2. The data is very easy to utilize without having to do any kind of extra tooling to setup usage of "custom attribute" data. You import your model and access the vertex **COLOR** binding in your shader. Simple, easy, efficient.


The only compromising solution I could see here if you're unwilling to budge on this, would be to instead have an option to "Export Vertex Color # as UV Channel #". In fact, this could be a workflow boon for Game Devs since it would allow the intuitive use of Vertex color combined with the wide support for multiple UV channel importing, and ease of access in shaders.

**Comment by bertodelrio256** [comment]
> From #2094 :
> 
> About exporting multiple VC:
> 
> * Problem is that COLOR_0 must be applied when present in glTF file, and COLOR_1 can't exist if there is no COLOR_0
> * Proposition : Add an option to force export VC
>   
>   * If VC is used in node tree, COLOR_0 is set from the node tree, and all others are from mesh list of VC
>   * If no VC is used in node tree, create a fake "all 1.0" COLOR_0, and then export all others from mesh list

there should always be an option to force the VC to export no matter the material config. since this is so debated, I really think there should be "advanced" options for this in the exporter. perhaps a custom prefix or suffix to look for in the VC name. basically, the default behavior should do the GLTF standard and search the nodes like you are saying, BUT their needs to be an option to override that.

**Comment by julienduroure** [comment]
Here is the new proposed solution: #2233

**Comment by julienduroure** [comment]
Merged!
