### ISSUE TITLE
Vertex alpha colors are not exported (Blender 4.1)

### ISSUE THREAD

**Issue by The0Dev** [KhronosGroup/glTF-Blender-IO#2206]
**Describe the bug**
Vertex alpha colors are properly imported and displayed in Blender. However, they are lost after reexporting assets.

**To Reproduce**
1. Import the attached .glb file.
2. Export the scene.
3. Import it back
4. Notice that opaque vertex colors are there but alpha colors were lost.

**Expected behavior**
All vertex colors should be preserved.

**Screenshots**
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/98645239/b6dc31d4-9aea-4859-a7c1-16fb14793148)
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/98645239/e796006b-58e2-459c-b040-dea9e5844a16)

**.blend file/ .gltf (mandatory)**

[vertex_colors_alpha_bug.glb.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/15044535/vertex_colors_alpha_bug.glb.zip)

**Version**
 - OS: Linux
 - Blender Version: 4.1.1

**Additional context**
It seems to work properly in Blender 4.0
I know there was a change to the glTF addon and it does not export vertex colors that are not used in the node graph. However, this is not the case here.

**Comment by scurest** [comment]
This appears to be caused by a copy-paste error.

The code to get the "Color" part of the vertex color looks for a Mix node set to "Color" and "Multiply"

https://github.com/KhronosGroup/glTF-Blender-IO/blob/c8387a6007e6e57cc9a656309efe2d822fd3b9cb/addons/io_scene_gltf2/blender/exp/material/gltf2_blender_search_node_tree.py#L627

Similarly, the code the get the Alpha part looks for a Mix node set to "Float" and "Multiply"

https://github.com/KhronosGroup/glTF-Blender-IO/blob/c8387a6007e6e57cc9a656309efe2d822fd3b9cb/addons/io_scene_gltf2/blender/exp/material/gltf2_blender_search_node_tree.py#L645

But the Mix node only has different `blend_type`s for colors. For floats, it always does pure mixing, it cannot be configured to do multiplication. Multiplication of floats is done with a Math node set to "Multiply" instead.

So this patch should fix it

```diff
diff --git a/addons/io_scene_gltf2/blender/exp/material/gltf2_blender_search_node_tree.py b/addons/io_scene_gltf2/blender/exp/material/gltf2_blender_search_node_tree.py
index 1d9e0a11..8b88358f 100644
--- a/addons/io_scene_gltf2/blender/exp/material/gltf2_blender_search_node_tree.py
+++ b/addons/io_scene_gltf2/blender/exp/material/gltf2_blender_search_node_tree.py
@@ -642,10 +642,10 @@ def get_vertex_color_info(color_socket, alpha_socket, export_settings):
     if alpha_socket is not None and alpha_socket.socket is not None:
         node = previous_node(alpha_socket)
         if node.node is not None:
-            if node.node.type == 'MIX' and node.node.data_type == "FLOAT" and node.node.blend_type == 'MULTIPLY':
-                use_vc, attribute_alpha, use_active = get_attribute_name(NodeSocket(node.node.inputs[2], node.group_path), export_settings)
+            if node.node.type == 'MATH' and node.node.operation == 'MULTIPLY':
+                use_vc, attribute_alpha, use_active = get_attribute_name(NodeSocket(node.node.inputs[0], node.group_path), export_settings)
                 if use_vc is False:
-                    use_vc, attribute_alpha, use_active = get_attribute_name(NodeSocket(node.node.inputs[3], node.group_path), export_settings)
+                    use_vc, attribute_alpha, use_active = get_attribute_name(NodeSocket(node.node.inputs[1], node.group_path), export_settings)
                 if use_vc is True and use_active is True:
                     attribute_alpha_type = "active"
                 elif use_vc is True and use_active is None and attribute_alpha is not None:
```

Note that alpha is also lost when there is alpha factor (#2110).

**Comment by julienduroure** [comment]
Confirmed
