### ISSUE TITLE
Importer: Replace dictionaries with arrays and only use the json containers

### ISSUE THREAD

**Issue by UX3D-nopper** [KhronosGroup/glTF-Blender-IO#23]
At the moment, we do have the data duplicated.

From our point of view, the additional dictionaries are not required. Instead - if really the indices are required - we should add accessors, which do calculate these.

**Comment by julienduroure** [comment]
Not sure to understand exactly what data are duplicated. Most of data are here mutable because there are objects, so assignment is done by reference, not by copy. Maybe I didn't understand what you mean (and/or maybe I did something wrong).

Currently data are read recursively (from parent to children), so dictionaries (at root level), may not be filled/read in index order.

**Comment by julienduroure** [comment]
Ok, will have a look on it. 

My first try give me an error:

> f_ = open("/path/to/gltf.gltf")
> data = f_.read()
> json_dict = json.loads(data)
> gltf_from_dict(json_dict)

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "io/com/gltf2_io.py", line 1164, in gltf_from_dict
>     return Gltf.from_dict(s)
>   File "io/com/gltf2_io.py", line 1108, in from_dict
>     accessors = from_union([lambda x: from_list(Accessor.from_dict, x), from_none], obj.get("accessors"))
>   File "io/com/gltf2_io.py", line 21, in from_union
>     assert False
> AssertionError

**Comment by UX3D-nopper** [comment]
But the references to the elements - and the storage of the data - are exactly the one from glTF.
Thanks a lot that u adapt the code!

**Comment by UX3D-nopper** [comment]
Got it.
Goal is to get things working until end of October.
We can still refactor afterwards :-)

**Comment by julienduroure** [comment]
Merge is now done into master!
