### ISSUE TITLE
gltf exporter: unwanted split of a large mesh

### ISSUE THREAD

**Issue by SpaceIm** [KhronosGroup/glTF-Blender-IO#233]
In Blender 2.8 Beta, I've imported Stanford dragon and exported it in ".gltf + bin" format. In the generated gltf file, geometry is split in multiple "primitive objects" such that indices are **unsigned short**, instead of keeping only one "primitive object" using **unsigned int** indices.

**Comment by SurlyBird** [comment]
Has any progress been made on this issue? I still notice very large combined meshes getting split into multiple smaller meshes after exporting to .glb.

**Comment by justtobeyourman** [comment]
I also met this problem, how should solve excuse me?

**Comment by scurest** [comment]
It looks like the fix could be as simple as changing this

https://github.com/KhronosGroup/glTF-Blender-IO/blob/2fb64552718638d8d4a1b80ebd6f82c9d4b293fc/addons/io_scene_gltf2/blender/exp/gltf2_blender_extract.py#L1035

to `4294967295`?

**Comment by emackey** [comment]
Just for some history here: 

* glTF indicies come in 16-bit and 32-bit unsigned integer forms (and 8-bit, but 8-bit was deprecated on account of being mostly useless and unsupported in various graphics APIs).
* The highest integer for a given number of bits (ie, 65535 for 16-bit) is disallowed due to "primitive restart" values used by various graphics APIs.
* This exporter previously would ask the artist whether they prefer 16 or 32 bits, with a combo box on the UI.  Artists generally didn't like being asked such questions, so the UI for this was removed.
* The intention behind removing the UI was originally to have Blender auto-select 16 or 32 bits per primitive, based on number of verts needed.  But, this logic was never written, so the choice of 16-bit became hard-coded.
* If artists chose 16-bit for a mesh with more than 65k verts, there was some protective code that would split the mesh into parts, to keep the vertex count below the limit.  This code is still in use today, and affects all large meshes.

Ideally, we should get rid of the mesh-splitting code, and have the exporter intelligently auto-select 16 or 32 bits.  This would be based not on the number of vertices in Blender, but the actual number of vertices about to be exported to glTF for a given mesh/primitive.

**Comment by scurest** [comment]
The exporter does auto-select

**Comment by emackey** [comment]
Hmm, I haven't done any 32-bit sized meshes in a long time, maybe this is working already?

I don't know if Blender supports more than 2**32 verts, would the splitting code be useful there at all?  Seems like the memory might run out.  But I haven't tested large meshes in a while.

**Comment by scurest** [comment]
It looks like (from the bmesh source code) Blender can handle no more than 2\*\*31 verts in a mesh and maybe less. A primitive can have more verts than that because of splitting (eg. when a vert is on a UV seam, etc.) though.

Exporting seem to work fine for me without the splitting code for both index sizes. I'll do a PR and see if the tests pass.

**Comment by donmccurdy** [comment]
Just to make sure this is mentioned, uint32 indices are unsupported in the core WebGL 1.0 spec, per https://github.com/KhronosGroup/glTF/issues/570.  This requires `OES_element_index_uint`. But support for that extension is pretty good these days, [98% of devices](https://webglstats.com/webgl/extension/OES_element_index_uint), so I'm not particularly concerned with removing the splitting logic in this exporter.

**Comment by donmccurdy** [comment]
^More specifically, the spec _allows_ uint32 indices, so applications that need to support the remaining 2% of devices should be prepared to split primitives themselves at runtime or to preprocess the mesh some other way.

**Comment by emackey** [comment]
@donmccurdy Just to be clear, this removal of code doesn't appear to change what the exporter is currently doing in master.  It was already auto-upgrading to UINT, in spite of my misunderstanding.  So this is basically a removal of dead code.
