### ISSUE TITLE
Importing glTF with named animations sometimes creates an extra active action

### ISSUE THREAD

**Issue by Phrogz** [KhronosGroup/glTF-Blender-IO#2341]
**Describe the bug**
Exporting a file with _N_ named NLA Tracks, and then re-importing that glTF, sometimes results in a project with _N_ named NLA Tracks and an extra action that is not pushed down on the NLA Editor.

**To Reproduce**
1. Open the attached .blend file.
   * _There are two nodes, one with 3 actions, one with 2 actions; all actions are toggled off._  
      <img width="1332" alt="image" src="https://github.com/user-attachments/assets/951add62-a334-498a-bad3-f7d34d1d0c84">
2. Export to glTF with Animation mode set to `Actions`, and Animation Sampling disabled.
   * _A glTF with the result is also attached._
3. Create a new project.
4. Import the glTF.
5. Open the NLA Editor
   * **Note: there is an extra non-pushed-down track named `CubeSlideX_MyCubeNode`.**  
      <img width="959" alt="image" src="https://github.com/user-attachments/assets/39661e35-b75d-4f11-b852-2a47d24547ee">

**Expected behavior**
No extra action should be created or active after import. Only tracks named for the animations in the glTF should be created.

Note that if you rename `MySphereNode` to `MyASphereNode` and repeat the steps above, the problem does NOT occur. (!)

**.blend file/ .gltf (mandatory)**
[action-test.zip](https://github.com/user-attachments/files/16843058/action-test.zip)

**Version**
 - macOS 14.5
 - Blender v4.2.0 2024-07-16
 - glTF add-on version 4.2.57

**Additional context**
I've seen this same result in 4.1 on Linux as well.

**Comment by Phrogz** [comment]
Beyond leaving extra junk in the scene that should not exist, this is an amusingly-annoying problem for me as I'm developing a glTF extension that works on the `Visible in Viewport` attribute. The junk action that comes in during my development sometimes leaves a keyframe active that hides the active object, making it especially confusing as to what's happening.

**Comment by julienduroure** [comment]
Hello,
There is only 5 actions created at import.

![image](https://github.com/user-attachments/assets/270adf7b-3cbf-438d-a980-50f478e2f90f)



All actions are named with name of the object as suffix, because in Blender, each action can be linked with only 1 object. This is not the case in glTF, where an animation can be linked to multiple object.
So we have to add suffix to avoid name duplication. (Even if in your case, the animation is link to a single object).
In NLA, the track is name the same as the glTF animation, as the track is link to a given object.
But the animation and the strip in the track will have the suffix.

![image](https://github.com/user-attachments/assets/bac9ff3e-5156-4c03-a133-0a47adec2e14)


The header line is the active action, not a 6th action. Please check the Blender documentation of the NLA if you need to understand how it works.

![image](https://github.com/user-attachments/assets/0534b2d4-84f3-4111-8d3f-34bbd6cad836)

Closing this ticket, no bug here


PS: Note that the behavior will change will Baklava project.

**Comment by Phrogz** [comment]
I'm frustrated that I wasted your time with another mistaken bug report. My apologies. I see now that you are right, that it's not an extra action, it's the same action made active.

I still do not think that any objects should have a particular action made active, especially not a subset of them. (In my example, why would we expect `MyCubeNode` to get an action made active, but MySphereNode to not get one?) I'm glad that this will change in Baklava.

I understand about the unique naming requirements. I don't expect the action and strip names to roundtrip through glTF.
