### ISSUE TITLE
Blender does not export the roughness map, instead it sets the metallic or roughness value to 1 if not both used

### ISSUE THREAD

**Issue by Linko-3D** [KhronosGroup/glTF-Blender-IO#240]
When I connect an image to the Metallic or Roughness input of the Principled shader, the image isn't exported, instead it just sets the value where it was connected to 1. But if I connect the image to the Metallic and Roughness slot the image is exported and a Separate RGBA node is added before it's connected to the Principled inputs.

Test file:
[roughness bug.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2779401/roughness.bug.zip)

**Comment by emackey** [comment]
There do seem to be some lingering bugs here.  The attached blend file doesn't include a roughness map, but when I added a grayscale one, it looked to me like the map got exported as grayscale, not placed into the green channel as glTF requires.

@Linko-3D for some background info, the glTF format does not contain any nodes.  It contains base color, normal map, emissive map, and a special texture I've taken to informally calling the ORM texture.  The ORM has baked ambient occlusion optionally in the Red channel, Roughness in the green channel, and Metalness in the blue channel.

Currently this addon doesn't support the ambient occlusion channel (yet), but it will handle the metallic and roughness channels by using Blender's "Separate RGB" node to split out two of the ORM channel assignments and connect them to Blender's Principled BSDF node.  So anytime you import a metal/rough glTF into Blender, you'll see this node show up.

I believe the plan for the exporter calls for it to accept grayscale, separate inputs to Roughness and Metallic, and combine them into a green+blue image with those two channels.  But if this isn't working, one option is to manually create the SeparateRGB node yourself, and use an image that's been encoded following the ORM convention.

**Comment by Linko-3D** [comment]
I have seen that it is mandatory to use both the Metallic and Roughness slots. If I only use the Roughness or Metallic slot, the file exported doesn't include the texture, it just sets the value to 1.

Here it works:

![works](https://user-images.githubusercontent.com/30020215/51534304-b6cd5f00-1e45-11e9-9605-1b16859197d5.png)

Here it will set the roughness to 1 without the texture exported:

![roughness not working](https://user-images.githubusercontent.com/30020215/51534316-c8af0200-1e45-11e9-8ebb-c08902fe0a99.png)

**Comment by UX3D-nopper** [comment]
It's a bug. Just verfied it. We will have a look at it.

**Comment by UX3D-schmithuesen** [comment]
This is more than exporting a texture. We would have to generate a new texture containing the roughness map **and the metallic map** (which would be the same number over and over). That's because glTF does not know a roughness map or metallic map – it just knows the [metallicRoughnessTexture](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#pbrmetallicroughnessmetallicroughnesstexture) (referred to as “ORM texture” by @emackey in the other comment).

> I believe the plan for the exporter calls for it to accept grayscale, separate inputs to Roughness and Metallic, and combine them into a green+blue image with those two channels.

This sounds like a good plan to me to start with, because accepting grayscale and creating the ORM texture is also the first step toward a solution of @Linko-3D s problem. Next step would be to automatically fill the other channel with a constant if nothing is connected.

**Comment by SurlyBird** [comment]
Chiming in on this to ask about AO (the red channel in the ORM map) and Blender's Principled BSDF. My current workflow is to pipe in the metallic and the roughness maps I get from, say, 3DCoat into the Principled BSDF and to let the exporter pack the texture. Since there is no obvious slot to pipe in an AO map in the Principled BSDF, the AO does not get packed (which did happen, I believe with the  bundled glTF Metallic Roughness shader). I really like having the Principled BSDF as the default material in 2.8, but do miss the AO slot.

I can, of course, manually add the AO into the red channel in Photoshop, but having the option to build the ORM completely in Blender would be ideal, naturally. For give this naïve question: I was curious if there was a plan to handle AO at export with glTF-Blender-IO? Is this practical/possible with Blender's Principled BSDF (like maybe using another slot - Specular, for instance, as a substitute for AO?

Sorry if this has already been answered and I missed the reply. Or if I'm missing something else terribly obvious.

**Comment by emackey** [comment]
@SurlyBird That topic is under discussion in #123.  Good to have another voice pointing out the strong need for AO.

**Comment by SurlyBird** [comment]
OK. Great! Thank you for pointing me in that direction!

**Comment by maepopi** [comment]
Hello all! I strongly agree with the need of AO, since neither with the previous plugins (Blender GLTF importer and exporter) nor with the Blender IO nor again with Blender 2.8 have I succeeded in exporting the AO with the object! I have tried many things, among them mixing the diffuse and the AO with a mix RGB and plugging them into the Diffuse slot of the Principled BSDF, but there only the diffuse gets encoded. whereas if I plug the AO map into the diffuse, it gets exported as a diffuse. XD

For now the only truly successful means I have found is to multiply the diffuse and AO under photoshop...

I'll go have a look at emackey's link too!

**Comment by donmccurdy** [comment]
I'm marking this issue as a bug, rather than an enhancement – while it's arguably an enhancement _to the code_ to support dynamically generating the combined texture, from a user's perspective the texture packing style of glTF is not necessary information, and it's a bug when a roughness map connected to the Principled node is ignored.

For AO see #123.

**Comment by aleksijuvani** [comment]
I think I just ran into this as well. If a mesh has a roughness map but no metallic map, the roughness map is not exported because the exporter does not generate the metallicRoughnessTexture. I would expect the color channel for the missing map to be filled with a constant value.
