### ISSUE TITLE
Export world settings

### ISSUE THREAD

**Issue by donalffons** [KhronosGroup/glTF-Blender-IO#25]
Hi and first of all: thanks for your great work on the GLTF standard and on this addon in particular. You're doing a fantastic job :).

Now my question / feature request: It would be great if you could somehow export the world settings / node tree of a scene and especially support HDR lighting. By chance, do you know [Verge3D](https://www.soft8soft.com/verge3d/)? I am think they are using big parts of your code in their product, but are having some pretty good enhancements, like exporting the mentioned world settings.

Cheers
-Sebastian

**Comment by donmccurdy** [comment]
Hi @donalffons — most of the world settings cannot practically be exported as part of a model ("raytrace" and "indirect lighting" are clear examples) because they don't have analogs that are consistently implemented across engines. For that reason, the glTF format doesn't have features for Blender-specific things that aren't very portable. Verge3D is able to do many of these enhancements because they define the rendering engine themselves, and only support a few exporters whereas glTF tries to support many engines and many DCC tools.

HDR lighting is a definite exception — we plan to make it possible to export that once glTF adds the feature. You can follow along at https://github.com/KhronosGroup/glTF/issues/946 for updates on that, but for now I will close this issue.
