### ISSUE TITLE
Exported GLTF model looks different when imported in Three.js

### ISSUE THREAD

**Issue by dodox87** [KhronosGroup/glTF-Blender-IO#264]
I have this terrain in Blender, with differents materials all setted as Principles BSDF, that looks like this. 
<img width="510" alt="blender-ss" src="https://user-images.githubusercontent.com/12169627/51903581-d2dc7d80-23bc-11e9-9fae-1dc6ce8b6776.PNG">
<img width="192" alt="cattura" src="https://user-images.githubusercontent.com/12169627/51903699-23ec7180-23bd-11e9-99c3-21470ece8c8d.PNG">
But when i import it into my three.js project looks polished and even the colors are distorted as you can see here (threejs material class is MeshStandardMaterial).
<img width="412" alt="cattura2" src="https://user-images.githubusercontent.com/12169627/51903858-804f9100-23bd-11e9-88b4-4f1584bed821.PNG">
If i use diffuse BSDF material in the model then after the export i get all materials with rgb 111 color (a kind of black):
<img width="628" alt="cattura3" src="https://user-images.githubusercontent.com/12169627/51904987-5d72ac00-23c0-11e9-9c74-766cbf588db3.PNG">
I am not very experienced in blender and i am asking myself if its a problem with the exporter or is me missing some settings. Every help will be very appreciated. Thank you.

**Comment by dodox87** [comment]
Principled BSDF
[firstterrain_principled.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2813222/firstterrain_principled.zip)

Diffuse BSDF
[firstterrain_diffuse.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2813224/firstterrain_diffuse.zip)

**Comment by donmccurdy** [comment]
Thanks @dodox87! Likely same issue as https://github.com/KhronosGroup/glTF-Blender-IO/issues/261 and https://github.com/KhronosGroup/glTF-Blender-IO/issues/127.

**Comment by donmccurdy** [comment]
This exporter supports Principled BSDF, but currently not Diffuse BSDF. We'll look into the coloration issue.

**Comment by UX3D-schmithuesen** [comment]
I noticed that your terrain has a negative scale on all axes – this also means that your normals are flipped so the first thing I did was flip them back. Also, I set the roughness of all materials from 0 to 1 because a material with no roughness **should** look polished. Below the result, I documented the normal flipping since you mentioned that you are unfamiliar with Blender (2.80).

**Result (rendered with [Don McCurdy's viewer](https://gltf-viewer.donmccurdy.com/)):**
![result](https://user-images.githubusercontent.com/44766936/52001403-9c3b5b80-24bf-11e9-8d2e-df2415b8b869.jpg)

**How to check the normals (red is the back of a face):**
![faceorientation](https://user-images.githubusercontent.com/44766936/52001382-8d54a900-24bf-11e9-9651-4ad16fcdc88c.jpg)

**How to flip all normals:**
![selectall](https://user-images.githubusercontent.com/44766936/52001392-93e32080-24bf-11e9-8f40-c5187c1b5310.jpg)
![flipnormals](https://user-images.githubusercontent.com/44766936/52001396-96de1100-24bf-11e9-9426-a4b297a7d92f.jpg)

**Comment by dodox87** [comment]
Thank you very much. Now the model looks perfect.
