### ISSUE TITLE
Maps exported as RGBA and waste a lot of space

### ISSUE THREAD

**Issue by qwiglydee** [KhronosGroup/glTF-Blender-IO#278]
MetallicRoughness map has 2 channels but exported with 4. Wasting 50% instead of possible 30%
Normal map has 3 channels but exported with 4. Wasting 25%.

**Comment by donmccurdy** [comment]
@qwiglydee what format are your original textures? This exporter should try to preserve the input textures, rather than converting to something else. If it's not doing that, we should fix it, but we'd like to avoid converting lossless PNGs to lossy JPEGs, and leave that to other optimization tools.

Also note – it's common to use PNG instead of JPEG for normal maps, lossy compression will often cause artifacts there. The size differences between JPEG and PNG are not as simple as the number of channels involved, there are cases where PNG may be smaller – e.g. textures with mostly solid colors.

**Comment by qwiglydee** [comment]
I'm talking about number of channels, not format.
However, seems like I panic too much.
Here are results of a pure experiment:
```
original/color.png: PNG image data, 1024 x 1024, 8-bit/color RGB, non-interlaced
original/metallic.png: PNG image data, 1024 x 1024, 8-bit grayscale, non-interlaced
original/roughness.png: PNG image data, 1024 x 1024, 8-bit grayscale, non-interlaced
original/normal.png: PNG image data, 1024 x 1024, 8-bit/color RGB, non-interlaced
1460k total

gltf/color.png: PNG image data, 1024 x 1024, 8-bit/color RGB, non-interlaced
gltf/metallicroughness.png: PNG image data, 1024 x 1024, 8-bit/color RGBA, non-interlaced
gltf/normal.png: PNG image data, 1024 x 1024, 8-bit/color RGB, non-interlaced
1616k total
```

The metallicroughness image has 4 channels and 2 of them unused.
However, the unused channels have only 1 bit depth.
```
  Type: TrueColorAlpha
  Endianess: Undefined
  Colorspace: sRGB
  Depth: 8-bit
  Channel depth:
    red: 1-bit
    green: 8-bit
    blue: 8-bit
    alpha: 1-bit
```

Nothing much to worry about, though.
