### ISSUE TITLE
Import: all instances of the same mesh share the same morph weights

### ISSUE THREAD

**Issue by scurest** [KhronosGroup/glTF-Blender-IO#290]
For example, only one cube should be animated in this example: [MorphCube.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2848792/MorphCube.zip)

This is caused by the fact that morph weights are per mesh instance in glTF, but there is one shape key per mesh (not per mesh instance) in Blender. I solved this by duplicating the mesh.

**Comment by julienduroure** [comment]
I confirm.
We have to detect if some nodes are animated in order to know if we have to instance the mesh or create a new one

**Comment by scurest** [comment]
IMO you should always create a new one, because the user can always change the weights by hand, so they would still experience "false sharing" of unanimated instances.

**Comment by julienduroure** [comment]
I'm not agreed with that.
I know that there is no perfect import in that case because animation is at node level in glTF, and at mesh level in Blender, but it's really important to keep mesh instancing for performance. 

If user want to change weights by hand in a specific object, he can easily make a single-user copy of the mesh.
I think we have to be as close as possible to the glTF file, so keeping mesh instancing everytime we can

**Comment by scurest** [comment]
Okay. Also of course, even unanimated instances can have different weights just because their nodes have different `"weights"` properties.

**Comment by julienduroure** [comment]
Yes, of course in this case we need to create a new mesh

**Comment by julienduroure** [comment]
"weights" at node level is not implemented in importer for now. In this issue, I will solve animation issue only.
I will create a new issue to manage weights at node level
