### ISSUE TITLE
Can't export custom normals (use_auto_smooth)

### ISSUE THREAD

**Issue by sketchpunk** [KhronosGroup/glTF-Blender-IO#309]
I'm using two addons to manually change the normals for my model. When I export, it doesn't get saved out. Is the exported checking if auto smooth is turned on and that the custom data is there being used?

Data should be stored in "Custom Split Normals Data" datablock. 

I can upload a sample file if you need it.

**Comment by j-conrad** [comment]
I think this is related to this issue-- looking for a good place to report this.
It appears to be a known issue that one cannot export a model that has manually-defined smooth/hard edges unless 'Apply Modifiers' is turned on. (Doesn't make much sense considering defining smooth/hard edges can be done without the use of any modifiers, but 🤷‍♂️)
The problem I'm having now is that I'd like to be able to export my Shape Keys AND have proper smooth/hard edges. However, Shape Keys don't export when 'Apply Modifiers' is turned on, aka the opposite problem. (Also a bit of a misnomer since Shape Keys appear to have zero to do with modifiers.)
Does anyone know how to get around this?

**Comment by emackey** [comment]
> one cannot export a model that has manually-defined smooth/hard edges unless 'Apply Modifiers' is turned on

@j-conrad As a workaround you can try, since it might take a while to get this bug fixed, is you could add an "Edge Split" modifier, and manually apply it, prior to export.  Then it won't matter if the "Apply Modifiers" checkbox is set or not.

This is actually what's happening with the addon's own "Apply Modifiers" checkbox, since there's a temporary Edge Split modifier that gets used as part of the export process, and applying it is what gives you the requested hard edges.

See also comments in #230.

**Comment by j-conrad** [comment]
@emackey thanks for the suggestion. Unfortunately, when attempting to apply an Edge Split modifier, Blender throws an error stating that you ‘cannot apply this modifier to an object that has shape keys’. 😣
Seems unreasonable to make people redo all their shape keys AFTER using the modifier which they don’t even want to apply permanently in the first place.
Looks like this problem doesn’t actually have a viable workaround.

**Comment by SteffenDuenner** [comment]
I hope this gets some attention. We're currently in the middle of a project that needs proper user normals / vertex normals to look the way it should.

**Comment by emackey** [comment]
This should be fixed in #414.
