### ISSUE TITLE
Packed JPGs are exported as PNG with filename and mime type JPG

### ISSUE THREAD

**Issue by pjoe** [KhronosGroup/glTF-Blender-IO#311]
When using a .blend file with packed images in JPG format, they are exported as PNG (making them much bigger). Also in this case it looks like the mime-type in the glTF file is `image/jpeg`, which is correct, just the actual exported image files are in PNG (even though their file extension is .jpg).

Example (2.80):
[FuseZombie.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2889398/FuseZombie.zip)

You can use: `File > External Data > Unpack All Into Files` inside blender to get the expected JPGs.

**Comment by UX3D-schmithuesen** [comment]
I've investigated this and my conclusion is that we should get rid of a lot of the image processing code. That stuff is obviously too complex because we wouldn't have weird bugs like this if it weren't. Also I think that I have found a nice solution: Whenever we want to gather an image for the glTF, we **first** unpack it if it is packed. That means that we only need one algorithm that writes the image to the correct location and save us some special cases.

**Comment by emackey** [comment]
@UX3D-schmithuesen We would like to preserve packed data where possible.  Particularly for JPG, which is a lossy compression format, the quality will suffer with every trip through un-pack and re-packing.  Turning JPG data into PNG is particularly bad, as it pairs JPG's low quality with PNG's large size.  It's better to hold onto existing compressed image data wherever possible.

**Comment by UX3D-schmithuesen** [comment]
Blender's unpacking doesn't turn JPG to PNG, it just writes it to the drive. We have to write something to the drive if the user wants the textures to be separated so using Blender's own unpacking method seems much better than using ours which can only write PNG.

**Comment by pjoe** [comment]
Maybe a bit off topic, but the exporter really should also support writing JPG when combining ORM textures. For web use the size/quality trade-off is definitely worth it in most cases.

**Comment by pjoe** [comment]
Isn't there a way to re-use Blenders image IO? E.g. create new temp image in Blender, set content to combined ORM texture, ask Blender to save image as PNG/JPG. (Then delete image when done)

**Comment by donmccurdy** [comment]
I haven't looked at how this is implemented in the this repo yet, but see this code from the old exporter: 

https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/992b493456abba7e4d45d78f24c8b2a48e8a5a85/scripts/addons/io_scene_gltf2/gltf2_create.py#L340-L421

In particular, note the comment on `blender_image.save_render`, and the fact that it unfortunately applies Scene settings like exposure to the texture output (https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/184).

My only strong preference here is that if an image can be left alone, it should be left alone. If the user gives us a PNG that doesn't need to be repacked, we don't repack it. This way, at least, we preserve the option for the user to do their packing and compression in another tool. In general I think that's better than trying to intuit the correct format.

**Comment by pjoe** [comment]
@UX3D-soares: so this will save packed JPGs as JPG?

**Comment by UX3D-schmithuesen** [comment]
No, this just fixes that we incorrectly call them jpg. The handling of packed files is untouched. The problem is that you can't use Blender's unpack functionality without changing the state of your scene (the image will be considered “unpacked” afterwards). We can open an `enhancement` issue to investigate further into this.

**Comment by pjoe** [comment]
Hmm, I would still consider it a bug that the exporter changes the file type (I know PNG is lossless, but often size changes dramatically). How is the PNG saved, by accessing the image data and formatting to PNG in the exporter? I understand that re-encoding to JPG would loose quality but at least having the option would allow the user to make a qualified choice about size/quality. For many web use cases having textures as maybe 150KB JPGs vs. 1.5MB PNGs can make a huge difference.

Anyway, just my 2 cents :)

**Comment by aerialglasgow** [comment]
I couldn't manage to export 'images as planes' in .jpg format in blender, despite selecting the export option as .jpg (always exported as larger .png files). If file size is a real issue for the object I managed to just edit the glTF file in a text editor and rename the .png file as .jpg. Then drag a similarly named .jpg file into the same folder. It works!

**Comment by scurest** [comment]
> I couldn't manage to export 'images as planes' in .jpg format in blender, despite selecting the export option as .jpg (always exported as larger .png files).

@aerialglasgow

That's because "Import Images as Planes" hooks up the alpha socket to handle images with transparency by default. When the glTF exporter sees the alpha socket is used, it thinks the texture will have an alpha channel, so that forces it to use PNG instead of JPEG.

If you turn "Use Alpha" off when you do the "Import Image as Plane" (or manually disconnect the Alpha), the glTF exporter is able to export as a JPEG.

However, it would be nice if the glTF exporter would be slightly smarter about [detecting whether an image needs an alpha channel](https://github.com/KhronosGroup/glTF-Blender-IO/blob/6605ac770ce64e014283a34fe720d75760c40e66/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_image.py#L123-L125) too.

**Comment by aerialglasgow** [comment]
Thanks @scurest Totally, it did dawn on me earlier importing another image, I had missed the 'Use Alpha' checkbox. Yes could be more intuitive on export, thanks for point this out. What an amazing app Blender is. Slowly getting to grips with it.
