### ISSUE TITLE
Import: incorrect material alpha

### ISSUE THREAD

**Issue by scurest** [KhronosGroup/glTF-Blender-IO#355]
The `baseColor` term for metallic-roughness materials is computed with the element-wise product

    baseColor = baseColorTexture * baseColorFactor * COLOR_0

I made a test file with three boxes, red, green, and blue, that each have an alpha value of 0.5. They achieve this with different combinations of textures/factors/vertex colors. Right now they look like this

[TransparentBoxes.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2955609/TransparentBoxes.zip)

![boxes-blender](https://user-images.githubusercontent.com/11024420/54181877-f855b000-446d-11e9-93f7-d93f1a5c26b3.png)

Correct rendering in Babylon.js

![babylon](https://user-images.githubusercontent.com/11024420/54181884-fd1a6400-446d-11e9-9e9b-cda3112d2078.jpeg)

1. **Cube 1 (Red)**

    baseColor = [1, 0, 0, 0.5]

    * No baseColorTexture
    * No vertex color
    * baseColorFactor = [1, 0, 0, 0.5]

2. **Cube 2 (Green)**

    baseColor = [0, 1, 0, 0.5]

    * baseColorTexture is a 1x1 white PNG (no alpha)
    * No vertex color
    * baseColorFactor = [0, 1, 0, 0.5]

3. **Cube 3 (Blue)**

    baseColor = [0, 0, 1, 0.5]

    * No baseColorTexture
    * Vertex color = [1, 1, 1, 0.5] for all vertices
    * baseColorFactor = [0, 0, 1, 1]

    This one might be hard to fix since AFAICT there isn't a way to get the A out of RGBA vertex colors in a shader node.

(Also cc @donmccurdy: the blue cube is also incorrect in the Three.js viewer.)

**Comment by donmccurdy** [comment]
Three.js doesn't support alpha in vertex colors yet, so the issue with the blue cube there is expected.

> This one might be hard to fix since AFAICT there isn't a way to get the A out of RGBA vertex colors in a shader node.

Hm that's unfortunate. I'm not aware of a way either.

Also note that Blender pretty much ignores the base color alpha value in viewport preview, even though that's what the exporter relies on (as opposed to a Transparent BSDF multiplied in). I'm hopeful that will be fixed in Blender eventually, per https://devtalk.blender.org/t/alpha-opacity-displacement-parallax-and-ao-input-for-the-principled-shader/3096/5?u=donmccurdy.

**Comment by julienduroure** [comment]
For info, current result in 2.80 beta, eevee render : 
![Capture du 2019-03-13 07-18-47](https://user-images.githubusercontent.com/1696020/54257644-46e37700-4560-11e9-9b50-c1285d8f3c3d.png)
