### ISSUE TITLE
What is the license of the polly scene assets?

### ISSUE THREAD

**Issue by DaviesX** [KhronosGroup/glTF-Blender-IO#371]
For both the exported glTF files (https://github.com/KhronosGroup/glTF-Blender-Exporter/tree/master/polly) and the original blender files (https://github.com/KhronosGroup/glTF-Blender-Exporter/tree/master/scenes)

**Comment by donmccurdy** [comment]
@UX3D-nopper when skinning issues are resolved and we're able to export the Polly model again, would you be OK with moving the model over to glTF-Blender-IO (or perhaps just the samples repo?) and adding a Creative Commons Attribution 4.0 International License or Creative Commons 1.0 Universal Public Domain Dedication?

**Comment by UX3D-nopper** [comment]
The polly project is included in the old glTF exporter and was part of the delivery. So at this point of time, it is Apache 2.0. Propably not suitable for an asset, so we can change it.

**Comment by DaviesX** [comment]
Thanks @UX3D-nopper

**Comment by vpenades** [comment]
Could it be possible to transfer the Polly model to glTF-Sample-Models ?

**Comment by UX3D-nopper** [comment]
https://github.com/KhronosGroup/glTF-Blender-IO/issues/371#issuecomment-781263165

**Comment by donmccurdy** [comment]
@vpenades This is a good idea. Could you open an issue on glTF-Sample-Models? My understanding is that the `.blend` will need some changes, to use the Principled BSDF material rather than the old custom nodes. In the past there were some problems supporting it, but it looks like re-importing the original `.glb` and then exporting from Blender works correctly, so maybe all of those issues have been fixed...
