### ISSUE TITLE
Roundtrip normals import/export incorrect

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Blender-IO#390]
Reported [on Twitter](https://twitter.com/Spo1ler/status/1111295525343715331):

>  I was trying to import Sponza scene from glTF Sample models repo. The thing that breaks is: if tangents w is used, then imported normals in blender (and re-exported in glTF) are broken like if w was always 1. I can provide screenshots a bit later if you want.

Possibly related to https://github.com/KhronosGroup/glTF-Blender-IO/issues/230 and https://github.com/KhronosGroup/glTF-Blender-IO/issues/309.

**Comment by Spo1ler** [comment]
It was me who submitted this bug. I'll provide a couple of screenshots and more description.
So, what I'm trying to do is put several gltf scenes into one, so I've taken Sponza from  https://github.com/KhronosGroup/glTF-Sample-Models and imported it into Blender 2.80.

After that, I've exported it out and then noticed that normals aren't proper.

Original scene:
<img width="1392" alt="original" src="https://user-images.githubusercontent.com/92574/55221333-43b3e080-521a-11e9-8fee-2944365db687.png">

After export:
<img width="1392" alt="after_export" src="https://user-images.githubusercontent.com/92574/55221411-71992500-521a-11e9-9efb-9292fba106ec.png">

It's kinda hard to see, so I've output only the normals (viewspace) from my engine (since I have no idea how to do it in Visual Studio glTF Preview).

Original normals:
<img width="812" alt="good_normals" src="https://user-images.githubusercontent.com/92574/55221459-9392a780-521a-11e9-8ccd-de9d25103c20.png">

Normals after export:
<img width="812" alt="broken_normal" src="https://user-images.githubusercontent.com/92574/55221474-98575b80-521a-11e9-8eb3-5722594c2292.png">


This happens when you ignore tangent w component and don't multiply the bitangent for the tangent-space construction (or if it's always the same sign).

For reference, in Blender after import it looks good: 
<img width="1392" alt="after_import" src="https://user-images.githubusercontent.com/92574/55221487-9ee5d300-521a-11e9-9e3f-9ef7a0d97c5d.png">


And, by the way, importing sponza takes like 5 whole minutes on my laptop, which is kinda strange, because there are plugins for 2.79 that do it almost instantly (but they also don't work that good after importing, so there's that).

**Comment by emackey** [comment]
This might be fixed in #414.

**Comment by julienduroure** [comment]
@Spo1ler Can you confirm this is now solved by #414 ?
I can't see any normal issue after import / export, and visualisation in blender (import again) or https://gltf-viewer.donmccurdy.com/

Closing for now, but don't hesitate to reopen / comment if you still have an issue
