### ISSUE TITLE
Add more tests to CI

### ISSUE THREAD

**Issue by ghost** [KhronosGroup/glTF-Blender-IO#40]
I have just merged some changes into master, adding support for automated CI tests using CircleCI. Until the repository has been officially enabled for CircleCI, [you can have a peek at how this will look like here](https://circleci.com/gh/UX3D-hanselmann/glTF-Blender-IO/2).

You can also run all tests locally using Docker (see DOCKER.txt for instructions).
I have tested this on Windows using Docker Toolbox, but it should work on all other platforms supported by Docker as well (in case you are using Docker Toolbox on Windows, please be aware that you [might have to increase the RAM size of your docker machine in order to build the image](https://github.com/crops/docker-win-mac-docs/wiki/Windows-Instructions-(Docker-Toolbox)#change-default-vm-settings))

The current test cases can be found inside tests/test. Right now, these load a few blender test files, export them as glTF and validate the resulting files using [glTF-Validator](https://github.com/KhronosGroup/glTF-Validator).

The importer can also be controlled from the tests scripts (see tests/test/import_gltf.py), but test cases for this are still missing. It might be a good idea to set up some round-trip tests (import glTF -> export glTF), and then do some sanity checks on the resulting glTF.

**Comment by UX3D-hanselmann** [comment]
CircleCI is now live, and the first test runs are public :)

You can find them here: https://circleci.com/gh/KhronosGroup/glTF-Blender-IO

[![CircleCI](https://circleci.com/gh/KhronosGroup/glTF-Blender-IO.svg?style=svg)](https://circleci.com/gh/KhronosGroup/glTF-Blender-IO)

Right now we are testing the export of some simple blender scenes (found in the tests/scenes), and are then sanity checking the result using the glTF Validator.

I also just added one test case which does a basic round-trip test. It imports a glTF file into an empty blender scene, and then exports the scene as glTF again. The generated glTF file is then validated again, and the resulting "info" properties inside the JSON report generated by the validator are compared against the corresponding values of the source glTF.

This, of course, is still far from being a proper content equality check, but it should be able to catch the most critical structural differences.

@julienduroure Could you put together a short list of sample glTF files from the [sample repository](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0) (or other sources, if that's preferable), so we can add them to the test cases?

**Comment by julienduroure** [comment]
I usually perform my tests on following file:
*  https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/CesiumMan
*  https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Monster
*  https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Avocado
*  https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/BoomBox
*  https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/BoxAnimated
*  https://sketchfab.com/models/8d06874aac5246c59edb4adbe3606e0e
*  https://sketchfab.com/models/7deb2dd552df4bf4bb65005018176647
*  https://sketchfab.com/models/9fea6ffd67b840cb970f5b4570794709

Tell me if you need more examples

**Comment by UX3D-schmithuesen** [comment]
The interesting locations for testing are (as far as I know)
* [tests/test/test.js](../blob/master/tests/test/test.js) which is the one being executed so it's the entry point for all our tests. Currently, it iterates through lots of .blend files and executes the `blenderFileToGltf`, `blenderRoundtripGltf` and `validateGltfFile` methods to determine failures
* [tests/export_gltf.py](../blob/master/tests/export_gltf.py) which wraps the call to `bpy.ops.export_scene.gltf` for exporting
* [tests/roundtrip_gltf.py](../blob/master/tests/roundtrip_gltf.py) which wraps the call to `bpy.ops.import_scene.gltf`, followed by another `bpy.ops.export_scene.gltf`
* [tests/scenes](../blob/master/tests/scenes) which is where the `.blend` files to be tested are located, but if I see that correctly, they still have to be added to an array at the top of [tests/test/test.js](../blob/master/tests/test/test.js) to be used
* [tests/roundtrip](../blob/master/tests/roundtrip) which is where the folders containing `.gltf` files are located – these seem to be parsed and used automatically

`.glb` files might currently not even be tested at all – at least I don't see any in there. This might be a bug in the test script because in the output, it clearly states “blender279b_roundtrip_glb” as a section with lots of results.

**Comment by UX3D-schmithuesen** [comment]
And this is where the results for every push are listed: https://circleci.com/gh/KhronosGroup/glTF-Blender-IO. To have your branch tested remotely, it's enough to just push it because every push on every branch is being tested, not just the open pull requests.

**Comment by donmccurdy** [comment]
This is an indefinitely vague issue — let's close this, and if specific parts of the codebase needs more tests we can open new issues identifying them.
