### ISSUE TITLE
JPEG textures exported as (much larger) PNG textures

### ISSUE THREAD

**Issue by vitorbalbio** [KhronosGroup/glTF-Blender-IO#402]
Hi!
I'm getting huge file sizes exporting glb files from blender 2.8. My scene has a total of 14 textures and each texture is only applied to one single material (Albedo, Normal and ORM per material). My .blend file has all textures attached and saved without the "compress" option is 6.5Mb but when i export it to glb it turns in 26mb!

Exporting the same model and textures from the 3DMax exporter the glb has < 4mb so i can only suppose that there's something really wrong with the glb/gltf exporter on blender. 
Did you guys have some magical tip to me to fix it? I really don't want to open 3d Max only for that.

[Sofá.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3036025/Sofa.zip)

Best Regards.
Vitor

**Comment by SteffenDuenner** [comment]
Just gave your scene a quick try and it seems that the exporter converts all your packed images (which are JPEGs) to PNGs on export. That explains the increase in size. If I export a gltf with separated bin and textures from Blender 2.80 I get textures of almost 24MBs of PNGs. The gltf + bin is around 1.5MB. So that will add up to around 26MBs you're getting.
Theoretically if the texture doesn't have an alpha channel they should be exported as a JPEG, but in your case they're all converted to PNGs and that's what causes the increase in size IMHO.
All your textures looks perfectly fine to me, in Blender they say they're RGB byte which means there's no alpha channel. But nonetheless they're exported as if they were.

On a side note I have to deal with a lot of gltf im- and exporting for a project since 2 weeks now and the whole format is a minefield to me. Every exporter has its own quirks and the Blender exporter eats vertex normals and instances for breakfast which causes a lot of problems for me right now. Maya and Max exporters have different problems and it seems like every app is cooking their own soup (which kind of defeats the idea of a standard to rule them all). :(

**Comment by donmccurdy** [comment]
@UX3D-becher - FYI in https://github.com/KhronosGroup/glTF-Blender-IO/pull/397, some code was deleted that had (originally) been written to solve this issue, ensuring that JPEGs always export as JPEGs. That code was unused since the Blender 2.8 updates, but at some point we will need to restore the behavior.

> Every exporter has its own quirks and the Blender exporter eats vertex normals and instances for breakfast which causes a lot of problems for me right now.

If you could file issues with details and example models that would be very helpful, thanks. Note that this exporter can write smooth or flat normals, but not custom normals, per https://github.com/KhronosGroup/glTF-Blender-IO/issues/230 and https://github.com/KhronosGroup/glTF-Blender-IO/issues/390.

**Comment by donmccurdy** [comment]
Oops, didn't mean to close this.

**Comment by SteffenDuenner** [comment]
> If you could file issues with details and example models that would be very helpful, thanks. Note that this exporter can write smooth or flat normals, but not custom normals, per #230 and #390.

Yeah, sorry. But the issue with the vertex normals has been mentioned in several issues:
https://github.com/KhronosGroup/glTF-Blender-IO/issues/230
https://github.com/KhronosGroup/glTF-Blender-IO/issues/338
https://github.com/KhronosGroup/glTF-Blender-IO/issues/390
https://github.com/KhronosGroup/glTF-Blender-IO/issues/309

I didn't want to spam the forum with another report.

**Comment by donmccurdy** [comment]
I see, thanks. @emackey has summarized the work that needs to be done for custom vertex normals in https://github.com/KhronosGroup/glTF-Blender-IO/issues/230#issuecomment-457785847.

For the original JPEG/PNG issue here, https://github.com/KhronosGroup/glTF-Blender-IO/pull/404 is in progress.

**Comment by SteffenDuenner** [comment]
Thumbs up! :)

**Comment by UX3D-becher** [comment]
#404 is now merged into master
