### ISSUE TITLE
All GLTF models have non-standard default rotation

### ISSUE THREAD

**Issue by EtagiBI** [KhronosGroup/glTF-Blender-IO#452]
**Describe the bug**
When I import any GLTF model, I notice that it has a non-standard default rotation.
![image](https://user-images.githubusercontent.com/20855725/56943855-c8a45980-6b3a-11e9-9254-c70249cae1e4.png)

**To Reproduce**
1. Download sample model
2. Import the model to Blender
3. See Transform tab

**Expected behavior**
Imported models should have a default rotation (like any newly created mesh).

**.blend file/ .gltf**
[Table_01.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3130121/Table_01.zip)

**Comment by emackey** [comment]
I believe this is intentional behavior.  glTF defines the up axis as +Y, and the front axis as +Z.

In Blender, +Z is clearly the up axis, and judging by the "front view" (Numpad 1) we can see that -Y is the front axis.

So when importing a model, a rotation is applied, to flip it right-side-up in Blender space.

**Comment by julienduroure** [comment]
Yes, I confirm that this is intentional behavior to convert from +Yup to +Zup
