### ISSUE TITLE
Roughness map not included when no metallic map is used.

### ISSUE THREAD

**Issue by roxlu** [KhronosGroup/glTF-Blender-IO#497]
**Describe the bug**

When you create a simple Principled BSDF setup with an Albedo, Roughness and Normal map and but no Metallic map, the generated .gltf file is missing the roughness image/material settings. 

**To Reproduce**

1. Create a simple scene with a cube, add Principled BSDF material (see screenshot)
2. Export to GLTF
3. Open the GLTF which is missing the rougness image.

**Expected behavior**

I would expect that a metallic-roughness image would be generated with the metallic channel set to zero. 

**Screenshots**

<img src="https://i.imgur.com/9JlPmWb.png">

**Version**
 - OS: Arch Linux 5.1,4
 - Blender Version 2.8 (2019-05-25)

**Comment by julienduroure** [comment]
Maybe someone will confirm, but I am quite sure this is before ColorRamp node is not supported in exporter.
You have to bake your texture, and use an image texture

**Comment by roxlu** [comment]
Thanks @julienduroure that's exactly the solution that I took. It would be nice if one could omit that step.

**Comment by julienduroure** [comment]
@roxlu glTF specification supports only color or image texture, so baking is a mandatory step. There is no plan for now to include baking into export process, because we don't want to change .blend during export process ("auto baking + auto change of the materiel" to take into account the baked texture will have impact on the .blend file).
