### ISSUE TITLE
Animation not imported correctly

### ISSUE THREAD

**Issue by mikejsavage** [KhronosGroup/glTF-Blender-IO#518]
**Describe the bug**
The attached model loses its animations when imported to blender but works in other viewers

(see also https://github.com/KhronosGroup/glTF-Blender-IO/issues/511)

[bigvic2.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3243735/bigvic2.zip)

**Comment by mikejsavage** [comment]
Nice, thanks for the fast fix!

Loosely related, would it cause problems if the importer didn't rename things? Like the `name = animation.name + "_" + obj.name` line. I was hoping to refer to animations/materials by name in my engine and the renaming makes that difficult

**Comment by julienduroure** [comment]
Hello,

Things can be done, but not 100%. Because in gltf, an action can apply on multiple nodes, than can be on different armatures / meshes, and blender action are different, so action named have to be different.

This will need a bit of refactoring. Priority is currently done on fixing bugs, but at long term, we can improve naming
