### ISSUE TITLE
Winding order is inverted

### ISSUE THREAD

**Issue by Leon-Cantin** [KhronosGroup/glTF-Blender-IO#551]
Maybe I am doing something wrong but I just wrote an importer into my Vulkan engine after exporting a cube from Blender to .glb and I am getting the wrong winding order.

From glTF 2.0 specification: "For triangle primitives, the front face has a counter-clockwise (CCW) winding order."

I checked the memory and the indices do seem to be clockwise. I load them straight up into a Vulkan buffer and defined my winding order as CCW and I get the wrong front face. If I switch the winding order in Vulkan to CW it then works.

Am I doing something wrong with the exporter or does it exports with CW instead of CCW?

I would have expected others to pick up on this issue by now if it really was one, but I can't find any issue about this on the issue tracker.

By the way, many thanks for this plugin, it's going to save me from using FBX. glTF is a bliss so far.

Cheers

**Comment by donmccurdy** [comment]
Could you share an example `.blend`? I'd assume that if it's rendering correctly across several viewers (e.g. http://gltf-viewer.donmccurdy.com/ and http://sandbox.babylonjs.com/) then the bug is not in the exporter, but I haven't looked closely at this.

**Comment by Leon-Cantin** [comment]
Sorry, I think I found the issue. My engine flips the Z axis (depth) since forward increases the depth and backward decreases. If I flip the Y axis in Blender (depth) with a -1 scale and I turn on backface culling, I end up with the wrong face showing in Blender, but it looks fine in my engine. I'll look into a way of flipping it before exporting... or redo everything to flip the Z axis in the engine. 
Thanks for the quick reply!

**Comment by frguthmann** [comment]
> Could you share an example `.blend`? I'd assume that if it's rendering correctly across several viewers (e.g. http://gltf-viewer.donmccurdy.com/ and http://sandbox.babylonjs.com/) then the bug is not in the exporter, but I haven't looked closely at this.
> 
> And thanks, we're glad it's helpful! :)

I just tried a model that has mixed winding order and both ThreeJS and BabylonJS seem to auto-magically solve the problem. Babylon switches WebGL context on the fly and ThreeJS only renders in CW, so I'm assuming it pre-processes the data.

In my custom engine half the model is inside-out because I'm rendering everything in CCW, as described in the spec. This viewer replicates this behavior https://gltf.insimo.com/

The model I'm having problems with was exported with Blender, I can't share it though. I'll eventually try and make one myself to see what happened.

**Comment by donmccurdy** [comment]
threejs doesn't preprocess mesh data, so i'm not sure why you're seeing that result, but glad it's working anyway. :)

**Comment by frguthmann** [comment]
Well I don't know who and I don't know what, but somebody's doing something. Because that's not possible haha. It can actually be harmful in some cases that the reference viewers work with wrongly formed data because people will use them as validation and keep on generating data that doesn't match the spec :/.

I'm pretty sure ThreeJS does something because it renders using CW winding. ( My observations were made using SpectorJS by the way) Maybe it simply converts everything CCW to CW? How does one even detect that some data is CCW?

**Comment by donmccurdy** [comment]
I maintain the glTF loader for three.js, and can assure you we aren't scanning for CW vs CCW triangles - that would be wildly inefficient. We upload the accessor exactly as it comes in. I suspect the exported data is not what you think, but a simple counterexample would be welcome. ;)

**Comment by frguthmann** [comment]
That is definitely possible. If I manage to get one that I can share or to create one myself I'll send it to you.

**Comment by cubeleo** [comment]
I've got a .blend file that is running into a similar if not the same issue with some of my scenes, and I've boiled it down to a scene with two cubes.  I took the default cube, translated it in X, then duplicated it, then scaled the duplicate by -1 in X about the origin.  When I export to glTF and then try and load and render it with my own code, the first cube looks fine but I see the scaled cube's inside faces.  As mentioned above, Don, your viewer renders it fine.  I wonder if it's some aspect of threejs that deals with this.
[TwoCubesOneNegativelyScaled.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/7037592/TwoCubesOneNegativelyScaled.zip)
