### ISSUE TITLE
Export with Draco provide strange message (or error) for compression

### ISSUE THREAD

**Issue by Dok11** [KhronosGroup/glTF-Blender-IO#567]
Look at export parameters, here compression in range 0-6
![image](https://user-images.githubusercontent.com/2697890/60185714-108de700-9833-11e9-8d31-dacfe91a23c3.png)

But in the console window 0-10
![image](https://user-images.githubusercontent.com/2697890/60185863-564aaf80-9833-11e9-9464-9215c066970e.png)

What's happen?

**Version**
 - OS: Win10
 - Blender Version v2.80.74

**Comment by julienduroure** [comment]
@UX3D-nopper Can you please have a look?

**Comment by UX3D-nopper** [comment]
The point is, that higher values are currently not supported in Blender I/O (see tooltip in Blender). So, the console output is correct - as Draco can theoretically do more.
@UX3D-eckerlein and @UX3D-schmithuesen can you give a closer insight on this, but as far as I know either it took too lonk and/or this compression did create artifacts.

**Comment by UX3D-schmithuesen** [comment]
With values 7-10, we encountered broken normals if I recall correctly, but we also noticed that the resulting files were **larger** than with compression levels 5 and 6.
https://github.com/google/draco/issues/504

Since that should not happen with all models though, we might want to investigate the normals issue and enable higher levels (maybe with a hint that 7-10 aren't better than 6 by definition).

**Comment by Dok11** [comment]
Wow, it's interesting. Thak you for describe

**Comment by julienduroure** [comment]
@UX3D-nopper and @UX3D-schmithuesen Any news?

**Comment by UX3D-nopper** [comment]
This should implicitly be fixed and not appear anymore.
@julienduroure Can u please cross check?

**Comment by UX3D-eckerlein** [comment]
Fixed here https://developer.blender.org/D6342.

**Comment by UX3D-nopper** [comment]
Closing, as accepted inside Blender. Should be visible in 2.82. I guess.
