### ISSUE TITLE
Exporter modified the file

### ISSUE THREAD

**Issue by samanthajo2** [KhronosGroup/glTF-Blender-IO#570]
**Describe the bug**

After exporting the Blender says the file has been modified. Exporting should not modify the file.

**To Reproduce**
1. Double click a blend file
2. Pick File->Export->glTF 2.0
3. Export
4. Double click another blend file

**Expected behavior**

The new blend file just loads

Instead Blender complains the current file needs to be saved or work will be lost. This is scary. What is being modified? Why do I have to save again? How can I distinguish between real changes and exporter produced changes?

The .obj  exporter does have this issue for example

**Version**
 - OS: macOS
 - Blender Version 2.79

**Comment by Cyp** [comment]
This may be related to applying modifiers/autosmooth when exporting. At least, I think this started happening around when autosmooth was fixed.

If I understand it right, then while exporting, it does some changes (creating a modifier which corresponds to autosmooth), gets the data to export, and then undoes the changes, but the file is still marked as modified.

**Comment by samanthajo2** [comment]
If nothing actually changes and if Blender has an API to reset the modified flag then would it be good to reset it after exporting so it matches use expectations?

**Comment by Cyp** [comment]
Yes. I'd expect Blender to have some kind of API for that somewhere, but don't know.

**Comment by scurest** [comment]
This looks like it can be fixed by removing `'UNDO'` from here

https://github.com/KhronosGroup/glTF-Blender-IO/blob/fe747dac01939cf3a619d5e62f4bdcd09d7c79ad/addons/io_scene_gltf2/__init__.py#L79

The .obj exporter, for example, only has PRESET. This also makes sense: you can't undo an export.

As a separate issue, we should probably check that the exporter doesn't actually modify anything (anything that does get modified should be protected with a `try`/`finally` that puts it back the way it was).
