### ISSUE TITLE
Export objects as hidden

### ISSUE THREAD

**Issue by donalffons** [KhronosGroup/glTF-Blender-IO#602]
Hi!

It would be great if it would be possible to export objects as hidden. I.e. they are part of the scene graph, but are not shown (until at some point I decide to show them in my application).

It would be best if the render visibility setting would be used to achieve this (i.e. the camera icon, not the eye icon).
![image](https://user-images.githubusercontent.com/33040347/62242559-b3f68c80-b3db-11e9-9e97-51ebea5e3963.png)

I did quite a bit of research and testing on this issue. I don't think this function is currently implemented. If I'm wrong, I would greatly appreciate if someone could point me in the right direction.

**Comment by julienduroure** [comment]
Hello, I'm not sure to really understand what you are looking for. You what to replace some meshes by an empty node in some cases ?
Not sure how we have to handle that. Using render visibility seems to be quite specific, I don't know if this requirement is very common.
Other dev, any thoughts ?

**Comment by donalffons** [comment]
Hi Julien, thanks for catching up on the issue.

Maybe I wasn't clear enough in my description. I would like to be able to export some objects in my scene as invisible by default. In ThreeJS for example, they would import with the "visibility = false" object property.

Here is an example use case of a product customizer: I have a 3D model of an office chair which comes without armrests by default - so they are exported as invisible. In the customizer, the user can enable the armrests, which would simply set the visibility to true.

Hope it's more clear now.

**Comment by julienduroure** [comment]
There is nothing in glTF specification to set the visibility.
What I suggest you is to use custom properties on objects, and read these "extras" datas in json in your importer

**Comment by donmccurdy** [comment]
For example, Blender custom properties will be exported to glTF, and appear in threejs as `object.userData`.

**Comment by donalffons** [comment]
OK, I understand. Thank you both for the hint to use custom properties. And generally, thank you for your great work on this technology :).

**Comment by etc0de** [comment]
Is there any plans to add this to GLTF? I think this would be useful to have. It could be used for invisible barriers and such that are supposed to show up in blender, but invisible ingame. There doesn't seem to be a material to do that, and custom properties are always a bit hackish. Also, a custom property would mean invisible walls (which can be quite essential for many game maps) won't be cross-compatible between engines.

**Comment by donmccurdy** [comment]
@etc0de there are no current plans for this. Depending on your use case and the engine you're loading this model into, exporting with an opacity of 0 may have the intended effect.

To load "invisible walls" as you suggest, you probably want not only to identify that the objects are invisible, but that they are in fact walls. I think identifying the functionality of an object in a game is a good use case for custom properties or object naming conventions — that's why custom properties exist, I don't consider this a hack.

**Comment by etc0de** [comment]
I don't understand the latter half of your response. Why would I want to specifically identify something as walls? Engines commonly just dump the triangle soup into the physics engine as collision mesh, your suggestion seems weird to me since I have never seen walls marked differently in an engine compared to like, anything else, really. Why would anyone want to use custom properties just for basic collision geometry?

@ first half: interesting, I didn't know there was opacity. That sounds useful, is this a material property somewhere?

**Comment by donmccurdy** [comment]
> Why would I want to specifically identify something as walls? Engines commonly just dump the triangle soup into the physics engine as collision mesh....

Wouldn't the collision mesh be identified somehow, to distinguish it from a more detailed scene mesh? That's all I mean, the collision mesh isn't always the same as what the user sees.

If you're using the Principled BSDF node in recent versions of Blender, then the "alpha" socket is the one to adjust for opacity. You'd likely need to choose either Alpha Clip or Alpha Blend mode.
