### ISSUE TITLE
light's range is not getting exported

### ISSUE THREAD

**Issue by aguaviva** [KhronosGroup/glTF-Blender-IO#618]
Apparently this bit it is not implemented as of today. 

```
def __gather_range(blender_lamp, export_settings) -> Optional[float]:
    # TODO: calculate range from
    # https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_lights_punctual#range-property
    return None
```

**Comment by donmccurdy** [comment]
Will be fixed in https://github.com/KhronosGroup/glTF-Blender-IO/pull/662.

Note that this relies on the *Custom Distance* property in Blender, and not *Radius*:

<img width="261" alt="Screen Shot 2019-09-05 at 8 38 11 AM" src="https://user-images.githubusercontent.com/1848368/64357009-aaeb7300-cfb8-11e9-9aeb-19e785c27131.png">

**Comment by slicer4ever** [comment]
Why are you not using the Radius property?

**Comment by donmccurdy** [comment]
The Radius property is not related to the light's range:

![Screen Shot 2019-10-31 at 10 02 12 AM](https://user-images.githubusercontent.com/1848368/67968990-8fba6f80-fbc5-11e9-9aa8-6ab39c440a65.png)

**Comment by etc0de** [comment]
@donmccurdy shouldn't the exported radius be something else than `0` if no custom distance is set? because I think most game engines won't show the light at all with a zero radius, so that default is a bit confusing. are people supposed to always manually set a custom light radius for it to work? why isn't one set by default then?

**Comment by mokiat** [comment]
This is now the case with Blender 3.4. There is no Custom Distance property so light range is not exported. It appears to be replaced by Light Falloff node.

**Comment by julienduroure** [comment]
@mokiat 
The Custom Distance is still there, but only for Eevee engine.
If you want to export the Range property with Cycle, you can switch temporary to Eevee, set the Custom Distance, and back to Cycles.
I will open a new ticket to update documentation about that

**Comment by mokiat** [comment]
@julienduroure , thank you. I searched all night about the missing Custom Distance and did not come across this. I am happy that the property is still there. Hope your reply helps other people as well.
