### ISSUE TITLE
Cannot open GLTFs downloaded from RemixDownloader

### ISSUE THREAD

**Issue by vico93** [KhronosGroup/glTF-Blender-IO#625]
Hi!

I'm currently downloading some models from the soon-defunct Remix3D by Microsoft, using [RemixDownloader](https://github.com/LanceMcCarthy/RemixDownloader) (console version) by @LanceMcCarthy , but every gtlf i open using the built in version included in Blender 2.80 x64 i get a trackback error.

Since i'm new on Blender, if anybody can help me to get the log file to send here for better clarification, i would be thankfully.

**Comment by julienduroure** [comment]
Please follow the bug report guidelines :
- upload an example file
- upload your trackback and / or screenshot of ot.

Without these informations, we can't investigate your issue

**Comment by vico93** [comment]
The model: [Wooly Mammoth.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3528990/Wooly.Mammoth.zip)

The error: ![print](https://user-images.githubusercontent.com/3485505/63497805-f66f2e80-c49a-11e9-8e18-4d40a05c6816.png)

Actually any GLTF downloaded from RemixDownloader causes this error

**Comment by vico93** [comment]
Sorry, the problem is with RemixDownloader (actually this issue: https://github.com/LanceMcCarthy/RemixDownloader/issues/19)

Since its not a blender issue i'm closing it.

**Comment by LanceMcCarthy** [comment]
Hi @vico93, thanks for tagging me. It looks like it should be fixed, I'll post to the original Issue, but to share here for transparency.

The assets and bin are now included next to the GLTF, this was the root cause of some 3D editing programs not being able to open the file

https://csharp.christiannagel.com/2019/08/14/moving-from-the-switch-statement-to-switch-expressions-c-8/
![image](https://user-images.githubusercontent.com/3520532/63551040-1259eb00-c502-11e9-9374-c344287e01e4.png)

**Comment by vico93** [comment]
Thanks @LanceMcCarthy !
