### ISSUE TITLE
Export broken on "RobotExpressive" example.

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Blender-IO#660]
[RobotExpressive.blend 2.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3577470/RobotExpressive.blend.2.zip)

Tested against `master`, https://github.com/KhronosGroup/glTF-Blender-IO/pull/637, and https://github.com/KhronosGroup/glTF-Blender-IO/pull/653. This file worked in the past, but now fails with this error:

![Screen Shot 2019-09-04 at 9 37 30 PM](https://user-images.githubusercontent.com/1848368/64312437-bf018700-cf5c-11e9-961f-fee1db83604e.png)

**Comment by donmccurdy** [comment]
Oof, I was in Blender 2.80, that's probably the issue. I'll update and test this again...

**Comment by donmccurdy** [comment]
Ok, still getting an error in 2.81, but it's a different error:

![Screen Shot 2019-09-04 at 10 05 11 PM](https://user-images.githubusercontent.com/1848368/64313386-53b9b400-cf60-11e9-80af-e153b64c2fdf.png)

I've used default settings, but with *Always Sample Animations* enabled.

**Comment by julienduroure** [comment]
@donmccurdy  Not linked to #637 or #653, because it happen also with only master.
I will add a check about that, but .blend file is quite weird: Robot_death action is linked to robot mesh, there is no sense to do that, because these are path to bone animation ...

Just remove this 'Robot_death" from blender object (see screenshot), and export will work
![image](https://user-images.githubusercontent.com/1696020/64313955-905fcc80-cfad-11e9-9724-8eee1325ff4c.png)

**Comment by donmccurdy** [comment]
I think we may have a regression on this issue – if you open the RobotExpressive.glb model in https://github.com/mrdoob/three.js/tree/dev/examples/models/gltf/RobotExpressive and then re-export from Blender, results are scrambled:

![Screen Shot 2022-12-20 at 10 15 03 AM](https://user-images.githubusercontent.com/1848368/208700630-a70d8fde-2f4b-4cfe-9996-d8cc1d3d52ea.png)

**Comment by julienduroure** [comment]
Confirmed.
I will open a new ticket about it.
Quite strange, because I have a .blend version of the file that can be exported without any issue
