### ISSUE TITLE
Image as Planes using PNG's when exported as .glb leads to a grey plane.

### ISSUE THREAD

**Issue by Fizzelini** [KhronosGroup/glTF-Blender-IO#670]
**Describe the bug**
I'm new to Blender and WebAR and am trying to import png into Blender 2.8 using image as planes, have changed Blend Mode to Alpha Blend. When i export it into a .glb all i get is a grey plane. Any help would be appreciated. Thank you :)
![Screenshot (1130)](https://user-images.githubusercontent.com/53847398/64686535-629dea80-d4bb-11e9-95bb-e6397a741cda.png)
![Screenshot (1133)](https://user-images.githubusercontent.com/53847398/64686657-9711a680-d4bb-11e9-8ac9-9cc2f6e3c5fd.png)
![Screenshot (1131)](https://user-images.githubusercontent.com/53847398/64686536-629dea80-d4bb-11e9-8706-17e127ebf61d.png)

**Comment by julienduroure** [comment]
Hello,

Blender 2.80 Images as Plane creates a node tree that is not supported by glTF exporter. You can find the doc of what is supported for glTF here : https://docs.blender.org/manual/en/latest/addons/io_scene_gltf2.html

But Images as Plane has been updated recently to create a node tree that is compatible with glTF exporter.  
You can find here alpha version of future 2.81 : https://builder.blender.org/download/

--> Your issue is solved in recent blender build
