### ISSUE TITLE
Animations across multiple armatures in 2.8+

### ISSUE THREAD

**Issue by Big-Crab** [KhronosGroup/glTF-Blender-IO#680]
**Describe the bug**
Animations on multiple armatures function absolutely fine in Blender but break when exported as FBX (For reference this is to Unity). Only the actively selected animation in Blender in the Action Editor will end up being exported, the rest seem to be corrupt or missing. This was supposedly fixed in 2.81 for glTF, _but glTF crashes when exporting_.

**To Reproduce**
1. Have an animation that keys bones from more than one armature
2. Ideally, have at least 2 animations that operate on more than one armature
3. Export to FBX, and/or to glTF (Which will likely crash)
4. Import into something that uses said FBX/glTF files, in my case Unity

**Expected behavior**
Previously, with <2.8 versions of Blender, the animations have exported absolutely fine. In Unity, I would see all the animations listed and their respective armatures, as "HandArmature | FireGun" and "GunArmature | FireGun" etc

**Screenshots**
For GLTF Export:
![image](https://user-images.githubusercontent.com/4087236/65334758-fc9c1c00-dbba-11e9-9077-a3796065849a.png)

**.blend file/ .gltf**
[Example file](https://drive.google.com/file/d/1ZP-_7NeJvMqV5Oc4wPdeW1tLnioVcp9N/view?usp=sharing)

**Version**
 - OS: Windows 10
 - Blender Version 2.8 and 2.81 (Was supposed to be fixed in 2.81? Seems to say so in the patchnotes)

**Comment by julienduroure** [comment]
What should be solved now is multiple mesh skinned by a single armature, not the inverse.
Anyway, can confirm the bug in the provided file.
Probably some checks need to be added, because the action is shared between multiple armature, but armature don't have same bone names ... Weird situation, we need to add check to avoid crash

![image](https://user-images.githubusercontent.com/1696020/65345747-3ed55580-dbdb-11e9-8b96-f4f16b992a2d.png)
