### ISSUE TITLE
Sponza import hangs

### ISSUE THREAD

**Issue by aschrein** [KhronosGroup/glTF-Blender-IO#701]
## Issue
Blender 2.8-2 hangs on import. This model is imported correctly with Assimp in my application.

## Configuration
Arch linux(5.2.14-arch2-1-ARCH) 
Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz

[Sponza.zip](https://www.dropbox.com/s/raal3n74n74ekds/Sponza.zip?dl=0)

**Comment by julienduroure** [comment]
Hello,
I'm not sure what version of blender you are using, becase 2.8-2 is not an existing version, but the performance bug is already fixed in current dev version 2.81 alpha.
Please test again with lastest  build here : https://builder.blender.org/download/

And don't hesitate to comment / reopen if you still have an issue
