### ISSUE TITLE
Sharp Edges Ignored

### ISSUE THREAD

**Issue by SurlyBird** [KhronosGroup/glTF-Blender-IO#73]
Exporter ignores manually-assigned hard/sharp edges in Blender 2.8, resulting in an 'all-soft' mesh.

Repro in Blender 2.80 Experimental with glTF-Blender-IO: 

1. Create a cube
1. Display>Shading>Smooth Edges
2. In Edit mode, select all edges. Edge>Edge Data>Mark Sharp
4. Select the Object Data tab, Turn on Auto Smooth and set the angle to 180. 
5. Edges of cube should appear hard/sharp in the viewport.
6. With cube selected File>Export glTF 2.0 (glb). Make sure Export normals and Export Tangents are checked.
7. Write file to disk. 
8. Load file in sandbox.babylonjs.com/
9. Hard edges will not be preserved.

Contrast the same workflow with Blender 2.79 using glTF-Blender-Exporter: Hard edges are preserved in .glb written to disk.

Note: In 2.80, setting Display>Shading>Flat faces does export a .glb with hard edges, but all edges are hard. What we want is the ability to define custom hard/soft edges on any given mesh (like we can do in Blender 2.79 with the glTF-Blender-Exporter addon).

Example files attached.
[cube_hard_soft.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2559855/cube_hard_soft.zip)

**Comment by julienduroure** [comment]
Note that an issue has been opened in developer.blender.org regarding sharp edges management:
https://developer.blender.org/T58638

**Comment by julienduroure** [comment]
User from Blender Issue tracker closed the report, saying : 

> Even this issue seem resolved in the build of 19/01/2019

Someone here can confirm this is solved ???

**Comment by SurlyBird** [comment]
I'll take a look. I have the 20/01/2019 build running right now.

**Comment by Cyp** [comment]
Was probably fixed in 85d2490c7ca97ed2a5aacd3359d8208d3dcb88e7 — auto-smooth used to be ignored.

**Comment by j-conrad** [comment]
Apologies for adding this comment on multiple issues, but I've seen several issues discussing 'Apply Modifiers' as a solution to different problems. Unfortunately, it appears to be a less-than-ideal fix for certain situations like this:

It appears to be a known issue that one cannot export a model that has manually-defined smooth/hard edges unless 'Apply Modifiers' is turned on. (Doesn't make much sense considering defining smooth/hard edges can be done without the use of any modifiers, but 🤷‍♂️)
The problem I'm having now is that I'd like to be able to export my Shape Keys AND have proper smooth/hard edges. However, Shape Keys don't export when 'Apply Modifiers' is turned on, aka the opposite problem. (Also a bit of a misnomer since Shape Keys appear to have zero to do with modifiers.)
Does anyone know how to get around this?

**Comment by pafurijaz** [comment]
I'm the author of thread in blender, here a link of a my model and I get some errors and I can't export. https://drive.google.com/open?id=1RnLZ1OHdxNRgTU9E_jKdSc-1zp5SogkH
Anyway a noticed that, when you export with the script and with option apply modifiers, I get a very clean result, with smooth and sharp edges correctly, but if I do conversion of the model manually and then export the model I have a wrong shading loosing all sharp edges.
