### ISSUE TITLE
Exporter crashes on imported glTF model

### ISSUE THREAD

**Issue by dirkk0** [KhronosGroup/glTF-Blender-IO#748]
**Describe the bug**
I imported a model from Sketchfab into Blender 2.8 and tried to export it; the exporter crashes.

**To Reproduce**
1. Download the model from here:
https://sketchfab.com/3d-models/wr-sales-space-e7051b98e3a749968a0c1497fa6026e4
2. Import into Blender 2.8 (OSX)
3. Export with default settings.
4. Crash (with many glt2_blender_gather_cache.py errors)

**Expected behavior**
The downloaded model works great in A-Frame; my expectation was that I could import a model in Blender and export it again.

**.blend file/ .gltf**
The zip can be obtained from Sketchfab with the link above.

**Version**
 - OS: OSX 10.13.6
 - Blender Version2.80

**Comment by julienduroure** [comment]
Hello,
Can you please test again with 2.81 beta that you can download here : builder.blender.org ?
Thanks

**Comment by dirkk0** [comment]
Sure thing.
Now it doesn't crash but saves forever, and never returns.
Tried it with both glb and gltf+bin.

Selecting just a part of the asset seems to work but results in a near empty file:

    {
        "asset" : {
            "generator" : "Khronos glTF Blender I/O v1.0.4",
            "version" : "2.0"
        },
        "scene" : 0,
        "scenes" : [
            {
                "name" : "Scene"
            }
        ]
    }

Any other suggestions?
Thanks for looking into this.

**Comment by julienduroure** [comment]
I am currently at the blender conference for the entire week, but I will look into it next week.

**Comment by dirkk0** [comment]
Ah great! Have fun, and thanks!

**Comment by julienduroure** [comment]
Hello,
I don't have any issue exporting it.
Are you sure that you didn't check "selection only" option and select nothing it you scene?
I can export it, and reopen in online viewer:
![image](https://user-images.githubusercontent.com/1696020/67701652-9ae88200-f9b0-11e9-8a01-e5b0759caf39.png)

**Comment by dirkk0** [comment]
Ok, then I must be doing very stupid here :/ - could you do me the favour to tell me what it is?
https://youtu.be/U44hZA544As

**Comment by julienduroure** [comment]
Is you exported test.glb file still empty?
Looks like it take some time to export, so it should have exported something, but you cut the video without the end

**Comment by dirkk0** [comment]
... ah ok - that was the problem.

The export took over two minutes; CleanMyMac (wrongly) implied that Blender
froze.
Exporting to FBX, DAE or OBJ takes around 5 seconds, so I followed this
implication.

Great! I don't care how long it takes, as long as it works.
And it does! Thank you very much for your work and your help!

**Comment by ariahiro64** [comment]
i know that this is closed however I'm making n64 models (like literal models that are exported to libdragon) so the poly count shouldn't be the issue. i also found that all of libdragon users are having this issue post 4.0.x. and its not fast64 as people all across the internet are having this issue that don't know what an n64 or fast64 even is.
https://projects.blender.org/blender/blender-addons/issues/98356
https://www.reddit.com/r/blenderhelp/comments/1bc0bmp/glb_export_crash_issue/
https://forum.babylonjs.com/t/blender-crashes-when-exporting-to-glb-cause-of-unoptimized-model-or-weak-pc/6006/7
https://projects.blender.org/blender/blender/issues/83685
https://github.com/KhronosGroup/glTF-Blender-IO/issues/748
https://projects.blender.org/blender/blender/issues/119887

and also i cannot legally send specific files because my files are under nda so i apologize i cant help more.
