### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'key_blocks'

### ISSUE THREAD

**Issue by NathanLovato** [KhronosGroup/glTF-Blender-IO#792]
**Describe the bug**

A Python error shows on export 

**To Reproduce**

1. Download the blend file below
2. Select the `rig` and the `body` objects
3. Export as gltf. Options used (different from defaults): 
    1. Include -> Selected objects
    2. Geometry -> Apply modifiers
4. See the traceback: https://pastebin.com/8cWeqAjz

**Expected behavior**

No error on export

**.blend file/ .gltf**

[mannequiny-0.2.0.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3882867/mannequiny-0.2.0.zip)

**Version**
 - OS: linux
 - Blender Version 2.81

**Additional context**

I was unable to pinpoint the step that triggered the bug. It happened several times today with several versions of this blend file, and the only solution I've found was to revert to a previously saved version.

**Comment by julienduroure** [comment]
Confirmed.

Root cause : You assigned an armature action to a mesh object.
Workaround: Unlink the action from the mesh object. Select the mesh, then on Dopesheet, click the cross button at right of the capture : 
![image](https://user-images.githubusercontent.com/1696020/69491040-e9921a80-0e8f-11ea-9340-212a45e96649.png)

I will add a check to avoid the crash
