### ISSUE TITLE
AO texture influences roughtness

### ISSUE THREAD

**Issue by LorenzWieseke** [KhronosGroup/glTF-Blender-IO#818]
I'm trying to bake AO for my models and export them als GLB's to view in Three.js.

My setup looks like this :

![image](https://user-images.githubusercontent.com/29607121/70273087-b57cfa80-17a9-11ea-97d7-76da6f76ac7a.png)

And it gives me the following result in the GLTF Viewer :

![image](https://user-images.githubusercontent.com/29607121/70273140-ccbbe800-17a9-11ea-90bf-a83f7e0b7647.png)

It seems like the AO Map influences the roughness map somehow, you can see the org. roughtness texture is applied as well. I also tried to use the same map for both textures but just scale one of them but that doesn't work at all, the mapping node is ignored.

![image](https://user-images.githubusercontent.com/29607121/70273397-42c04f00-17aa-11ea-928a-b3cae30435b6.png)

In the file there is another object with ao and normal where everything works fine. On the other hand the normal map is an own texture and ao, metal and roughtness get joined which might be the reason the mapping node solution doesn't work and they all must use the same uv...

Blend File and GLB :

[AO_Test.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3929077/AO_Test.zip)
[ao_map_in_spec.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3929109/ao_map_in_spec.zip)

It would be much appreciated if someone could help me.

**Comment by scurest** [comment]
This is probably because the image is encoded as a JPEG. JPEG artifacts aren't confined to one channel so if there are hard edges causing artifacts in one channel, they will visibly bleed into the others.

![stack](https://user-images.githubusercontent.com/11024420/70276363-c449ba00-1775-11ea-82b0-7d9ed2920821.png)

Try setting the option _Geometry > Images_ to _PNG format (.png)_ when you export and see if it still happens.

**Comment by julienduroure** [comment]
Seems we can close this ticket.
Don't hesitate to comment if you have any info to add.
