### ISSUE TITLE
pbr_node from glTF-Blender-Exporter ambiguity

### ISSUE THREAD

**Issue by tweakoz** [KhronosGroup/glTF-Blender-IO#846]
Regardless of if the new exporter can export principled nodes directly, I'd definitely prefer to use the pbr_node wrapper from the previous exporter repo. It reduces the likelyhood of bad assets being generated - like shaders on rails - and its simpler to debug in other people's assets. I think I have surmised from reading other issues that this wrapper node might still work, that said it's ambiguous. Can we re-import the .blend files (glTF2.blend,  glTF2_Principled.blend) into this repo, and support them? This would remove ambiguity that it is supported and of course synchronize maintenance of the wrapper node with the exporter. Could maybe even add an GLTF-import option to generate the wrapper instead of loose shader nodes for those so inclined.

**Comment by emackey** [comment]
@tweakoz Unfortunately the old wrapper node got partially deprecated, neither removed nor fully supported as first-class.  The Principled BSDF node has first-class support and is [fully documented](https://docs.blender.org/manual/en/2.81/addons/import_export/io_scene_gltf2.html#exported-materials) now.

The old custom node group is still looked for on a fallback path, for when an un-grouped Principled BSDF node is not found, but, in this exporter it's never been 100% feature-complete the way it used to be in the old glTF-Blender-Exporter.  It's there for backwards compatibility; I wouldn't recommend building any production pipeline on it today.

You raise an interesting issue though: How does one validate that a Blender asset's materials conform to something that can be properly exported?  Even using the old custom node group didn't guarantee this, because users had to understand not to connect an image texture node to a factor input for example, or assign a solid color to a texture input.  It might be useful to have a message pop up warning users if they've created some arrangement of nodes that won't correctly convert to a glTF material.

**Comment by tweakoz** [comment]
IMHO it is not just for validation. Its about improving signal to noise ratio and ease of use (for this use case). Just looking at the principled node's vast array of inputs which for this application have no meaning is visually tiresome and misleading and I would definitely argue error prone - Not something I would want to base a production pipeline on. Just being honest

**Comment by donmccurdy** [comment]
> Just looking at the principled node's vast array of inputs which for this application have no meaning is visually tiresome and misleading and I would definitely argue error prone 

Note that many of these are actually on our roadmap... https://github.com/KhronosGroup/glTF-Blender-IO/pull/931 adds clearcoat, for example.

**Comment by donmccurdy** [comment]
>  It's there for backwards compatibility; I wouldn't recommend building any production pipeline on it today.

I think @emackey's comment above remains true, and we do not plan to invest further in custom nodes for this addon, sorry. We do intend to continue adding support for more of the Principled BSDF features as glTF's material system advances.
