### ISSUE TITLE
traceback error when exporting with animation, but without skinning

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#853]
@swift502 I am currently not able to reproduce it (using blend file from #373)
Can you please confirm:
- what blender version you are using
- what addon version you are using
- screenshot of your export options
- your current selection if needed

Thanks !

https://user-images.githubusercontent.com/24359130/71646123-18977980-2ce3-11ea-83a4-3259b0e8e606.png

**Comment by swift502** [comment]
Sure!

- Blender 2.81a (Steam version)
- Addon version 1.0.5
- Settings:
![image](https://user-images.githubusercontent.com/24359130/71779545-5fbd8d00-2fb7-11ea-8d73-8151079c4272.png)
- Selection is unchanged since opening [the Blend file](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/2545811/game_man_sketchbookb1.zip). I just open it and export what is currently selected.

**Comment by julienduroure** [comment]
I confirm that this issue occurs on 2.81a, but I am not able to reproduce it on current master.
Can you please test with a recent version of Blender (2.82 alpha) that you can download on https://builder.blender.org/download/ ?

**Comment by swift502** [comment]
Yep, no error in 2.82 Alpha.

**Comment by julienduroure** [comment]
Thanks !
