### ISSUE TITLE
IK still samples incorrectly

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#854]
@swift502 You're file (from #373) has lot of animation. Can you please tell me what animation are wrong, it will help me to find what can be wrong ?

Note: This is maybe link to the fact that you rig is wrong. You can't add an IK constraint to all your bone chain, because the upper bone (for example arm_upper.L is constraint two times (by IK constraint and by IK constraint of arm_lower.L). Not sure this can have some consequence on sample animation, (I have to check), but this is a rigging tip ;-)

**Comment by swift502** [comment]
I replaced the elbow and knee controllers with Pole Targets and everything's fine. 👍 
I learnt to do knees and elbows this way years ago and used it since, and it was always fine in Blender. There's so many tutorials out there teaching this "incorrect" method.
So why is it that Blender solves IK differently than the exporter? Is it the amount of samples, or the order of the bones?

Btw, there used to be another problem a year ago, where the leg IK didn't bake at all, but I couldn't replicate that issue now. So unless you see the IK discrepancies as a problem I'm fine with closing this issue. 👌

**Comment by julienduroure** [comment]
OK, thanks!
