### ISSUE TITLE
'Selected Objects' does not include selected cameras.

### ISSUE THREAD

**Issue by PirateJC** [KhronosGroup/glTF-Blender-IO#885]
With a camera selected, and choosing the 'selected objects,' the camera does not export. Currently you need to have the 'cameras' option checked. This seems broken. Selected objects should take into account ALL selected objects in the scene...meshes, cameras, lights..etc.

**Comment by julienduroure** [comment]
Well, I understand your point of view, but I think currently, the way it is working is:
- checkbox to add camera and/or light
- checkbox to restrict export to the selection only.
But if camera option is unchecked and a camera is selected, seems legit to not export it.

Maybe this is only wording, or maybe we should change options to be more simple

**Comment by PirateJC** [comment]
I think the part that makes it confusing is that we separate cameras and lights from the selection only option. Why don't we do the same thing with other elements as well?  Meshes, particles, etc. It seems like the thing that would make the most sense is to adopt one philosophy or another philosophy maybe?  Either we have individual check boxes for all of the object types, OR we let "selected objects" be a catch all for everything?  Currently it seems like our collective feet are partially in both camps, leading to confusion?  It's also possible that it's just me, but it definitely does not make immediate sense to me when I first use it.

**Comment by donmccurdy** [comment]
If both options are shown as they are now, then I agree they should be mutually exclusive — with "Selected Objects" enabled and "Cameras" disabled, a camera should never be exported. Blender's FBX exporter has the same options, and they behave the same way. The FBX exporter also adds more options as @PirateJC suggests, though:

<img width="252" alt="Screen Shot 2020-01-23 at 5 52 07 PM" src="https://user-images.githubusercontent.com/1848368/73039061-8ed25c00-3e09-11ea-8824-6fa47778493e.png">

No one has really asked for the ability to disable Meshes and Empties, so I'm hesitant to add those options right now (they wouldn't prevent this particular source of confusion, anyway). Additional text on the "Selected Objects" tooltip might be sufficient, unless this turns out to be a source of confusion for more users and requires a more complex fix?

**Comment by emackey** [comment]
I think cameras & lights are separate because they're a glTF extension, and the other exportable objects are glTF core.  If you haven't enabled the extension, the camera doesn't export.

I agree that's bad UX, but I don't think breaking out all those different object types is the right fix.  Maybe if "Selected Objects" is in use and cameras/lights are selected, we implicitly enable the extension?

**Comment by emackey** [comment]
Nevermind, cameras are core... sorry for the noise...

**Comment by julienduroure** [comment]
Hello,
Closing this ticket, as it is quite old, and this is not really a bug, the behaviour is the same than other exporter (fbx).
