### ISSUE TITLE
Traceback importing a glb file

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#887]
Traceback when trying to import file from #715 

![image](https://user-images.githubusercontent.com/1696020/73026009-edf79700-3e30-11ea-865f-737943d0a37b.png)

**Comment by scurest** [comment]
Ah, yeah I noticed missing images stopped working too.

Tracked it down to me breaking it in 7d9d567, because I changed the implicit invariant that:

> When `img_data, img_name = BinaryData.get_image_data(gltf, img_idx)`, if `img_name` is not None, then `img_data` is not None.

The best fix is probably to change

https://github.com/KhronosGroup/glTF-Blender-IO/blob/c0df87c5e413099d75e213b2100d73e3f674480b/addons/io_scene_gltf2/blender/imp/gltf2_blender_image.py#L94-L96

to test for `img_data is not None` instead.

**Comment by julienduroure** [comment]
Fixed by f0e0744
