### ISSUE TITLE
uv_textures or uv_layers?

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#92]
After fix from 
https://github.com/KhronosGroup/glTF-Blender-IO/commit/2381398a35e41910d346796abea06077a4120481,

I have a question:
- In blender 2.8, there is only uv_layers existing
- In blender 2.79, there is both uv_layers & uv_textures. Why use uv_textures or u_layers ?

Currently in master, we use uv_textures for 2.79 and uv_layers for 2.80

**Comment by scurest** [comment]
@julienduroure I think how it worked is if you looked in the Textured view, uv_layers[i] stored the UVs for each poly, and uv_textures[i] stored the image that would be shown on each poly. In 2.8 the Textured view is gone, and poly.material_index determines the material to show on each poly in the Material view.

Anyway, I guess it doesn't matter anymore since 2.79 support is gone.
