### ISSUE TITLE
Importing glTF with multiple animations fails to load all but one animation

### ISSUE THREAD

**Issue by elrnv** [KhronosGroup/glTF-Blender-IO#952]
**Description**
Importing a glb (or gltf) with multiple animation sequences will only load the first animation. The importer used to load all animations correctly in Blender 2.80, and since Blender 2.81a this stopped working.

**To Reproduce**
1. Unzip the example [box_rotate.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4264681/box_rotate.zip) of two identical box rotation animations saved as gltf/bin.
2. Import the gltf file in Blender 2.82 or 2.81a.
3. Scrubbing the playhead will only animate one of the meshes.

**Expected behavior**
Both given meshes should be animated (which is what happens in Blender 2.80).

**.blend file/ .gltf**
[box_rotate.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4264681/box_rotate.zip)

**Version**
 - OS: Pop!_OS 19.10
 - Blender Version 2.82

**Comment by scurest** [comment]
I'm the one who changed this, see #671. I think this is working correctly, but we can revisit it. I think @fire also [thought we should play the first action that can be played on an object.](https://github.com/KhronosGroup/glTF-Blender-IO/issues/862#issuecomment-571917870)

First, all the animations do get loaded, it's just that only the first animation plays.  
The animations are organized like this in the NLA editor:

![nla](https://user-images.githubusercontent.com/11024420/75509306-c013ee00-59ac-11ea-8a70-6ee3ee1d0c4c.png)

Why I think playing only the first animation is the right thing to do:

* This matches both the Three.js and Babylon.js viewer, which both play only the first animation by default.
* Each glTF animation is self-contained. There's no way to know that two animations should "play together". Sometimes it will be true, but we should be conservative and not assume that. Things that should always play together should be part of the same animation.
* If two animations target the same object and we tried to play both simultaneously, we'd have pick one animation that should "win" at that object, and we could wind up with part of one animation playing on one part of a scene and part of another animation playing somewhere else, creating a potentially nonsensical result animation that never existed in the glTF file.
* "Always plays the first animation" is easy to explain and understand.
* You can still set it up to do whatever you want by hand after import.

**Comment by scurest** [comment]
cc @julienduroure @donmccurdy @emackey

**Comment by donmccurdy** [comment]
@elrnv if the intention for gltfgen output is to have a scene with a single global animation timeline, played consecutively, then it would be best to output only a single animation rather than one per object. Playback in glTF viewers will behave more as you expect with that approach.

@scurest I agree with your points above. This model seems unusual in having N distinct animations each affecting exactly one of N objects, where (purely from a Blender artist's perspective) it would be understandable to expect one active Action on each object after importing. That's an unusual case, and not one we encourage glTF exporters to use, so I'm not necessarily saying we should try to detect it and handle it differently than the (easier to explain) behavior you describe.

**Comment by elrnv** [comment]
Ah that makes sense. I actually have not issue with this being the default behaviour. I think I just misunderstood how the animation system is supposed to work. I will adjust gltfgen to output a single animation. Thank you for the feedback!
