### ISSUE TITLE
Custom normals are lost when exporting w Apply Modifiers checked

### ISSUE THREAD

**Issue by Joel-Hjerten** [KhronosGroup/glTF-Blender-IO#975]
I'm losing custom normals when exporting using Apply Modifiers:
Blender 2.82 (Win 10 64-bit), web viewer https://gltf-viewer.donmccurdy.com/
[Bug.custom.normals.discarded.by.gltf.export.if.apply.modifiers.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4333677/Bug.custom.normals.discarded.by.gltf.export.if.apply.modifiers.zip)
![75896958-1a430200-5e38-11ea-8a1c-78ae011ba685](https://user-images.githubusercontent.com/18649705/76693441-2499a300-6665-11ea-9f08-958a53d59b89.jpg)

**Comment by julienduroure** [comment]
Probably a duplicate/linked to #799 and #877

**Comment by pafurijaz** [comment]
I add my issues here in order to avoid a duplicate, but I have a same problem with auto smooth with the similar issues, with unnecessary edges boundary inner the surfaces, here an examples of my export on CAD Assistant. Blender 2.83 Beta 
![Istantanea_2020-05-14_19-11-37](https://user-images.githubusercontent.com/11751383/81964642-26f18c80-9617-11ea-90fd-10d0c99a7d6b.png)

![Istantanea_2020-05-14_18-49-14](https://user-images.githubusercontent.com/11751383/81964647-2953e680-9617-11ea-9574-f133e2be67f6.png)

May 13, 23:10:33 - 71298a1da971
