### ISSUE TITLE
Scaling issue when non normalized quaternion

### ISSUE THREAD

**Issue by torbenvanassche** [KhronosGroup/glTF-Blender-IO#984]
**Describe the bug**
Mesh scale is weird when exported glb from blender.

**To Reproduce**
Export mesh from blender as gltf
Scaling is wrong(?) on export

**Expected behavior**
Export sucessfully with shape keys as morph targets for threejs

**Screenshots**
![image](https://user-images.githubusercontent.com/38832704/76998723-d848ae80-6955-11ea-8635-ddfa5228b47d.png)

**.blend file/ .gltf**
[scene (2).zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4350957/scene.2.zip)

**Version**
 - OS: [e.g. macOS, linux]
 - Blender Version 2.82.7

**Comment by donmccurdy** [comment]
The scale looks the same in both places to me:

blender
![Screen Shot 2020-03-18 at 12 46 46 PM](https://user-images.githubusercontent.com/1848368/77001096-99dfcf00-6916-11ea-9f2a-4e246f6f98d8.png)


threejs
![Screen Shot 2020-03-18 at 12 46 54 PM](https://user-images.githubusercontent.com/1848368/77001085-964c4800-6916-11ea-8fd1-a0a198d29d44.png)

Note both are about 6 units across. Could you explain what you mean by "scale is weird"?

**Comment by torbenvanassche** [comment]
there is amesh 3d printer in that gltf file scene. thats the only one so far that has shape keys.
I do understand my explanation was kinda subpar. bottom right corner the mesh is really not as it should be

**Comment by donmccurdy** [comment]
Hah ok I see it now, thanks! We'll take a look.

**Comment by julienduroure** [comment]
Ok, find the root cause, and I am able to reproduce on simpler scene:

![image](https://user-images.githubusercontent.com/1696020/77042441-f21cdc80-69bb-11ea-8b85-92e1b1f4be2a.png)


This is linked to a non normalized quaternion rotation on your 3D printer (object with parent having a scale)
Change 3D printer rotation from:
![image](https://user-images.githubusercontent.com/1696020/77042518-111b6e80-69bc-11ea-93b1-eca3210aa27b.png)

To:
![image](https://user-images.githubusercontent.com/1696020/77042538-1e385d80-69bc-11ea-8368-5372aa6feb77.png)


Will solve the issue

**Comment by torbenvanassche** [comment]
I'll confirm that worked and fixed it. Thank you for the (especially fast) help.
