### ISSUE TITLE
Blender 2.82a glTF 1.2.18 Exports PSD as JPG, there is no PNG option any more

### ISSUE THREAD

**Issue by Joel-Hjerten** [KhronosGroup/glTF-Blender-IO#986]
<img width="196" alt="Annotation 2020-03-19 043449" src="https://user-images.githubusercontent.com/18649705/77029096-0bf9f780-699b-11ea-8c39-f5404c6a1d71.png">

Blender 2.82a with Manually updated glTF Exporter 1.2.18 from Blender 2.83 (1.2.18) as well as the downloaded 1.2.48 from git repo.

Need the exported textures to be in PNG format from my working PSD textures, can't have them being saved to JPG as we need to do arbitrary post export compression of textures to work within our games size limits.

[Bug Blender 2.82a glTF 1.2.18 Exports PSD as JPG, there is no PNG option any more.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4352517/Bug.Blender.2.82a.glTF.1.2.18.Exports.PSD.as.JPG.there.is.no.PNG.option.any.more.zip)

**Comment by scurest** [comment]
This was changed by #882.

It seems that though Blender can open PSDs, internally it just converts it to a JPEG, which is why the exporter treats it like one. If you check the `image.file_format` field it's `'JPEG'`, if you go to "Save As" Blender will try to save it as a JPEG, etc.

What we could do is check if the image came from a file and that file ends in `.psd`/.PSD`, and use PNG in that case.

This also means it's possible to have an image that's `JPEG` format, but whose file on disk isn't a JPEG. Will need to check that that's handled correctly...
