### ISSUE TITLE
Cannot import GLB from Tiltbrush

### ISSUE THREAD

**Issue by SamuelAB** [KhronosGroup/glTF-Blender-IO#990]
**Describe the bug**
When importing a GLB from a Google Tiltbrush export, it does not work.

**To Reproduce**
1. Go to IMPORT
2. Click on GLtf 2.0
3. Select the file to import

**Expected behavior**
Importing the file should work

**Screenshots**
![image](https://user-images.githubusercontent.com/10355335/77181855-4ac6a500-6aa2-11ea-912d-9930cd3c3052.png)

**.blend file/ .gltf**
included GLB file
[TEST FILE.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4360613/TEST.FILE.zip)

**Version**
 - OS: Windows 10
 - Blender Version: 2.82

**Additional context**
These files originate from Google Tiltbrush

**Comment by julienduroure** [comment]
I can't reproduce here on linux.
Trying with https://gltf-viewer.donmccurdy.com/, seems that the validator has 1 error linked to texture uri

**Comment by donmccurdy** [comment]
The error is because my viewer doesn't support absolute URLs to external resources. In this case, there's a full URL for this image:

https://www.tiltbrush.com/shaders/brushes/TaperedMarker-d90c6ad8-af0f-4b54-b422-e0f92abe1b3c/TaperedMarker-d90c6ad8-af0f-4b54-b422-e0f92abe1b3c-v10.0-MainTex.png

The file itself is valid, as the warnings are minor. 

I'm not sure whether it's reasonable for us to support absolute URLs of resources in this importer though. I wonder if tilt brush could export a self-contained file instead?

**Comment by julienduroure** [comment]
Thanks Don for the update.
Anyway, I don't have any traceback here

**Comment by scurest** [comment]
I get that traceback on the `blender-v2.82-release` branch, but not on master.

**Comment by SamuelAB** [comment]
@scurest I seem to have the latest version of Blender c.82a
How can I try the newer "fixed" version?

**Comment by scurest** [comment]
Either reinstall the addon from the master branch in your copy of Blender 2.82, or download a 2.83 beta from https://builder.blender.org/download/.
