### ISSUE TITLE
Import/Perf: question about #922

### ISSUE THREAD

**Issue by scurest** [KhronosGroup/glTF-Blender-IO#996]
I want to ask a question about #922. For me it seems to be slower instead of faster.

* When I say `before`, I mean 1900252, the last commit before #922 went in.
* When I say `after`, I mean 354045d, the merge commit for #922.

Since #922, for each primitive we process all the elements in the COLOR_0 array with the linear->sRGB conversion instead of only the ones used by the current primitive. This means we've slowed down in the case where a primitive uses only part of the whole array.

I made [a test file](https://github.com/KhronosGroup/glTF-Blender-IO/files/4382910/sphere.zip) that demonstrates this. It's a sphere broken into six primitives sharing one COLOR_0.

| | before | after |
|:---|:---|:---|
| sphere.gltf | 1.7s | 2.6s |

So I went to test the file from [T72167](https://developer.blender.org/T72167) and found that for me _that_ is actually consistently slower after #922 too. Times are with _Shading > Smooth Shading_. (Note: you'll probably need >4GB of RAM for this import to work)

| | before | after |
|:---|:---|:---|
|modelGroup.glb|112s|115s|

Can someone else test modelGroup.glb with 1900252 and 354045d and see what times you're getting?

**Comment by julienduroure** [comment]
Tagging as 2.83 milestone, in case we need to revert #922

**Comment by garyo** [comment]
I see the point -- thanks! When there are far fewer vertices than there are colors in the array, my speedup will slow things down instead because it always processes all the colors. I see two ways to speed it up: I can only convert the array elements actually used (at some startup cost to find them), or I can just switch back to the old one-by-one method if the count of vertices is much less than the length of the colors array (maybe 10x, but I can try a few tests). Or maybe a hybrid of the two. I'll look into it shortly. (About how much time do I have before risking missing the 2.83 deadline?)

**Comment by scurest** [comment]
My main point though was that I don't see any improvement from #922 at all (ie even when the whole COLOR_0 array is used). Like I said, for me the modelGroup.glb file imports faster before #922 than after. Does anyone else see that happen?

**Comment by garyo** [comment]
Hmm, weird -- that's the exact file I used when making the change. It sped up a lot for me. What OS & CPU are you on? I'm on a 32-thread Ryzen 1950X so the multithreading of numpy is probably where a lot of my speedup's coming from. (Also you get it to load in 112 sec which is great -- it's a lot slower than that for me without my fix, more like 300 sec if I remember correctly.)

**Comment by scurest** [comment]
Linux / FX8350. A Ryzen should be much faster so it's really weird that it would be slower. Even with _Use Normal Data_ I only get like 150s before. Can you post your times on those two commits I mentioned above?

**Comment by julienduroure** [comment]
> About how much time do I have before risking missing the 2.83 deadline?

Deadline for 2.83 bugfixing is end of April

**Comment by scurest** [comment]
@julienduroure What times do you get?

**Comment by julienduroure** [comment]
With modelGroup.glb, with smooth shading, on my laptop i7-4710HQ CPU @ 2.50GHz × 8 

Before : 76.63
After: 80.36

**Comment by garyo** [comment]
Weird. I'll retest today. Just so we're doing the same thing, are you using one build of Blender for both tests and symlinking/copying the addons folder from this repo into it?
Also I'm on Windows. I can do some other OS tests but not for a few days.

Actually I remember now that my [original work](https://developer.blender.org/T72167) based on the nightly Blender version I was using then had some other speedups, some of which were already incorporated here by the time I submitted my PR, so my original 5 minute timing was with a slightly older version of glTF-Blender-IO -- I'll get you my accurate before/after numbers today.

**Comment by scurest** [comment]
Okay, thanks.

> Just so we're doing the same thing, are you using one build of Blender for both tests and symlinking/copying the addons folder from this repo into it?

Yeah.

**Comment by garyo** [comment]
I confirm that it's the same or slower with my patch now.  
Timings as reported by Blender console (wallclock is slightly slower but uniformly so):
* Sphere before: 1.34, after: 2.06
* modelGroup before: 98.5, after: 97.3
Not sure what went wrong; I'm investigating. Thanks for noticing this!

**Comment by scurest** [comment]
Alright, since it looks like its the same or slower I think we should back it out then.

We can also probably make up any small difference by just using `**` instead of `pow` in the color_management code. This only buys me 4 seconds but it's free for us to do.

**Comment by garyo** [comment]
Actually would you mind holding off backing it out for a few days? I have some further improvements that certainly ought to help, based on my current patch.

**Comment by scurest** [comment]
Sure.

**Comment by garyo** [comment]
OK, by doing a bunch more stuff I got the import time for my particular test case down to 90 sec, but the sphere test case is still just as slow (it re-converts the color accessor multiple times; caching would help). And the way I had to do it is not particularly clean. It's at https://github.com/garyo/glTF-Blender-IO/tree/garyo/gltf-import-speedup-experiments just for the record. 
The main thing I did in the branch above is to use numpy to get data from accessors, rather than iterating with `struct.unpack_from`, which creates a python int/float for each element (slow and causes GC). It helps. Building the tris from indices gets faster, for instance. But since the rest of the code, especially creating the Blender objects themselves, requires python lists, eventually you usually end up creating a list. In some cases `np.frombuffer()` -> `np.tolist()` is still faster, but not always and not by enough. And the numpy method doesn't work well if the accessor is sparse, so I had to add cases for that. 
I think the only way to get a real speed increase is to add a numpy interface to the core blender object creation functions `BMFaceSeq` and `BMVertSeq` (and maybe `BMesh.to_mesh`). If those existed, almost all the import code could be array-based and _much_ faster. And of course it should be multithreaded, but, sigh, GIL.
So, sadly I have to agree, you should go ahead & back out my patch for now.

I'm more than willing to spend whatever time is needed to speed this stuff up; importing my test model into three.js is pretty much instantaneous, while importing into Blender takes 100 sec - for my app this is a serious issue. It's just going to take more work.

**Comment by scurest** [comment]
Hmm, that's too bad.

I know the FBX importer uses `mesh.polygons.foreach_set('loop_start')` and `mesh.polygons.foreach_set('loop_total')` to create polys which is supposed to be faster. It also doesn't use bmesh (there was a reason we do but I don't remember it). But AFAIK there is no `foreach` way to set vertex colors...

Anyway, I'll send the PR to back it out. Should make it for 2.83.

**Comment by garyo** [comment]
If there's a faster way to create polys, I'm happy to try that out -- especially if you can remember what the gotchas might be, i.e. why glTF import uses BMesh instead. Just quickly looking at the source in `bpy_rna.c` it looks like `foreach_set` should directly take a buffer (or a numpy array). Interesting!

**Comment by scurest** [comment]
I think it used a bmesh just because I couldn't find the API for some stuff on a regular mesh. If you can do everything without a bmesh that would obviously avoid incurring the `to_mesh` conversion though.

Look at `blen_read_geom` in `scripts/addons/io_scene_fbx/import_fbx.py`. They add a whole batch of verts/polys at once and set them in a batch from an array. You have to handle degenerate/duplicate tris differently (with `mesh.validate`) and you'd have to figure out how to handle normals.

**Comment by julienduroure** [comment]
Closed by c0118a3

**Comment by scurest** [comment]
I tried doing some of this in a branch. It's buggy obviously but here:

[import-numpy-experiment](https://github.com/KhronosGroup/glTF-Blender-IO/compare/905798...scurest:import-numpy-experiment?expand=1)

So I used your `np.frombuffer` to decode accessors to numpy arrays and also the numpy code for linear->sRGB, but all the mesh creation code was re-written to make the mesh directly with foreach_set (no bmesh). I didn't finish implementing everything (normalization, modes, morph targets, retargeting), but there's enough for a lot of models.

This brings modelGroup.glb with smooth shading down to 70s on my PC (down ~35%). MetalRoughSpheres also comes down by about half.

OTOH its harder to set the vertex groups for skinning without bmesh and skinned models are sometimes slower than master, but maybe there's a better way ([this](https://github.com/scurest/glTF-Blender-IO/blob/b8a9978b2f14ec6d4c077ba340f1f02c7059abff/addons/io_scene_gltf2/blender/imp/gltf2_blender_mesh.py#L406-L424) is how I did it). Also I didn't implement retargeting onto the bind pose, which seems hard to do with numpy.

Anyway, I was just wondering exactly how much performance we've left on the table.

**Comment by scurest** [comment]
I timed modelGroup.glb for how long it takes to do some of the non-negotiable stuff. Doing these are absolutely required to create the mesh (at least if you do it this way), so they put a lower bound on how fast we can get

* Time spent doing foreach_sets to create all verts/loops/polys: 9.7 s
* Time spent in normals_split_custom_set_from_vertices: 14.6 s
* Time spent doing foreach_sets to create vertex colors: 17.7 s
* Time spent doing mesh.validate: 10.6 s

That gives a total of 52 s as the minimum possible import time with this method.

Though it's possible that foreach_set might be faster with a different type of array (depending on the dtype or something) I guess.

Btw, the color conversion linear->sRGB is about 7.8 s.
